### ISSUE TITLE
tour: missing share button on embedded playground

### ISSUE THREAD

**Issue by Wessie** [golang/go#11011]
Not much to add, I recall the older version did have the button. People asking for help with a tour exercise now have to go through an extra step to share their code.

**Comment by adg** [comment]
@campoy what do you think?

**Comment by campoy** [comment]
This should be easy enough. I'll work on it soon (probably this week).

**Comment by kytrinyx** [comment]
Fixed in golang/tour@f0da76323f586944223a7fb12eb2665b91038859

**Comment by adg** [comment]
Actually, that change a "Feedback" button, not a "Share" button like the one that appears on play.golang.org. This issue is still valid.

**Comment by kytrinyx** [comment]
Ah, I was fooled by the "asking for help" part.

**Comment by ysmolsky** [comment]
Closing since it belongs to tour project and it's own bug tracker.
