### ISSUE TITLE
x/tools/cmd/oracle: doesn't work with GO15VENDOREXPERIMENT

### ISSUE THREAD

**Issue by ereyes01** [golang/go#12459]
I was directed to open this issue here in #12278.

It appears that x/tools/cmd/oracle doesn't honor the GO15VENDOREXPERIMENT when resolving dependencies. Here is a small example illustrating the problem:

```
$ echo $GOPATH
/home/ereyes/code/oracle-vendor-issue
$ pwd
/home/ereyes/code/oracle-vendor-issue
$ find src/a
src/a
src/a/vendor
src/a/vendor/b
src/a/vendor/b/b.go
src/a/a.go
$ cd src/a
$ cat a.go
package main

import (
	"b"
	"fmt"
)

func main() {
	fmt.Println("Hello from a!")

	b.Hello()
}
$ cat vendor/b/b.go 
package b

import "fmt"

func Hello() {
	fmt.Println("Hello from b!")
}
$ go version
go version go1.5 linux/amd64
$ GO15VENDOREXPERIMENT=1 go run a.go
Hello from a!
Hello from b!
$ go get golang.org/x/tools/cmd/oracle
$ GO15VENDOREXPERIMENT=1 $GOPATH/bin/oracle -pos=./a.go:44 callees a
/home/ereyes/code/oracle-vendor-issue/src/a/a.go:4:2: could not import b (cannot find package "b" in any of:
	/home/ereyes/code/go-1.4/src/b (from $GOROOT)
	/home/ereyes/code/oracle-vendor-issue/src/b (from $GOPATH))
/home/ereyes/code/oracle-vendor-issue/src/a/a.go:11:2: undeclared name: b
oracle: couldn't load packages due to errors: a
$
```

Thanks, Eddy

**Comment by ianlancetaylor** [comment]
As noted on the other issue, the right place to fix this might be the go/build package.

**Comment by abourget** [comment]
Is that fixed here ? https://github.com/golang/go/issues/12278

**Comment by adonovan** [comment]
It is about 95% fixed.  The oracle and other loader-based tools now mostly work with vendoring, but there a few minor bugs still to fix.

**Comment by alandonovan** [comment]
Fixed by these CLs:
https://go-review.googlesource.com/17727
https://go-review.googlesource.com/18053
https://go-review.googlesource.com/18318
https://go-review.googlesource.com/18452
https://go-review.googlesource.com/18457
