### ISSUE TITLE
runtime: gcAssistAlloc can call itself recursively

### ISSUE THREAD

**Issue by deft-code** [golang/go#12894]
This occurs in Go 1.5.1 possibly 1.5.0 as well.
gcAssistAlloc may decide to sleep for 200us. This results in allocating a timer object and eventually ending up in gcAssistAlloc again.

gcAssistAlloc -> time.Sleep -> builtin.new -> mallocgc -> gcAssistAlloc -> ...

sanitized snippet from debug/pprof/heap?debug=1
    #       0x123456        time.Sleep+0x37                 go/gc/src/runtime/time.go:53
    #       0x123456        runtime.gcAssistAlloc+0x23e     go/gc/src/runtime/mgcmark.go:295
    #       0x123456        runtime.mallocgc+0x535          go/gc/src/runtime/malloc.go:711
    #       0x123456        runtime.newobject+0x42          go/gc/src/runtime/malloc.go:760
    #       0x123456        time.Sleep+0x37        go/gc/src/runtime/time.go:53
    #       0x123456        runtime.gcAssistAlloc+0x23e     go/gc/src/runtime/mgcmark.go:295
    #       0x123456        runtime.mallocgc+0x535       go/gc/src/runtime/malloc.go:711
    #       0x123456        runtime.newobject+0x42      go/gc/src/runtime/malloc.go:760

**Comment by ianlancetaylor** [comment]
Is this fixed now?  In both 1.5 branch and tip?

**Comment by aclements** [comment]
Yes. It was fixed on master by 65aa2d6 and on the 1.5 branch by c257dfb.

**Comment by aclements** [comment]
The fix on the 1.5 branch (c257dfb) isn't quite correct. We were able to verify that it reduces but does not eliminate the issue. I believe the recursion can still happen at the beginning of a GC cycle when gp.gcscanwork is also small or zero. I'm working on a better fix, which we'll try to verify more thoroughly.

**Comment by aclements** [comment]
Fixed (for real this time) on release branch by 71a7647.
