### ISSUE TITLE
x/mobile: Java to Go bindings crashes with  java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by sureshg** [golang/go#12951]
I have a sample Android app with Java to Go bindings, built using gomobile bind command. When i try to run this code on Nexus 5 (Android 6) it's always crashing with ` java.lang.UnsatisfiedLinkError.../libgojni.so: has text relocations`. I am not sure whether this is the right repo to report x/mobile issues. Reporting it here because i didn't find any option in `golang/mobile`

SDK Version
```
android {
    compileSdkVersion 23
    buildToolsVersion "23.0.1"

    defaultConfig {
        minSdkVersion 16
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
    }
```

Go bind gradle plugin
```
go version go1.5.1 darwin/amd64

plugins {
    id "org.golang.mobile.bind" version "0.2.2"
}
```
```
10-15 16:08:26.634 1632-1662/io.test.gopherandy I/OpenGLRenderer: Initialized EGL, version 1.4
10-15 16:08:28.242 1632-1632/io.test.gopherandy D/AndroidRuntime: Shutting down VM
10-15 16:08:28.256 1632-1632/io.test.gopherandy E/AndroidRuntime: FATAL EXCEPTION: main
10-15 16:08:28.256 1632-1632/io.test.gopherandy E/AndroidRuntime: Process: io.test.gopherandy, PID: 1632
10-15 16:08:28.256 1632-1632/io.test.gopherandy E/AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: /data/app/io.test.gopherandy-2/lib/arm/libgojni.so: has text relocations
10-15 16:08:28.256 1632-1632/io.test.gopherandy E/AndroidRuntime:     at java.lang.Runtime.loadLibrary(Runtime.java:372)
10-15 16:08:28.256 1632-1632/io.test.gopherandy E/AndroidRuntime:     at java.lang.System.loadLibrary(System.java:1076)
10-15 16:08:28.256 1632-1632/io.test.gopherandy E/AndroidRuntime:     at go.LoadJNI.<clinit>(LoadJNI.java:5)
10-15 16:08:28.256 1632-1632/io.test.gopherandy E/AndroidRuntime:     at java.lang.Class.classForName(Native Method)
10-15 16:08:28.256 1632-1632/io.test.gopherandy E/AndroidRuntime:     at java.lang.Class.forName(Class.java:324)
10-15 16:08:28.256 1632-1632/io.test.gopherandy E/AndroidRuntime:     at java.lang.Class.forName(Class.java:285)
10-15 16:08:28.256 1632-1632/io.test.gopherandy E/AndroidRuntime:     at go.Seq.<clinit>(Seq.java:23)
10-15 16:08:28.256 1632-1632/io.test.gopherandy E/AndroidRuntime:     at go.hello.Hello.Greetings(Hello.java:13)
```

**Comment by crawshaw** [comment]
This is the same as #12890.

I believe you can build with targetSdkVersion=22, but this may have been fixed by 82d11f. Could you try syncing to the latest gomobile and running init and bind again?

**Comment by crawshaw** [comment]
@sureshg please reopen this issue if this is not fixed by the latest version of gomobile.

**Comment by sureshg** [comment]
@crawshaw yeah cleaned up the existing gomobile (if that matters) and ran the following commands with new gradle plugin ("org.golang.mobile.bind" version "0.2.3") . Still having the same issue. Did i miss anything?

``` 
  $  go get -u golang.org/x/mobile/cmd/gomobile && gomobile init
  $ ./gradlew -b gobuild/build.gradle gobind 
```

```
0-15 19:26:31.474 22685-22685/io.test.gopherandy E/AndroidRuntime: FATAL EXCEPTION: main
10-15 19:26:31.474 22685-22685/io.test.gopherandy E/AndroidRuntime: Process: io.test.gopherandy, PID: 22685
10-15 19:26:31.474 22685-22685/io.test.gopherandy E/AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: /data/app/io.test.gopherandy-2/lib/arm/libgojni.so: has text relocations
10-15 19:26:31.474 22685-22685/io.test.gopherandy E/AndroidRuntime:     at java.lang.Runtime.loadLibrary(Runtime.java:372)
10-15 19:26:31.474 22685-22685/io.test.gopherandy E/AndroidRuntime:     at java.lang.System.loadLibrary(System.java:1076)
10-15 19:26:31.474 22685-22685/io.test.gopherandy E/AndroidRuntime:     at go.LoadJNI.<clinit>(LoadJNI.java:5)
10-15 19:26:31.474 22685-22685/io.test.gopherandy E/AndroidRuntime:     at java.lang.Class.classForName(Native Method)
10-15 19:26:31.474 22685-22685/io.test.gopherandy E/AndroidRuntime:     at java.lang.Class.forName(Class.java:324)
10-15 19:26:31.474 22685-22685/io.test.gopherandy E/AndroidRuntime:     at java.lang.Class.forName(Class.java:285)
10-15 19:26:31.474 22685-22685/io.test.gopherandy E/AndroidRuntime:     at go.Seq.<clinit>(Seq.java:23)
10-15 19:26:31.474 22685-22685/io.test.gopherandy E/AndroidRuntime:     at go.hello.Hello.Greetings(Hello.java:13)
10-15 19:26:31.474 22685-22685/io.test.gopherandy E/AndroidRuntime:     at io.test.gopherandy.MainActivity$1.onClick(MainActivity.java:26)```

**Comment by ekrivenja** [comment]
@sureshg, update just gomobile is not enough, see #12890 last messages.
