### ISSUE TITLE
Stackoverflow on a heap array

### ISSUE THREAD

**Issue by Opposition** [golang/go#14028]
Taken this toy example, that calculates prime numbers: http://play.golang.org/p/XrUCUvC7In

Building this with <b> go build -gcflags -m </b> shows following output

<b>
moved to heap: arr
moved to heap: x
</b>

However, running the program I get following error: 

runtime: goroutine stack exceeds 1000000000-byte limit
fatal error: stack overflow

runtime stack:
runtime.throw(0x470f80, 0xe)
        c:/go/src/runtime/panic.go:527 +0x97
runtime.newstack()
        c:/go/src/runtime/stack1.go:800 +0xb25
runtime.morestack()
        c:/go/src/runtime/asm_amd64.s:330 +0x87

goroutine 1 [stack growth]:
main.main()
        C:/Users/Daniel/Desktop/rensir.go:27 fp=0xc0c202be50 sp=0xc0c202be48
runtime.main()
        c:/go/src/runtime/proc.go:111 +0x27e fp=0xc0c202bea0 sp=0xc0c202be50
runtime.goexit()
        c:/go/src/runtime/asm_amd64.s:1721 +0x1 fp=0xc0c202bea8 sp=0xc0c202bea0

Is it supposed to get a stackoverflow, if it is a heap object?

Go version: go1.5.3 windows/amd64
OS: windows 7 64 bit

**Comment by dominikh** [comment]
Simpler example that reproduces the problem:

```
package main

func fn() (arr [1e9]bool) {
	for range arr {
	}
	return
}

func main() {
	fn()
}
```

Without the loop it's fine.

**Comment by kostya-sh** [comment]
`range arr` puts arr on the stack.

The following example:

    package main

    func fn() (arr [1e10]bool) {
        for range arr {
        }
        return
    }

    func main() {
        fn()
    }

fails to compile with "stack frame too large (>2GB)" error. It looks like compiler and runtime disagree about the maximum stack frame size.

**Comment by kostya-sh** [comment]
The following example compiles though:

    func fn() (arr [1e10]bool) {
        for _ = range arr {
        }
        return
    }

so `range arr` puts `arr` on the stack unnecessarily.

The following example doesn't compile (correctly IMHO):

    func fn() (arr [1e10]bool) {
        for _, v := range arr {
            _ = v
        }
        return
    }

**Comment by bradfitz** [comment]
cc @randall77 as fun tests to add to the ssa branch too

**Comment by kostya-sh** [comment]
Sorry, ignore my last comment. I didn't test it properly ;)

**Comment by minux** [comment]
Did you know that `for range arr` makes a copy of the array
(onto stack)?

**Comment by kostya-sh** [comment]
@minux, `for range arr` (and `for i := range arr`) doesn't make a copy of the array onto stack. But `for _, v := range arr` does.

**Comment by mdempsky** [comment]
Simpler repro:

    package main

    //go:noinline
    func fn() (arr [1e9]bool) {
        return
    }

    func main() {
        fn()
    }

Discussion about the `for` loop is a red herring. It just prevented inlining.

The issue seems to be that when we're warning about stack frames that are >1GB, we're failing to include the space reserved for calling other functions. In the example above, main needs to allocate 1GB of stack space for fn's return values, but we're not including that space in the test.

**Comment by josharian** [comment]
We’ve fixed a bunch of similar bugs recently. I’m AFK for a while but I’d wager this is now fixed, if someone wants to double-check.

**Comment by fraenkel** [comment]
They still fail like they did in 1.11.4.
I tested with 
go version devel +5073bf3886 Thu Jan 3 22:51:08 2019 +0000 linux/amd64
