### ISSUE TITLE
Segmentation fault on 'go get' on Ubuntu LTS

### ISSUE THREAD

**Issue by andreydroid** [golang/go#15429]
1. What version of Go are you using (`go version`)?
go version xgcc (Ubuntu 4.9.3-0ubuntu4) 4.9.3 linux/amd64

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOCHAR="6"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/username/GoProjects"
GORACE=""
GOROOT="/usr"
GOTOOLDIR="/usr/lib/gccgo/tool"
TERM="dumb"
CC="gcc"
GOGCCFLAGS="-g -O2 -fPIC -m64 -pthread"
CXX="g++"
CGO_ENABLED="1"

3. What did you do?
go get github.com/linkedin/burrow

4. What did you expect to see?
Get an installed package

5. What did you see instead?
Segmentation Fault
[Core dump](https://s3.amazonaws.com/wix-shareable/go-core.gz)

**Comment by davecheney** [comment]
It looks like your using Ubuntu's go cgo installation, was that what you intended? On Ubuntu the name of the go distribution is golang-go

**Comment by andreydroid** [comment]
Thanks for the quick response. My intention was to install the 'go' command. Looks like gccgo-go was installed by default to resolve this dependency. I've removed gccgo-go and installed golang-go instead as you suggested and the segfault went away.

**Comment by davecheney** [comment]
Sorry about that, I know it's not ideal.

**Comment by bradfitz** [comment]
So there's not a bug? Already fixed in gccgo?

**Comment by andreydroid** [comment]
The problem is still there in Ubuntu 14.04 LTS. But I was convinced that it's an issue with apt-get's recommendation for golang (gccgo-go package picked instead of golang-go) rather than a bug with Go itself.

**Comment by davecheney** [comment]
If you do

[sudo] apt-get install golang-go

That will solve the problem. However, unless you have the trusty-backports
repo enabled, you'll get Go 1.2.1. Can I suggest that you use the tarball
from the golang.org website instead, it is well tested and known to work.
