### ISSUE TITLE
x/mobile/bind: XCode warning then build project with gomobile framework for non-64bit device

### ISSUE THREAD

**Issue by ekrivenja** [golang/go#15519]
I am using

> go version go1.6.2 darwin/amd64
> gomobile version +c435d0b Wed Apr 27 17:00:39 2016 +0000 (android,ios); androidSDK=

My issue is minor and very related to fixed #12590, the crash is fixed, but warning is still there if I try to build my XCode project with gomobile framework, for device like iPad 2 (non-64 bit A5 chip on board)

The warning message:

> ld: warning: PIE disabled. Absolute addressing (perhaps -mdynamic-no-pic) not allowed in code signed PIE, but used in main.init from /Users/... To fix this warning, don't compile with -mdynamic-no-pic or link with -Wl,-no_pie

The same build for iPad Pro (64bit A9X on board) is going without any warning.
My gomobile framework is built with default parameters `gomobile bind -target=ios <package>`

**Comment by eliasnaur** [comment]
Sounds like a duplicate of https://github.com/golang/go/issues/12896 which was recently fixed. Could you please try Go tip and see if your issue is still present?

**Comment by ekrivenja** [comment]
You are right, looks like CL https://golang.org/cl/22461 should fix this issue. I'll try Go tip, thank you.

**Comment by ekrivenja** [comment]
Yes, it is fixed. Tested on

> go version devel +082881d Wed May 4 15:08:16 2016 +0000 darwin/amd64

**Comment by ekrivenja** [comment]
Sorry, but warning is still there. I tested on

> go version devel +082881d Wed May 4 15:08:16 2016 +0000 darwin/amd64

**Comment by ekrivenja** [comment]
The issue is with ARMv7 only, if I remove it from Valid Architectures list, any build (ARMv7s, ARM64) has no warning.

**Comment by eliasnaur** [comment]
Thank you, I've reproduced the issue. The Go c-archive tests seems to run as PIE now, so it seems gomobile is doing something that breaks PIC generation. I'm working on a fix.

**Comment by ekrivenja** [comment]
Yes, it is fixed in

> go version devel +87a2ae1 Mon May 9 06:16:07 2016 +0000 darwin/amd64

Thank you, @eliasnaur

**Comment by wxiaoguang** [comment]
I am using "go version go1.7beta1 darwin/amd64" and gomobile "tip.

I still get the no_pic warning:
(null): PIE disabled. Absolute addressing (perhaps -mdynamic-no-pic) not allowed in code signed PIE, but used in main.init from /..../NetConnMan(go.o). To fix this warning, don't compile with -mdynamic-no-pic or link with -Wl,-no_pie

**Comment by eliasnaur** [comment]
If you haven't already, please check if the golang.org/x/mobile/examples/bind example also produces the PIC warning. If not, the next step would be to figure out why the projects differ in behaviour. A minimal reproducer would allow us to fix this issue quicker.
