### ISSUE TITLE
cmd/compile: poor error message when invoking method on embedded type

### ISSUE THREAD

**Issue by dsymonds** [golang/go#15711]
Please answer these questions before submitting your issue. Thanks!
1. What version of Go are you using (`go version`)?

go1.6.2
1. What operating system and processor architecture are you using (`go env`)?

The playground
1. What did you do?

https://play.golang.org/p/hsjwmQwtsb

Relevant snippet:

``` go
func TestFoo(t *testing.T) {
    t.Fail("what?")
}
```
1. What did you expect to see?

```
prog.go:14: too many arguments in call to t.Fail
```
1. What did you see instead?

```
prog.go:14: too many arguments in call to t.common.Fail
```

The `.common` bit is unexpected and an implementation detail. Running `godoc testing Fail` shows a simple method `func (c *T) Fail()`, and the fact that `testing.T` embeds `testing.common` does not seem useful.

**Comment by odeke-em** [comment]
This bug can now be closed. With Go1.8 +e776975, we'll now have a nice message talking about `t.common.Fail` failing instead of just `t.Fail`, and that was even fixed in Go1.7
<img width="688" alt="screen shot 2017-01-03 at 1 28 12 am" src="https://cloud.githubusercontent.com/assets/4898263/21602680/efaba5de-d153-11e6-8eb1-12965a9bd67b.png">


```shell
$ go run main.go 
# command-line-arguments
./main.go:14: too many arguments in call to t.common.Fail
	have (string)
	want ()
```

The too many arguments improved message was implemented in  https://go-review.googlesource.com/25156.

I'll let @bradfitz close it so that we can properly triage and note it as a Go1.7/8 fixed bug.

**Comment by ianlancetaylor** [comment]
I don't think tracking setting the milestone of a closed bug to a closed milestone makes much difference.  Closing this issue.

**Comment by dsymonds** [comment]
Sorry, this isn't fixed. My complaint wasn't about the "too many arguments" part. It was about the error referring to the unexported embedded type.

```shell
$ go version
go version devel +d698e614a2 Tue Jan 3 19:23:23 2017 +0000 linux/amd64
$ go test
...
./x_test.go:6: too many arguments in call to t.common.Fail
        have (string)
        want ()
```

That `t.common.Fail` is the problematic part. My code doesn't (and can't) refer to `t.common`.

**Comment by odeke-em** [comment]
Am sorry about that @dsymonds and @ianlancetaylor, I totally misunderstood that issue, that 1AM clarity. Yap your issue still stands.

**Comment by linsite** [comment]
2025.3.5 updates

hi, @dsymonds, newly test with Go 1.24 shows as below.

```
./prog.go:14:9: too many arguments in call to t.Fail
	have (string)
	want ()

Go build failed.
```
