### ISSUE TITLE
x/tools/cmd/godoc: wrong indentation for inline examples

### ISSUE THREAD

**Issue by ALTree** [golang/go#16746]
First line is not indented, every other line is. A couple examples:

https://golang.org/pkg/go/printer/#example_Fprint
https://golang.org/pkg/archive/zip/#example_Reader

note the the actual code (in the source file) is correctly indented.

**Comment by rakyll** [comment]
It looks like the tip is working correctly and there has been a line trims the extra whitespace in the pre block at https://github.com/golang/tools/blame/master/godoc/godoc.go#L463.

@broady, are we running an old version of godoc on the website?

**Comment by broady** [comment]
Nope, I deployed it yesterday from `release-branch.go1.7`

**Comment by biztos** [comment]
Hi there.  I see this bug still expressed on golang.org but not on godoc.org:

https://godoc.org/go/printer#ex-Fprint

(I had naïvely assumed they used the same code to generate the docs and just differed in the stylesheets, but it seems that's not the case.)

**Comment by ALTree** [comment]
Mmh, I honestly don't remember if godoc.org was affected when I opened this issue; I focused on golang.org because that's where I saw the issue first.

**Comment by broady** [comment]
This will be fixed when Go 1.8 rolls out to golang.org. (~1 March)
