### ISSUE TITLE
A suspicious bug about panic 

### ISSUE THREAD

**Issue by zhexuany** [golang/go#18431]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.7 linux/amd64
### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/dev-super/repo/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build024474410=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"

### What did you do?
~~~
func checkError (err error) {
    if err != nil {
		panic(err)
    }
}

type Error struct {
    errCode uint8
}
func (e *Error) Error() string {
        switch e.errCode {
        case 1:
                return "file not found"
        case 2:
                return "time out"
        case 3:
                return "permission denied"
        default:
                return "unknown error"
         }
}

func main() {
    var e *Error
    checkError(e)
}
~~~
### What did you expect to see?
It should be panic.

### What did you see instead?
But this snippet hangs in background. 

The strace report is the following:

~~~
2855  execve("./bar", ["./bar"], [/* 29 vars */]) = 0
2855  arch_prctl(ARCH_SET_FS, 0x499b88) = 0
2855  sched_getaffinity(0, 8192, [0])   = 32
2855  mmap(0xc000000000, 65536, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0xc000000000
2855  munmap(0xc000000000, 65536)       = 0
2855  mmap(NULL, 262144, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7facf3fe3000
2855  mmap(0xc420000000, 1048576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0xc420000000
2855  mmap(0xc41fff8000, 32768, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0xc41fff8000
2855  mmap(0xc000000000, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0xc000000000
2855  mmap(NULL, 65536, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7facf3fd3000
2855  mmap(NULL, 65536, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7facf3fc3000
2855  rt_sigprocmask(SIG_SETMASK, NULL, [], 8) = 0
2855  sigaltstack(NULL, {ss_sp=NULL, ss_flags=SS_DISABLE, ss_size=0}) = 0
2855  sigaltstack({ss_sp=0xc420002000, ss_flags=0, ss_size=32672}, NULL) = 0
2855  gettid()                          = 2855
2855  rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
2855  rt_sigaction(SIGHUP, NULL, {SIG_DFL, [], 0}, 8) = 0
2855  rt_sigaction(SIGHUP, {0x44d080, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x44d170}, NULL, 8) = 0
2855  rt_sigaction(SIGINT, NULL, {SIG_DFL, [], 0}, 8) = 0
2855  rt_sigaction(SIGINT, {0x44d080, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x44d170}, NULL, 8) = 0
2855  rt_sigaction(SIGQUIT, NULL, {SIG_DFL, [], 0}, 8) = 0
2855  rt_sigaction(SIGQUIT, {0x44d080, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x44d170}, NULL, 8) = 0
2855  rt_sigaction(SIGILL, NULL, {SIG_DFL, [], 0}, 8) = 0
2855  rt_sigaction(SIGILL, {0x44d080, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x44d170}, NULL, 8) = 0
2855  rt_sigaction(SIGTRAP, NULL, {SIG_DFL, [], 0}, 8) = 0
2855  rt_sigaction(SIGTRAP, {0x44d080, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x44d170}, NULL, 8) = 0
2855  rt_sigaction(SIGABRT, NULL, {SIG_DFL, [], 0}, 8) = 0
2855  rt_sigaction(SIGABRT, {0x44d080, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x44d170}, NULL, 8) = 0
2855  rt_sigaction(SIGBUS, NULL, {SIG_DFL, [], 0}, 8) = 0
2855  rt_sigaction(SIGBUS, {0x44d080, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x44d170}, NULL, 8) = 0
2855  rt_sigaction(SIGFPE, NULL, {SIG_DFL, [], 0}, 8) = 0
2855  rt_sigaction(SIGFPE, {0x44d080, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x44d170}, NULL, 8) = 0
2855  rt_sigaction(SIGUSR1, NULL, {SIG_DFL, [], 0}, 8) = 0
2855  rt_sigaction(SIGUSR1, {0x44d080, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x44d170}, NULL, 8) = 0
2855  rt_sigaction(SIGSEGV, NULL, {SIG_DFL, [], 0}, 8) = 0
2855  rt_sigaction(SIGSEGV, {0x44d080, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x44d170}, NULL, 8) = 0
2855  rt_sigaction(SIGUSR2, NULL, {SIG_DFL, [], 0}, 8) = 0
2855  rt_sigaction(SIGUSR2, {0x44d080, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x44d170}, NULL, 8) = 0
2855  rt_sigaction(SIGPIPE, NULL, {SIG_DFL, [], 0}, 8) = 0
2855  rt_sigaction(SIGPIPE, {0x44d080, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x44d170}, NULL, 8) = 0
2855  rt_sigaction(SIGALRM, NULL, {SIG_DFL, [], 0}, 8) = 0
2855  rt_sigaction(SIGALRM, {0x44d080, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x44d170}, NULL, 8) = 0
2855  rt_sigaction(SIGTERM, NULL, {SIG_DFL, [], 0}, 8) = 0
2855  rt_sigaction(SIGTERM, {0x44d080, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x44d170}, NULL, 8) = 0
2855  rt_sigaction(SIGSTKFLT, NULL, {SIG_DFL, [], 0}, 8) = 0
2855  rt_sigaction(SIGSTKFLT, {0x44d080, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x44d170}, NULL, 8) = 0
2855  rt_sigaction(SIGCHLD, NULL, {SIG_DFL, [], 0}, 8) = 0
2855  rt_sigaction(SIGCHLD, {0x44d080, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x44d170}, NULL, 8) = 0
2855  rt_sigaction(SIGURG, NULL, {SIG_DFL, [], 0}, 8) = 0
2855  rt_sigaction(SIGURG, {0x44d080, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x44d170}, NULL, 8) = 0
2855  rt_sigaction(SIGXCPU, NULL, {SIG_DFL, [], 0}, 8) = 0
2855  rt_sigaction(SIGXCPU, {0x44d080, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x44d170}, NULL, 8) = 0
2855  rt_sigaction(SIGXFSZ, NULL, {SIG_DFL, [], 0}, 8) = 0
2855  rt_sigaction(SIGXFSZ, {0x44d080, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x44d170}, NULL, 8) = 0
2855  rt_sigaction(SIGVTALRM, NULL, {SIG_DFL, [], 0}, 8) = 0
2855  rt_sigaction(SIGVTALRM, {0x44d080, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x44d170}, NULL, 8) = 0
2855  rt_sigaction(SIGPROF, NULL, {SIG_DFL, [], 0}, 8) = 0
2855  rt_sigaction(SIGPROF, {0x44d080, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x44d170}, NULL, 8) = 0
2855  rt_sigaction(SIGWINCH, NULL, {SIG_DFL, [], 0}, 8) = 0
2855  rt_sigaction(SIGWINCH, {0x44d080, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x44d170}, NULL, 8) = 0
2855  rt_sigaction(SIGIO, NULL, {SIG_DFL, [], 0}, 8) = 0
2855  rt_sigaction(SIGIO, {0x44d080, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x44d170}, NULL, 8) = 0
2855  rt_sigaction(SIGPWR, NULL, {SIG_DFL, [], 0}, 8) = 0
2855  rt_sigaction(SIGPWR, {0x44d080, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x44d170}, NULL, 8) = 0
2855  rt_sigaction(SIGSYS, NULL, {SIG_DFL, [], 0}, 8) = 0
2855  rt_sigaction(SIGSYS, {0x44d080, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x44d170}, NULL, 8) = 0
2855  rt_sigaction(SIGRTMIN, NULL, {SIG_DFL, [], 0}, 8) = 0
2855  rt_sigaction(SIGRT_1, NULL, {SIG_DFL, [], 0}, 8) = 0
2855  rt_sigaction(SIGRT_2, NULL, {SIG_DFL, [], 0}, 8) = 0
2855  rt_sigaction(SIGRT_2, {0x44d080, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x44d170}, NULL, 8) = 0
2855  rt_sigaction(SIGRT_3, NULL, {SIG_DFL, [], 0}, 8) = 0
2855  rt_sigaction(SIGRT_3, {0x44d080, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x44d170}, NULL, 8) = 0
2855  rt_sigaction(SIGRT_4, NULL, {SIG_DFL, [], 0}, 8) = 0
2855  rt_sigaction(SIGRT_4, {0x44d080, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x44d170}, NULL, 8) = 0
2855  rt_sigaction(SIGRT_5, NULL, {SIG_DFL, [], 0}, 8) = 0
2855  rt_sigaction(SIGRT_5, {0x44d080, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x44d170}, NULL, 8) = 0
2855  rt_sigaction(SIGRT_6, NULL, {SIG_DFL, [], 0}, 8) = 0
2855  rt_sigaction(SIGRT_6, {0x44d080, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x44d170}, NULL, 8) = 0
2855  rt_sigaction(SIGRT_7, NULL, {SIG_DFL, [], 0}, 8) = 0
2855  rt_sigaction(SIGRT_7, {0x44d080, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x44d170}, NULL, 8) = 0
2855  rt_sigaction(SIGRT_8, NULL, {SIG_DFL, [], 0}, 8) = 0
2855  rt_sigaction(SIGRT_8, {0x44d080, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x44d170}, NULL, 8) = 0
2855  rt_sigaction(SIGRT_9, NULL, {SIG_DFL, [], 0}, 8) = 0
2855  rt_sigaction(SIGRT_9, {0x44d080, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x44d170}, NULL, 8) = 0
2855  rt_sigaction(SIGRT_10, NULL, {SIG_DFL, [], 0}, 8) = 0
2855  rt_sigaction(SIGRT_10, {0x44d080, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x44d170}, NULL, 8) = 0
2855  rt_sigaction(SIGRT_11, NULL, {SIG_DFL, [], 0}, 8) = 0
2855  rt_sigaction(SIGRT_11, {0x44d080, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x44d170}, NULL, 8) = 0
2855  rt_sigaction(SIGRT_12, NULL, {SIG_DFL, [], 0}, 8) = 0
2855  rt_sigaction(SIGRT_12, {0x44d080, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x44d170}, NULL, 8) = 0
2855  rt_sigaction(SIGRT_13, NULL, {SIG_DFL, [], 0}, 8) = 0
2855  rt_sigaction(SIGRT_13, {0x44d080, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x44d170}, NULL, 8) = 0
2855  rt_sigaction(SIGRT_14, NULL, {SIG_DFL, [], 0}, 8) = 0
2855  rt_sigaction(SIGRT_14, {0x44d080, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x44d170}, NULL, 8) = 0
2855  rt_sigaction(SIGRT_15, NULL, {SIG_DFL, [], 0}, 8) = 0
2855  rt_sigaction(SIGRT_15, {0x44d080, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x44d170}, NULL, 8) = 0
2855  rt_sigaction(SIGRT_16, NULL, {SIG_DFL, [], 0}, 8) = 0
2855  rt_sigaction(SIGRT_16, {0x44d080, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x44d170}, NULL, 8) = 0
2855  rt_sigaction(SIGRT_17, NULL, {SIG_DFL, [], 0}, 8) = 0
2855  rt_sigaction(SIGRT_17, {0x44d080, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x44d170}, NULL, 8) = 0
2855  rt_sigaction(SIGRT_18, NULL, {SIG_DFL, [], 0}, 8) = 0
2855  rt_sigaction(SIGRT_18, {0x44d080, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x44d170}, NULL, 8) = 0
2855  rt_sigaction(SIGRT_19, NULL, {SIG_DFL, [], 0}, 8) = 0
2855  rt_sigaction(SIGRT_19, {0x44d080, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x44d170}, NULL, 8) = 0
2855  rt_sigaction(SIGRT_20, NULL, {SIG_DFL, [], 0}, 8) = 0
2855  rt_sigaction(SIGRT_20, {0x44d080, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x44d170}, NULL, 8) = 0
2855  rt_sigaction(SIGRT_21, NULL, {SIG_DFL, [], 0}, 8) = 0
2855  rt_sigaction(SIGRT_21, {0x44d080, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x44d170}, NULL, 8) = 0
2855  rt_sigaction(SIGRT_22, NULL, {SIG_DFL, [], 0}, 8) = 0
2855  rt_sigaction(SIGRT_22, {0x44d080, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x44d170}, NULL, 8) = 0
2855  rt_sigaction(SIGRT_23, NULL, {SIG_DFL, [], 0}, 8) = 0
2855  rt_sigaction(SIGRT_23, {0x44d080, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x44d170}, NULL, 8) = 0
2855  rt_sigaction(SIGRT_24, NULL, {SIG_DFL, [], 0}, 8) = 0
2855  rt_sigaction(SIGRT_24, {0x44d080, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x44d170}, NULL, 8) = 0
2855  rt_sigaction(SIGRT_25, NULL, {SIG_DFL, [], 0}, 8) = 0
2855  rt_sigaction(SIGRT_25, {0x44d080, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x44d170}, NULL, 8) = 0
2855  rt_sigaction(SIGRT_26, NULL, {SIG_DFL, [], 0}, 8) = 0
2855  rt_sigaction(SIGRT_26, {0x44d080, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x44d170}, NULL, 8) = 0
2855  rt_sigaction(SIGRT_27, NULL, {SIG_DFL, [], 0}, 8) = 0
2855  rt_sigaction(SIGRT_27, {0x44d080, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x44d170}, NULL, 8) = 0
2855  rt_sigaction(SIGRT_28, NULL, {SIG_DFL, [], 0}, 8) = 0
2855  rt_sigaction(SIGRT_28, {0x44d080, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x44d170}, NULL, 8) = 0
2855  rt_sigaction(SIGRT_29, NULL, {SIG_DFL, [], 0}, 8) = 0
2855  rt_sigaction(SIGRT_29, {0x44d080, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x44d170}, NULL, 8) = 0
2855  rt_sigaction(SIGRT_30, NULL, {SIG_DFL, [], 0}, 8) = 0
2855  rt_sigaction(SIGRT_30, {0x44d080, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x44d170}, NULL, 8) = 0
2855  rt_sigaction(SIGRT_31, NULL, {SIG_DFL, [], 0}, 8) = 0
2855  rt_sigaction(SIGRT_31, {0x44d080, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x44d170}, NULL, 8) = 0
2855  rt_sigaction(SIGRT_32, NULL, {SIG_DFL, [], 0}, 8) = 0
2855  rt_sigaction(SIGRT_32, {0x44d080, ~[], SA_RESTORER|SA_STACK|SA_RESTART|SA_SIGINFO, 0x44d170}, NULL, 8) = 0
2855  rt_sigprocmask(SIG_SETMASK, ~[], [], 8) = 0
2855  clone(child_stack=0xc420037fc0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD) = 2856
2855  rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
2855  rt_sigprocmask(SIG_SETMASK, ~[], [], 8) = 0
2855  clone(child_stack=0xc420033fc0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD) = 2857
2855  rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
2855  futex(0x499c30, FUTEX_WAIT, 0, NULL <unfinished ...>
2857  gettid()                          = 2857
2857  arch_prctl(ARCH_SET_FS, 0xc420028468) = 0
2857  sigaltstack(NULL, {ss_sp=NULL, ss_flags=SS_DISABLE, ss_size=0}) = 0
2857  sigaltstack({ss_sp=0xc420044000, ss_flags=0, ss_size=32672}, NULL) = 0
2857  gettid()                          = 2857
2857  rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
2857  futex(0x499c30, FUTEX_WAKE, 1 <unfinished ...>
2855  <... futex resumed> )             = 0
2857  <... futex resumed> )             = 1
2855  --- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0} ---
2855  rt_sigreturn({mask=[]})           = 0
2855  --- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0} ---
2855  rt_sigreturn({mask=[]})           = 0
2855  mmap(NULL, 262144, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7facf3f83000
2855  --- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0} ---
2855  rt_sigreturn({mask=[]})           = 0
2855  --- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0} ---
2855  rt_sigreturn({mask=[]})           = 0
2855  --- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0} ---
2855  rt_sigreturn({mask=[]})           = 0
2855  --- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0} ---
2855  rt_sigreturn({mask=[]})           = 0
2855  --- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0} ---
2855  rt_sigreturn({mask=[]})           = 0
2855  --- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0} ---
2855  rt_sigreturn({mask=[]})           = 0
2855  --- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0} ---
2855  rt_sigreturn({mask=[]})           = 0
2855  --- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0} ---
2855  rt_sigreturn({mask=[]})           = 0
2855  --- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0} ---
2855  rt_sigreturn({mask=[]})           = 0
2855  --- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0} ---
2855  rt_sigreturn({mask=[]})           = 0
2855  --- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0} ---
2855  rt_sigreturn({mask=[]})           = 0
2855  --- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0} ---
2855  rt_sigreturn({mask=[]})           = 0
2855  --- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0} ---
2855  rt_sigreturn({mask=[]})           = 0
2855  --- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0} ---
2855  rt_sigreturn({mask=[]})           = 0
2855  --- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0} ---
2855  rt_sigreturn({mask=[]})           = 0
2855  --- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0} ---
2855  rt_sigreturn({mask=[]})           = 0
2855  --- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0} ---
2855  rt_sigreturn({mask=[]})           = 0
2855  --- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0} ---
2855  rt_sigreturn({mask=[]})           = 0
2855  --- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0} ---
2855  rt_sigreturn({mask=[]})           = 0
2855  --- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0} ---
2855  rt_sigreturn({mask=[]})           = 0
2855  --- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0} ---
2855  rt_sigreturn({mask=[]})           = 0
2855  --- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0} ---
2855  rt_sigreturn({mask=[]})           = 0
2855  --- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0} ---
2855  rt_sigreturn({mask=[]})           = 0
2855  --- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0} ---
2855  rt_sigreturn({mask=[]})           = 0
2855  --- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0} ---
2855  rt_sigreturn({mask=[]})           = 0
2855  --- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0} ---
2855  --- SIGINT {si_signo=SIGINT, si_code=SI_KERNEL} ---
2855  rt_sigaction(SIGINT, {SIG_DFL, ~[], SA_RESTORER|SA_STACK|SA_SIGINFO, 0x44d170}, NULL, 8) = 0
2855  rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
2855  gettid()                          = 2855
2855  tkill(2855, SIGINT)               = 0
2855  --- SIGINT {si_signo=SIGINT, si_code=SI_TKILL, si_pid=2855, si_uid=1000} ---
2857  +++ killed by SIGINT +++
2856  +++ killed by SIGINT +++
2855  +++ killed by SIGINT +++
~~~

**Comment by zhexuany** [comment]
Given the strace report, it seems there is something prevent `rt_sigreturn` cleanup stack frame.

**Comment by ALTree** [comment]
This should be fixed in go1.8 (see [CL 30358](https://go-review.googlesource.com/#/c/30358/)).

**Comment by ianlancetaylor** [comment]
Yes, this fails (hangs) in 1.7 but succeeds (crashes) in 1.8.  Closing.

**Comment by zhexuany** [comment]
@ianlancetaylor  Just checked with latest master branch. The error persists.

**Comment by zhexuany** [comment]
@ALTree Could you please tell me whether my build of go 1.8 is not correct? Otherwise, this bugs still persists.

**Comment by davecheney** [comment]
Please double check that you have not set `GOROOT`. If `GOROOT` is set and points to the wrong version of Go this could explain why you are not seeing the fix.

**Comment by zhexuany** [comment]
Ah! it works. Thx!

**Comment by davecheney** [comment]
@zhexuany protip: _never_ _ever_ _never_ set `GOROOT`, it only causes confusing problems.
