### ISSUE TITLE
cmd/gofmt: does it have to specify tab width = 8 ?

### ISSUE THREAD

**Issue by bits01** [golang/go#19618]
https://tip.golang.org/cmd/gofmt/

> Gofmt formats Go programs. It uses tabs **(width = 8)** for indentation and blanks for alignment.

Does it need to specify tab width = 8? If not, could you please remove it?

**Comment by mvdan** [comment]
Perhaps this has something to do with padding of comments, assignments and key-value pairs, since those are done with spaces.

**Comment by mvdan** [comment]
cc @griesemer

**Comment by griesemer** [comment]
@bits01 Tabs are only used for indentation. Their width determines how many blanks are required for alignment of comments and other things (after indentation). Since the tab width is fixed, it makes sense to mention it because for an editor to display source properly aligned (as formatted by gofmt), that editor needs to know that the tab with needs to be set to 8. Furthermore, some editors/users have tabs replaced with blanks, and  that number of blanks should match tab width.

Originally, tab width could be changed (it was a flag rather than a constant). However, in practice that only caused problems because different people would gofmt source differently. Also, in practice, tab with is unchanged for most people and set to 8. One of the benefits of gofmt is not just visual; by reducing variability of formatting it reduces merge conflicts and other spurious differences when reviewing code.

I'm going to close this. Feel free to re-open if you feel you have a strong reason as to why it shouldn't be mentioned. Thanks.

**Comment by bits01** [comment]
Thanks for your reply. I'm still not sure I understand. I thought the reason for using tabs was to let people decide in their editor how big the indent is in terms of spaces, e.g. users could set their editor tab width to 2, 4, 8 or whatever they like. It also seems that editors tend to default tab width to 4 not 8.

If the code formatted by gofmt "looks good" only when tab width = 8, then shouldn't the tool simply use 8 spaces instead of tabs and not mix tabs and spaces?

I am not trying to open the tabs vs spaces can of worms, just trying to understand the rationale behind the decision to document the tab width.

Thank you.

**Comment by bradfitz** [comment]
@griesemer, I think we should keep this open to fix the wording, as this keeps coming up.

Putting "(width = 8)" after the word "tabs" is what's confusing people. 

Instead of:

> Gofmt formats Go programs. It uses tabs (width = 8) for indentation and blanks for alignment.

We could write something like:

> Gofmt formats Go programs. It uses tabs for indentation and spaces for alignment of comments, assuming a tab width of 8.

(Or more or less verbose, at your choosing.)

**Comment by mvdan** [comment]
I think @bradfitz's suggestion makes it much clearer without being verbose. I assume we don't want to get into historical details there.

**Comment by bits01** [comment]
@mvdan we do not and the purpose is not to try to change what gofmt does in any way. As @bradfitz said, the statement should sound more like a suggestion, e.g.
> For best readability, suggested editor tab width of 8.

(something to that effect)
