### ISSUE TITLE
x/tools/cmd/go-contrib-init: tool does not recognize .googlesource.com config

### ISSUE THREAD

**Issue by dlsniper** [golang/go#21019]
### What version of Go are you using (`go version`)?
Go 1.9beta2

### What operating system and processor architecture are you using (`go env`)?
Windows 10

### What did you do?
```
go get golang.org/x/tools/cmd/go-contrib-init

go-contrib-init
```

### What did you expect to see?
```
All good. Happy hacking!
Remember to squash your revised commits and preserve the magic Change-Id lines.
Next steps: https://golang.org/doc/contribute.html#commit_changes
```

### What did you see instead?
```
Your .gitcookies file isn't configured.
Next steps:
  * Submit a CLA (https://golang.org/doc/contribute.html#cla) if not done
  * Go to https://go.googlesource.com/ and click "Generate Password" at the top,
    then follow instructions.
  * Run go-contrib-init again.
```

This seems to be caused by the fact that I already have a line in the configuration containing this:

```
.googlesource.com       TRUE    /       TRUE    <hidden>      o       git-florinpatan.gmail.com=<hidden>
```

**Comment by bradfitz** [comment]
Wasn't this already fixed by https://go-review.googlesource.com/c/48230/ ?

Are you running an old version?

**Comment by dlsniper** [comment]
I literally just go getted the tool for the workshop so no, it's not fixed yet I guess. sorry.

**Comment by bradfitz** [comment]
@dlsniper, but you probably had an old x/tools on disk already from a different x/tool package.

Use `go get -u` or tell me what git revision of x/tools you have currently.

**Comment by kevinburke** [comment]
Investigating...

**Comment by dlsniper** [comment]
I've fixed with ` go get -u `, thank you.
