### ISSUE TITLE
Windows: MSI Upgrade should default to previous install folder, not insist on C:\Go\

### ISSUE THREAD

**Issue by lkarlslund** [golang/go#21609]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

1.9 release

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

Windows

### What did you do?

Had Go 1.9rc2 installed in C:\Program Files\Go\
Wizard asked if I wanted to uninstall old during upgrade, I chose YES
Wizard asks where I want to install new version, defaults to C:\Go\

### What did you expect to see?

I expected it to suggest installation in the previously selected folder, as this is an upgrade, and everything in environment is set for that path.

### What did you see instead?

It insists on suggesting C:\Go\ which fills up my root folder with more directories. I don't get it why you don't use Program Files as everything else on Windows. This is not Linux (and you would never suggest to install in /go/ on a Linux system anyway)

**Comment by ianlancetaylor** [comment]
CC @broady

**Comment by as** [comment]
The utility will have to remember where the previous installation occured. How would it do this?

**Comment by lkarlslund** [comment]
It could write the install path to HKLM/Software/Golang/InstallPath (or whatever you are using now) when installing. Next install reads it, and suggests that. If key is missing, it just uses default folder like now.
________________________________
Fra: as <notifications@github.com>
sendt: 11. sep. 2017 10.42 PM
til: golang/go
Cc: Lars Karlslund; Author
Emne: Re: [golang/go] install: Windows: MSI Upgrade should default to previous install folder, not insist on C:\Go\ (#21609)


The utility will have to remember where the previous installation occured. How would it do this?

-

**Comment by as** [comment]
That may be a good option. It seems the installer already places a gift in the registry:

`reg query HKCU\software\goprogramminglanguage /v installLocation`

```
HKEY_CURRENT_USER\software\goprogramminglanguage
    installLocation    REG_SZ    C:\Go\
```

Someone with MSI expertise can take it from here.

**Comment by as** [comment]
Just for the record, I really like `C:\go`, especially since you can shorten it to `\go`. Please don't change the default. 

Windows has a `Program Files (x86)`, a `ProgramData`, a `System32` and a `SysWow64`. There is a _32-bit_  `Notepad.exe` in the `SysWow64` folder and a _64-bit_ notepad in the `System32` folder. The simplicity of `C:\go` is deeply appreciated on this system.

**Comment by iwdgo** [comment]
Default location is now `%ProgramFiles%\Go`

![image](https://user-images.githubusercontent.com/19574010/126320069-17282241-5284-44cb-9d18-c9cb561b7dfc.png)

This seems incidentally solved by #18680.

**Comment by tamasd** [comment]
This is still a problem for me. I have Go installed under `S:\Go`, but every time I update, the installer wants to install it under `C:\Program Files\Go`. I checked the registry, and the `installLocation` correctly points to `S:\Go`.
