### ISSUE TITLE
Error in godoc -html

### ISSUE THREAD

**Issue by henryas** [golang/go#21740]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
Go 1.9 

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
Windows 10 amd64

### What did you do?
run "godoc -html :8000" and open the browser to localhost:8000.

### What did you expect to see?
The usual welcome page.

### What did you see instead?
There is an error message displayed on the welcome page 
_"template: main:6:10: executing "main" at <$.GoogleCN>: can't evaluate field GoogleCN in type godoc.Page"_
and the welcome page has no content.

**Comment by henryas** [comment]
Nevermind. It is fixed by updating godoc.

**Comment by mh-cbon** [comment]
fyi

```
$ godoc -http=":6060"
2018/04/02 20:13:51 executing template doc/root.html: template: main:6:10: executing "main" at <$.GoogleCN>: can't evaluate field GoogleCN in type godoc.Page
2018/04/02 20:13:53 executing template doc/root.html: template: main:6:10: executing "main" at <$.GoogleCN>: can't evaluate field GoogleCN in type godoc.Page
^C
[mh-cbon@pc4 src] $ go version
go version go1.10 linux/amd64
```

**Comment by LucaPaterlini** [comment]
hello, still having the same issue on go 1.11 on a 64 bi linux lubuntu 16.04

**Comment by agnivade** [comment]
This issue is closed. If you are still seeing issues, please open a new issue instead. Thanks.
