### ISSUE TITLE
doc/code.html: update description of install command

### ISSUE THREAD

**Issue by toni-rmc** [golang/go#24506]
### What version of Go are you using (go version)?
`go version go1.10 windows/amd64`

### Does this issue reproduce with the latest release?
1.10 is the latest at this moment

### What operating system and processor architecture are you using (go env)?
GOARCH=amd64
GOOS=windows

### What did you do?
I have small test program with two small dummy libraries.

Go program in the `src` has path `github.com/user/hello`

    package main

    import (
        "fmt"
 
        // Libraries bellow are not automatically generated in pkg
        "github.com/user/stringutil"
        "github.com/user/tttt"
    )

    func main() {
        fmt.Printf(stringutil.Reverse("\nHello, world.\n"))
        fmt.Println(add(85,tttt.Tttt(9)))
    }

`add()` function is in separate file, also in `hello` directory:

    package main

    func add(x int, y int) int {
	    return x + y
    }

When I don't have the above libraries compiled and just use go install `hello` program is installed and works but the `pkg` directory is not created and no `stringutil.a` and `tttt.a`.

If I want to have libraries generated I have to use `go install` on every library, in which case `pkg` is generated and libraries in it.

this is not behaviour according to this documentation:

> Whenever the go tool installs a package or binary, it also installs whatever dependencies it has. So when you install the hello program
$ go install github.com/user/hello
the stringutil package will be installed as well, automatically.

Note that I have just installed the latest version (1.10) and just start using it as is writing only one dummy program and two dummy libraries one of which is copied from Go documentation.

### What did you expect to see?
Dependencies installed automatically in the `pkg`

### What did you see instead?
No `pkg` and no installed dependencies

**Comment by AlexRouSg** [comment]
The behavior has since been changed so that to install the dependencies you need to pass the `-i` flag.
https://golang.org/cmd/go/#hdr-Compile_and_install_packages_and_dependencies

> The -i flag installs the dependencies of the named packages as well.

Do you have a link to where you got the documentation?

**Comment by toni-rmc** [comment]
Got it from here
[https://tour.golang.org/concurrency/11](https://tour.golang.org/concurrency/11)

Link to the documentation is on this page in the

> To learn how to organize and work with Go code, watch this screencast or read How to Write Go Code. 

section.

"How to Write Go Code" is the link to it.

**Comment by toni-rmc** [comment]
With the `-i` flag works as it should.

**Comment by jdparkinson93** [comment]
Fixed in [+105655](https://go-review.googlesource.com/#/c/go/+/105655) @bcmills

**Comment by toni-rmc** [comment]
I'm still seeing `install` without `-i` switch in the web documentation linked above.

**Comment by AlexRouSg** [comment]
@toni-rmc 

Fix has not been approved and merged yet
