### ISSUE TITLE
gccgo: runtime address space conflict on AIX

### ISSUE THREAD

**Issue by amandeepgautam** [golang/go#24994]
### What version of Go are you using (`go version`)?
go version go1.9 gccgo (GCC) 8.0.0 20171205 (experimental) aix/ppc

### Does this issue reproduce with the latest release?
Not certain of that.

### What operating system and processor architecture are you using (`go env`)?
OS : AIX 7.2, ppc8

-bash-4.4$ go env
GOARCH="ppc"
GOBIN=""
GOEXE=""
GOHOSTARCH="ppc"
GOHOSTOS="aix"
GOOS="aix"
GOPATH="/go:/home/amandeep/workspace/main/.go:/home/amandeep/workspace/main/build/.go_no_cmake:/home/amandeep/go:/home/amandeep/workspace/main/build/.go"
GORACE=""
GOROOT="/opt/freeware"
GOTOOLDIR="/opt/freeware/libexec/gcc/powerpc-ibm-aix7.2.0.0/8.0.0"
GCCGO="/opt/freeware/bin/gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build346587613=/tmp/go-build -gno-record-gcc-switches -funwind-tables"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"

Additional flags:
GOARCH=ppc64 CGO_LDFLAGS='-maix64 -Wl,-bbigtoc'

### What did you do?
Compiled and ran the programs with following flags:

### What did you expect to see?
After running for a few minutes or so, it crashed with following error:

runtime: address space conflict: map(0xa00000100063000) = 0xa00000104463000
fatal error: runtime: address space conflict

runtime stack:
runtime_mstart
        ../../../../gcc-8.0.0/libgo/runtime/proc.c:524

goroutine 45554 [running]:
cohesity_util_storage_proxy.readFileData.pN40_cohesity_util_storage_proxy.StorageProxy
        /home/akshay/workspace/main/.go/src/cohesity/util/storage/proxy/storage_proxy.go:237
cohesity_util_storage_proxy.FetchFileData.pN40_cohesity_util_storage_proxy.StorageProxy
        /home/akshay/workspace/main/.go/src/cohesity/util/storage/proxy/storage_proxy.go:457
util_storage_proxy_stub_grpc_service_pb._GRpcService_FetchFileData_Handler
        /home/akshay/workspace/main/build/.go_no_cmake/src/util/storage/proxy/stub/grpc_service.pb/grpc_service.pb.go:199
google_golang_org_grpc.processUnaryRPC.pN29_google_golang_org_grpc.Server
        /go/src/google.golang.org/grpc/server.go:920
google_golang_org_grpc.handleStream.pN29_google_golang_org_grpc.Server
        /go/src/google.golang.org/grpc/server.go:1142
google_golang_org_grpc._nested82
        /go/src/google.golang.org/grpc/server.go:637
created by google_golang_org_grpc._nested81
        /go/src/google.golang.org/grpc/server.go:635 +316

goroutine 1 [IO wait, 1 minutes]:
internal_poll.runtime_pollWait
        ../../../../gcc-8.0.0/libgo/go/runtime/netpoll.go:176
internal_poll.wait.pN22_internal_poll.pollDesc
        ../../../../gcc-8.0.0/libgo/go/internal/poll/fd_poll_runtime.go:85
internal_poll.waitRead.pN22_internal_poll.pollDesc
        ../../../../gcc-8.0.0/libgo/go/internal/poll/fd_poll_runtime.go:90
internal_poll.Accept.pN16_internal_poll.FD
        ../../../../gcc-8.0.0/libgo/go/internal/poll/fd_unix.go:334
net.accept.pN9_net.netFD 
        ../../../../gcc-8.0.0/libgo/go/net/fd_unix.go:238
net.accept.pN15_net.TCPListener

**Comment by agnivade** [comment]
I don't think we support AIX. Can you try running your code on a linux machine ?

**Comment by amandeepgautam** [comment]
@agnivade I think it is an ongoing effort: https://github.com/golang/go/issues/19200
Will those bugs not be tracked here?

**Comment by agnivade** [comment]
Ah ok, so it is not supported.

> Will those bugs not be tracked here?

 It is not a bug since AIX is not supported yet. If you still see the issue once the port is complete, then we can track issues for it.

Closing as this is not a bug.

**Comment by ianlancetaylor** [comment]
@agnivade This issue was opened against gccgo.  The AIX port of gccgo is largely complete.  I don't think we need to close these issues are not supported.

**Comment by ianlancetaylor** [comment]
That said, this bug was likely fixed by https://golang.org/cl/97357 or https://golang.org/cl/99117.  @amandeepgautam Can you try a current version of gccgo?

**Comment by agnivade** [comment]
I see. I wasn't sure whether we track bugs for partially complete ports. Since the issue #19200 was not resolved, I concluded that it wasn't complete. Thanks for following up.

**Comment by amandeepgautam** [comment]
@ianlancetaylor I have already set it up and will update if I still see these errors.

**Comment by amandeepgautam** [comment]
Closing the issue as we cannot reproduce it.
