### ISSUE TITLE
os: RemoveAll blocks indefinitely on large directories without permissions

### ISSUE THREAD

**Issue by efritz** [golang/go#29921]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11.2 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes - the behavior can still be traced in the source of the master branch.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/efritz/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/efritz/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/lib/go"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build861899082=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Create a directory `parent` with _more than_ 1024 files in it owned by the non-current user. This behavior originally presented itself with a directory mounted in Docker that created 1050 root-owned files locale files. The following script creates a directory parent with such contents.

```bash
#!/bin/bash -ex

mkdir -p parent

for i in {0..1025}; do
    touch "parent/$i"
done

chown root:root -R parent/*
```

Then, run the following go program in the same directory.

```go
package main

import (
	"fmt"
	"os"
)

func main() {
	if err := os.RemoveAll("parent"); err != nil {
		fmt.Printf("> %s\n", err.Error())
		os.Exit(1)
	}

	fmt.Printf("Ok\n")
}
```

### What did you expect to see?

A program terminating with a permissions error.

### What did you see instead?

A non-terminating program. Inspecting the program with strace shows the same set of unlink attempts and permissions errors. This is due to the following loop, which attempts to delete the contents of the `parent` directory in batches of 1024.

https://github.com/golang/go/blob/ba1de79a3a542b5bf25c4cc3be1c91d1ede47c55/src/os/removeall_at.go#L89

This logic is subtly wrong, as if all 1024 files cannot be deleted, recurseErr will be set (and not read within the loop) and the subsequent Readdir call will return the same set of filenames. This logic will also be problematic for _any_ directory containing at least 1024 files which cannot be deleted.

**Comment by mvdan** [comment]
Seems closely related to #20841, fixed in Go 1.11.

**Comment by efritz** [comment]
I just built the 1.11.5 from source and, although the RemoveAll code has changed, the same behavior is still present. Is there a target branch you would like me to confirm this behavior for?

**Comment by efritz** [comment]
```
```

**Comment by bcmills** [comment]
CC @ianlancetaylor

**Comment by antong** [comment]
> Seems closely related to #20841, fixed in Go 1.11.

I'd bet that fix is what caused this issue :-)

**Comment by Gnouc** [comment]
@efritz 

```
chown root:root -R parent/*
```

must be:

```
chown root:root -R parent
```

to reproduce the issue, otherwise you can still remove the parent.

**Comment by cxfans** [comment]
I have the same problem.
