### ISSUE TITLE
x/exp: errors/fmt.TestPanics broken

### ISSUE THREAD

**Issue by eliasnaur** [golang/go#30622]
From tip: https://build.golang.org/log/5dd20c71b5e4d2d29ae2230ab47058abb52d88e5

```
--- FAIL: TestPanics (0.00s)
    fmt_test.go:1684: 1: "%s": got "%!s(PANIC=String method: unexpected EOF)" expected "%!s(PANIC=unexpected EOF)"
    fmt_test.go:1684: 2: "%s": got "%!s(PANIC=String method: 3)" expected "%!s(PANIC=3)"
    fmt_test.go:1684: 4: "%#v": got "%!v(PANIC=GoString method: unexpected EOF)" expected "%!v(PANIC=unexpected EOF)"
    fmt_test.go:1684: 5: "%#v": got "%!v(PANIC=GoString method: 3)" expected "%!v(PANIC=3)"
    fmt_test.go:1684: 6: "%#v": got "[]interface {}{%!v(PANIC=GoString method: 3), %!v(PANIC=GoString method: 3)}" expected "[]interface {}{%!v(PANIC=3), %!v(PANIC=3)}"
    fmt_test.go:1684: 8: "%s": got "%!s(PANIC=Format method: unexpected EOF)" expected "%!s(PANIC=unexpected EOF)"
    fmt_test.go:1684: 9: "%s": got "%!s(PANIC=Format method: 3)" expected "%!s(PANIC=3)"
FAIL
FAIL	golang.org/x/exp/errors/fmt	0.109s
```

**Comment by eliasnaur** [comment]
@mpvl

**Comment by bcmills** [comment]
This is failure is consistent on the `openbsd-arm` builder:
https://build.golang.org/log/e345ae0134a58d52d63d97fba243afea814f90a5
https://build.golang.org/log/ab72bb8d8ca9390349ec155239f79df407f83d67
https://build.golang.org/log/e8dc2b6221e15f0facf18685ea458ee8034319f8

**Comment by dmitshur** [comment]
Issue #32528 has been resolved, and so the tests for the `golang.org/x/exp/errors` module will be executed when trybots run. That means this test failure will affect all trybot runs in x/exp.

**Comment by dmitshur** [comment]
I'm not familiar enough with this code to know how the test should be fixed. I can send a CL to skip this test on builders with a reference to this issue. It'd be good to have a fix sooner so that trybots can succeed on x/exp.

**Comment by jba** [comment]
I think we can remove `exp/errors`; it's been obsoleted by `xerrors` and the 1.13 stdlib `errors`. @mpvl @neild can you confirm?

**Comment by bcmills** [comment]
This is still showing up on the `android` builders, presumably because the `GO_BUILDER_NAME` environment variable is not being propagated to the subprocess.

Regardless, we shouldn't _only_ hide the failure from the builders: end users may reasonably try to run `go test golang.org/x/exp/...` on their own machines and expect it to pass.

**Comment by rsc** [comment]
Fixing the tests is trivial. Why not do that? Sent a CL.
