### ISSUE TITLE
os/exec: "fork/exec ... cannot allocate memory" on linux,!amd64

### ISSUE THREAD

**Issue by 4a6f656c** [golang/go#31936]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +5286b2a Thu May 9 14:58:03 2019 +0000 linux/s390x
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

linux/s390x

### What did you do?

On a linux/s390x LPAR with 12GB of RAM:

```go
package main

import (
        "log"
        "os/exec"
)

func main() {
        c := 8 * 1024 * 1024 * 1024
        a := make([]byte, c, c)
        for i := range a {
                a[i] = byte(i % 255)
        }

        log.Print(exec.Command("sleep", "1").Run())
}
```

```shell
$ go build -o fork fork.go
```

### What did you expect to see?

```shell
$ ./fork
2019/05/07 04:21:46 <nil>
```

### What did you see instead?

```shell
$ ./fork
2019/05/07 03:59:54 fork/exec /bin/sleep: cannot allocate memory
```

This causes a production impact since various Go programs cannot fork/exec (including the Go compiler at times).

This is reproducable under Linux on most architectures aside from linux/amd64, where the problem has been addressed via issue #5838. The memory consumption will need to be altered depending on the available host memory.

**Comment by acls** [comment]
It would be nice to also have this fixed in linux/arm. There was a fix in https://go-review.googlesource.com/c/go/+/175697/5 but was removed.

**Comment by albertoangelici** [comment]
Still have the problem with **linux/mipsle** (compiled with go 1.13.4 windows/amd64)

**Comment by csystem-it** [comment]
this issue is impacting us pretty hard even on go 1.15 on **linux/mipsle**.
Is there any workaround? Adding swap space (with zram) helps a bit, but it still happens.

**Comment by 4a6f656c** [comment]
@csystem-it - there is no real work around for this issue, short of either fixing the the syscall package, or rearchitecting your application. Feel free to try https://go-review.googlesource.com/c/go/+/295849 (the mipsle portion of that should be easy to backport to Go 1.15).

**Comment by csystem-it** [comment]
I tried to backport and it seems to be working.
Any idea when we can see this in a stable release?
I see that it is merged, but I'm not familiar with the Go development cycle,  so I don't know if it will make it for a 1.16.x release, 1.17 or if it has not been decied.

**Comment by ianlancetaylor** [comment]
@csystem-it The change in https://golang.org/cl/295849 will be in the upcoming Go 1.17 release.  It was not in the Go 1.16 release.

**Comment by ianlancetaylor** [comment]
@csystem-it The change in https://golang.org/cl/295849 will be in the upcoming Go 1.17 release.  It was not in the Go 1.16 release.
