### ISSUE TITLE
cmd/go: go adds unnecessary module dependency

### ISSUE THREAD

**Issue by alanconway** [golang/go#34290]
### What version of Go are you using (`go version`)?

go version go1.12.9 linux/amd64

### Does this issue reproduce with the latest release?

Don't know, using latest packaged release on Fedora.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/aconway/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/aconway/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/lib/golang"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/aconway/gomod/src/github.com/cloudevents/sdk-go/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build160743641=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

<pre>
$ git clone https://github.com/cloudevents/sdk-go
$ cd sdk-go
$ go list -m
github.com/cloudevents/sdk-go
$ go mod tidy
$ grep gogo go.mod # Note output is empty
$ go list -m
github.com/cloudevents/sdk-go
$ grep gogo go.mod # Just `go list -m` causes this dep to appear.
	github.com/gogo/protobuf v1.2.0 // indirect
$ go mod why github.com/gogo/protobuf
# github.com/gogo/protobuf
(main module does not need package github.com/gogo/protobuf)
$ go mod tidy
$ grep gogo go.mod # gogo is gone again!
$ 
</pre>

### What did you expect to see?

No incorrect dependencies in go.mod. 
Agreement between go tools on what dependencies are required.
After a successful `go build; go mod tidy`, subsequent calls of `go build` or 
`go mod tidy` with no code changes should not change go.mod.

### What did you see instead?

Calling `go list -m` or any go comand (go build etc.) adds a line to go.mod

    	github.com/gogo/protobuf v1.2.0 // indirect

Calling `go tidy` removes that line. 

I suspect this may be some environmental factor on my machine as I haven't heard anyone else with this problem but I don't know what it might be.

**Comment by zikaeroh** [comment]
Given you're still on 1.12, this is probably #31248, fixed in 1.13.

**Comment by thepudds** [comment]
@alanconway As @zikaeroh mentioned, there were fixes in this area for Go 1.13. If you run through these steps with Go 1.13, does the problem still happen?

**Comment by alanconway** [comment]
Still happens on 1.13, I uninstalled the 1.12 installation to ensure I wasn't picking up any old libs.

My symptoms are different from  #31248 - `go tidy` is behaving correctly, it is removing a package that is not needed. `go why` agrees that it is not needed. However `go list`, `go build` and other commands add it back. I built github.com/cloudevents/sdk-go with go dep in GOPATH mode to confirm that github.com/gogo/protobuf is really not required to build.

**Comment by douglarek** [comment]
I got the same issue as @alanconway

**Comment by bcmills** [comment]
@alanconway, I'm unable to reproduce the behavior you observed using `go1.13.1`. Can you provide a specific commit of the repository that I can check out to reproduce the behavior?

This may be a duplicate of #34086, but without a current reproducer it's hard to be sure.

**Comment by alanconway** [comment]
@bcmills 1.13.1 works for me, looks like it's fixed :) Thanks.

**Comment by douglarek** [comment]
It is still unresolved when using Go 1.13.1.

**Comment by douglarek** [comment]
Some supplement for this: it only work when you use go 1.13.1 and also use 1.13.1 in go.mod file.

**Comment by bcmills** [comment]
> it only works when you use go 1.13.1 and also use 1.13.1 in go.mod file.

The `go.mod` file specifies only the language version: `go 1.13.1` in the `go.mod` file should not be accepted in the first place. (`go 1.13`, however, should.)

> And another question: when using a newer go version, should go.mod's go version be updated automatically

No. Newer versions of the toolchain can compile older versions of the language spec, so in general it should not be necessary to update the `go` directive unless you need to enable newer language features.

**Comment by bcmills** [comment]
@douglarek, the problem originally reported here does not seem to reproduce, so I'm going to close this issue.

If you're seeing something you believe to be a bug, please file a new issue with concrete steps to reproduce it — ideally, a repo that we can check out at a specific commit to demonstrate the problem.

**Comment by alanconway** [comment]
Re-opened till other comments are addressed. 

I see that 1.13.1 go mode adds a "go 1.13.1" line go go.mod  if there's no existing go version, but if I add an explicit version like "go 1.11", then go mod leaves it alone, so it seems like upgrading to go.mod requires an explicit go version to stop the defaulting if you care about older versions.

**Comment by bcmills** [comment]
Please keep issue threads on-topic: this discussion doesn't seem to have anything to do with the originally-reported issue.

Clarifying documentation about which `go` version to set is #30791.
