### ISSUE TITLE
cmd/go: bad error when GOROOT not set correctly

### ISSUE THREAD

**Issue by rsc** [golang/go#34769]
Bad GOROOT is not diagnosed particularly well:

```
$ go build
$ GOROOT=/nonexist go build
go: cannot find GOROOT directory: /nonexist
$ GOROOT=/ go build
build rsc.io/kb/pw: cannot load bytes: malformed module path "bytes": missing dot in first path element
$
```
The first error is great. The second error is not. It should diagnose the bad GOROOT setting not complain about malformed module paths. 

FWIW GOPATH mode is bad too but differently:

```
$ GOROOT=/ GO111MODULE=off go build
pw.go:16:2: cannot find package "bytes" in any of:
	/src/bytes (from $GOROOT)
	/Users/rsc/src/bytes (from $GOPATH)
../../../golang.org/x/crypto/blake2b/register.go:10:2: cannot find package "crypto" in any of:
	/src/crypto (from $GOROOT)
	/Users/rsc/src/crypto (from $GOPATH)
pw.go:17:2: cannot find package "crypto/rand" in any of:
	/src/crypto/rand (from $GOROOT)
	/Users/rsc/src/crypto/rand (from $GOPATH)
(many lines cut)
```

**Comment by a8m** [comment]
This issue is somehow related to [CL] that changes the second error.

The `missing dot in first path element` error returns in other cases, like this [one](https://github.com/a8m/go-issue-34769).

[CL]: https://go-review.googlesource.com/c/go/+/203118

**Comment by aayushrathore** [comment]
for me the issue was resolved after chaning the GOROOT environment variable from "/usr/loca/go/bin" to "/usr/local/go"

OS : Linux centos

**Comment by nzoueidi** [comment]
For me, even changing the GOROOT variable to /usr/local/go still showing me the same output when doing go build.

**Comment by piotrkira** [comment]
For me `go list` in root path of project resolved issuse.
