### ISSUE TITLE
x/tools/gopls: creating a new file in a package causes import errors to show and disappear as the new file is edited

### ISSUE THREAD

**Issue by zikaeroh** [golang/go#36960]
Please answer these questions before submitting your issue. Thanks!

#### What did you do?

In my project (https://github.com/hortbot/hortbot), added a new file in the `bot` package, and typed `package bot`, then started to work in it.

#### What did you expect to see?

No errors when I'm in a good state.

#### What did you see instead?

Every time I edit the file, I can see the other files in the package flash red and back again. There are diagnostics being sent and then removed repeatedly on edit. Sometimes, I can edit the file, and they'll persist. Looking at the logs, it appears to be errors about imports.

Logs: https://gist.github.com/zikaeroh/7a9674c79a34a35e3e8973ceffae5c3c

#### Build info

```
golang.org/x/tools/gopls master
    golang.org/x/tools/gopls@v0.1.8-0.20200131211209-ecb101ed6550 h1:0NRGhttWS2Y5cK/h+uPZyIQewGG9mx0M3DRRkuMAjNU=
    github.com/BurntSushi/toml@v0.3.1 h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=
    github.com/sergi/go-diff@v1.0.0 h1:Kpca3qRNrduNnOQeazBd0ysaKrUJiIuISHxogkT9RPQ=
    golang.org/x/mod@v0.1.1-0.20191105210325-c90efee705ee h1:WG0RUwxtNT4qqaXX3DPA8zHFNm/D9xaBpxzHt1WcA/E=
    golang.org/x/sync@v0.0.0-20190423024810-112230192c58 h1:8gQV6CLnAEikrhgkHFbMAEhagSSnXWGV915qUMm9mrU=
    golang.org/x/tools@v0.0.0-20200131211209-ecb101ed6550 h1:3Kc3/T5DQ/majKzDmb+0NzmbXFhKLaeDTp3KqVPV5Eo=
    golang.org/x/xerrors@v0.0.0-20191011141410-1b5146add898 h1:/atklqdjdhuosWIl6AIbOeHJjicWYPqR9bpxqxYG2pA=
    honnef.co/go/tools@v0.0.1-2019.2.3 h1:3JgtbtFHMiCmsznwGVTUWbgGov+pVqnlf1dEJTNAXeM=
    mvdan.cc/xurls/v2@v2.1.0 h1:KaMb5GLhlcSX+e+qhbRJODnUUBvlw01jt4yrjFIHAuA=
```

#### Go info

```
go version go1.13.7 linux/amd64

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/jake/.cache/go-build"
GOENV="/home/jake/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/jake/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/jake/zikaeroh/hortbot/hortbot/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build291942412=/tmp/go-build -gno-record-gcc-switches"
```

**Comment by ridersofrohan** [comment]
The error messages that keeps coming up are: "getting file for AllImportsFixes: command-line-arguments has no metadata" and "diagnose: no workspace packages: command-line-arguments has no metadata".

This issue seems to be on [go/packages/golist.go#L289](https://github.com/golang/tools/blob/ea181f53ac568019e9fb1574c252555775c01e28/go/packages/golist.go#L289) and seems to be caused from falling back to using an ad-hoc package is there is an error loading the package, I think the problem here is that if the file does not have a package line yet, then the package that gets returned from go/packages will be "command-line-arguments". gopls caches this package and attempts to keep loading this package on file changes and never gets any metadata back.

**Comment by ridersofrohan** [comment]
@zikaeroh I just pushed up https://go-review.googlesource.com/c/tools/+/219222 that should have fixed this issue. Can you give it a try when you get the chance?

**Comment by zikaeroh** [comment]
No, the issue still appears. Note that this extends out into all packages that depend on the package with a new file.

New logs: https://gist.github.com/zikaeroh/69ff621bcaff40c8199e7c0d651cf4be

I add a new file `a.go`, it appears to be fine, then reverse dependencies show red. Then, I hit "enter" and insert a new line, and then the `bot` package breaks too.

**Comment by stamblerre** [comment]
Related: https://github.com/microsoft/vscode-go/issues/3082

**Comment by stamblerre** [comment]
@zikaeroh, are you still seeing this issue with Go 1.14? I'm quite certain it should only be a problem with 1.13 and below, so I'm not sure if it's worth us finding a work-around for this issue.

**Comment by zikaeroh** [comment]
I haven't seen this specifically since I upgraded to Go 1.14, no, though I do occasionally get the "your workspace is misconfigured" when adding a new file or test file. Not sure if that one's been filed elsewhere yet.

**Comment by zikaeroh** [comment]
Out of curiosity, what about 1.14 would make this issue not happen?

**Comment by stamblerre** [comment]
There was a `go` command bug that was dropping imports when a file was empty - it was fixed for 1.14. I think we won't try to make it work for 1.13 - it will be too complicated. I have noticed the "Your workspace is misconfigured" message though - I'll leave this open and fix that.

**Comment by stamblerre** [comment]
Duplicate of https://github.com/golang/go/issues/37958

**Comment by rowe0x** [comment]
@stamblerre This problem doesn't fixed in go1.14.

**Comment by stamblerre** [comment]
@rowe0x: Can you please provide a repro case or [`gopls` logs](https://github.com/golang/tools/blob/master/gopls/doc/troubleshooting.md#capturing-logs)? I have not seen this issue in Go 1.14.

**Comment by stamblerre** [comment]
Reopening this because we should add a regression test for it.

@findleyr: Because of the diagnostic caching, we can't wait for empty diagnostics, so I think the easiest way to implement this would be to fail if we get new non-empty diagnostics for the given file. Is this something we could do in the regression tests? It sounds similar to what you've mentioned about waiting until `gopls` is quiescent :smile:

**Comment by pjweinb** [comment]
Is there some way of marking this as 'fixed but awaiting regression test'?

**Comment by findleyr** [comment]
> Is there some way of marking this as 'fixed but awaiting regression test'?

We could close this and open a separate issue for the regtests... **BUT** with https://golang.org/cl/229777 (and the associated stack of changes) we should be able to write this test! So I would propose waiting until that stack is reviewed, and then I'd be happy to write a test for this.

**Comment by AkaiNoCat** [comment]
I had the same problem just now:
`1.14.2`
/Users/kx0591/go/src/go_learning/gopl.io/ch1/helloworld.go
but,When I remove the `.io`,and the problem disappears
/Users/kx0591/go/src/go_learning/gopl/ch1/helloworld.go

**Comment by stamblerre** [comment]
@AkaiNoCat: This sounds like a different issue (possibly related to your Go setup). Please file a new issue with the information requested in the [troubleshooting guide](https://github.com/golang/tools/blob/master/gopls/doc/troubleshooting.md).
