### ISSUE TITLE
x/mobile/cmd/gomobile: Go1.15beta1 cannot generate Objective-c bindings because hardcoded GOARCH=arm configuration is used to load packages

### ISSUE THREAD

**Issue by libnat** [golang/go#39575]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15beta1 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOOS="darwin"
</pre></details>

### What did you do?
Tried three ways, all failed with the same error
gomobile bind -v -target=ios .
gomobile bind -v -target=ios/arm64 .
GOARCH=arm64 gomobile bind -v -target=ios .

### What did you expect to see?
Generate objective-c framework

### What did you see instead?
gomobile: go [-e -json -compiled=true -test=false -export=false -deps=false -find=true -tags=ios -- mypkg]: exit status 2: cmd/go: unsupported GOOS/GOARCH pair darwin/arm

**Comment by davecheney** [comment]
Go 1.15 has removed support for `darwin/arm`. Please see the [draft release nots](https://tip.golang.org/doc/go1.15#darwin)

**Comment by libnat** [comment]
@davecheney Thanks for your reply. Actually my GOARCH is arm64. You could take a look at the output of `go env`.

**Comment by libnat** [comment]
@davecheney Could you help to review this issue again? I didn't mean it should support darwin/arm. It's just an error message. Now I have changed the issue title. Thanks

**Comment by davecheney** [comment]
Please reopen the issue and edit the description as appropriate

**Comment by libnat** [comment]
> Please reopen the issue and edit the description as appropriate

It seems I am not allowed to reopen this issue.
Github has a rule: Non-collaborator cannot reopen its own issues if a repo collaborator closed them.
@davecheney Could you help to reopen it? Thanks

**Comment by ianlancetaylor** [comment]
I've reopened it but I'm not sure I understand the problem.  Are you saying that gomobile requires darwin/arm support in all cases even when not building for darwin/arm?  That would be unfortunate.

CC @hyangah

**Comment by libnat** [comment]
@ianlancetaylor Your understanding is correct. I have fixed this issue locally. 
There is a line in `golang.org/x/mobile/cmd/gobind/bind.go`
`config.Env = append(os.Environ(), "GOARCH=arm", "GOOS="+targetOS, "CGO_ENABLED=1")`
If I replace "GOARCH=arm" with "GOARCH=arm64", then `gomobile bind -target=ios/arm64` works.
It looks like gomobile needs to make some changes if built with Go 1.15.

**Comment by hajimehoshi** [comment]
Confirmed. I'll take a look.

```
$ go1.15beta1 test ./cmd/gomobile/
go: downloading golang.org/x/tools v0.0.0-20200117012304-6edc0a871e69
go: downloading golang.org/x/mod v0.1.1-0.20191209134235-331c550502dd
go: downloading golang.org/x/xerrors v0.0.0-20191011141410-1b5146add898
--- FAIL: TestIOSBuild (0.08s)
    build_darwin_test.go:49: GOMOBILE=/Users/hajimehoshi/go/pkg/gomobile
        WORK=$WORK
        
    build_darwin_test.go:50: go [-e -json -compiled=true -test=false -export=false -deps=false -find=true -tags=tag1,ios -- golang.org/x/mobile/example/basic]: exit status 2: cmd/go: unsupported GOOS/GOARCH pair darwin/arm
        
FAIL
FAIL    golang.org/x/mobile/cmd/gomobile        5.209s
FAIL
```

**Comment by libnat** [comment]
> https://golang.org/cl/241717

Thanks for the reply. This change can fix this issue. 
I just found another issue after this change. `gomobile bind -target=ios` will only generate arm64 binary. It would be better to generate both arm64 and amd64 binaries by default. Arch amd64 is required for iOS simulator. 
Before this change, gomobile built with go 1.14  will generate iOS framework which contains armv7, arm64, i386, amd64 binaries together. 
As armv7 and i386 are not supported in go 1.15, it's expected to generate iOS framework which contains arm64 and amd64 by default.

**Comment by diegomontoya** [comment]
Why is that go1.15beta1 and gomobile allows android generation of armv7 and i386 .so files?

If i386 and armv7 is deprecated in go1.15, why are we only seeing this bug when target=ios. When target=android, both armv7 and i386 .so functional libraries are generated in the .aar file. 

There needs to be come clarification to this.

**Comment by dmitshur** [comment]
@libnat If that issue you found is an issue right now, please open a separate issue to track it. If it's introduced by that CL, please leave a review comment on it.

@diegomontoya Only the darwin 32-bit ports are deprecated in Go 1.15. See https://tip.golang.org/doc/go1.15#darwin.

**Comment by diegomontoya** [comment]
Use the patch at https://golang.org/cl/241717 with Go 1.15beta1

gomobile bind -target=ios FAILS (same unsupported GOOS ARCH combo dawin/arm)
gomobile bind -target=ios/arm64 WORKS 
gomobile bind -target=ios/amd64 FAILS  (cflag error --mmacosx-version-min=10.11 not allowed with -mios-simulator-version-min=7.0

The patch only addressed the specifics of passing -target=ios/arm64 and not the entire -target=ios build set. Something is wrong in go1.15bet1 causing =ios/amd64 compile inserting the macos build flag which xcode rejects.

**Comment by hajimehoshi** [comment]
> gomobile bind -target=ios FAILS (same unsupported GOOS ARCH combo dawin/arm)

I'll try to create another CL.

**Comment by hajimehoshi** [comment]
I think we can close this issue (I don't have a right to do this :-)

**Comment by dmitshur** [comment]
Fixed via [CL 243477](https://golang.org/cl/243477) and [CL 241717](https://golang.org/cl/241717).

**Comment by diegomontoya** [comment]
@hagen1778 @dmitshur 

Unfortunately still not fixed. I checked the patch set and the IOS allArchs code is wrong to include 386 target.

```
return []string{"arm64", "386", "amd64"}
```

go1.15 also deprecated i386 for darwin. As result, I am getting "darwin/386" wrong GOOS/ARCH error when target=ios. 

Build system:

1) go tip
2) gomobile/gobind tip

**Comment by diegomontoya** [comment]
@hagen1778 @dmitshur

I really think the buildbot needs a updated test. This should not have passed buildbot ci imo.

**Comment by hajimehoshi** [comment]
That's a little odd since `go1.15beta1 test -run=BindIOSAll ./cmd/gomobile/` passed on my local machine. Let me investigate.

**Comment by hajimehoshi** [comment]
> That's a little odd since go1.15beta1 test -run=BindIOSAll ./cmd/gomobile/ passed on my local machine.

My bad, the `-n` flag was on in the test and actual command execution (go build) did not run...

**Comment by hajimehoshi** [comment]
@diegomontoya Does the latest commit work fine for you?

**Comment by libnat** [comment]
@hajimehoshi Thank you for the changes. It still doesn't work for me. Got a new error: 
`clang: error: invalid argument '-mmacosx-version-min=10.11' not allowed with '-mios-simulator-version-min=7.0' ` 
Could you have a look at this? Please let me know if I should create a new issue.
Thanks

**Comment by hajimehoshi** [comment]
@libnat I see. Could you file another issue? Thanks!

**Comment by libnat** [comment]
@hajimehoshi Fine. I created another issue: https://github.com/golang/go/issues/40390
