### ISSUE TITLE
x/build/cmd/gopherbot: mark Gerrit comments as CI-generated

### ISSUE THREAD

**Issue by FiloSottile** [golang/go#39828]
From https://www.gerritcodereview.com/2020-05-06-change-log-experiment.html

> All human messages are shown, but for autogenerated messages they are only shown on one patchset. If for example a CI system posts on patchsets 3, 4, 5, 6, 7, and a Linter posts on patchsets 3, 5, 6, then the CI messages are only shown on ps 7, and the Linter messages are only shown on ps 6.

That sounds great!

However, as far as I can tell, Gobot Gobot is just pretending to be a human account, so it does not benefit from this logic. It'd be nice to port it to whatever system it needs to use to be recognized as a CI tool.

It might even have better security properties than a GSuite account.

/cc @golang/osp-team

**Comment by dmitshur** [comment]
This may have been resolved by placing the Go Bot account (and Gerrit Bot) in a "Service Users" group for Gerrit's Attention Set feature (documented [here](https://gerrit-review.googlesource.com/Documentation/user-attention-set.html)), see internal issue b/171883377 for details.

Do you think there's more left to do here?

**Comment by FiloSottile** [comment]
I think the "Service Users" group simply exempts Go Bot from attention set logic.

I still see Go Bot entries on older Patch Sets. I think this change would significantly reduce visual clutter.

Finally, moving Go Bot to a service account from a GSuite account sounds like a nice cleanup.

**Comment by FiloSottile** [comment]
Go Bot's messages are still shown for all past Patch Sets.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/1225294/114692852-029aa600-9ce7-11eb-8e5f-a08a675aeb14.png">

This is nearly undocumented, but what we need to do is tag those messages with a tag with an `autogenerated:` prefix.

https://groups.google.com/g/repo-discuss/c/JdTcZSeg-o4

**Comment by FiloSottile** [comment]
Ah, found the right docs. Sending a CL.

https://gerrit-review.googlesource.com/Documentation/rest-api-changes.html#review-input
