### ISSUE TITLE
x/pkgsite: Remove 2 modules

### ISSUE THREAD

**Issue by davidsbond** [golang/go#41439]
Hello, I've been fiddling around with vanity import paths and have accidentally merged some modules together I didn't intend to. 

Could these modules be removed in their entirety please?
https://pkg.go.dev/pkg.dsb.dev/bimpsonbot
https://pkg.go.dev/pkg.dsb.dev/eventsource

Thank you

**Comment by julieqiu** [comment]
Done.

**Comment by davidsbond** [comment]
Thanks @julieqiu,

I noticed I can still see them at the bottom of the list here:

https://pkg.go.dev/pkg.dsb.dev

Will those go away once I've done a new version of the `pkg.dsb.dev` module?

**Comment by julieqiu** [comment]
They've been deleted.

**Comment by davidsbond** [comment]
Perfect, thank you very much :)
