### ISSUE TITLE
Support VAES and VPCLMULQDQ instructions in cryto/cipher/AES-GCM and internal/cpu

### ISSUE THREAD

**Issue by tpaint** [golang/go#42726]
### What version of Go are you using (`go version`)?

<pre>
$ go version 1.15.5 linux/amd64

</pre>

### Does this issue reproduce with the latest release? 
yes

### What operating system and processor architecture are you using (`go env`)? amd64 linux

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
amd64 linux
</pre></details>

### What did you do?
This is a request/proposal for two new features:
1. In internal/cpu:  detect CPU support for AVX-512 VAES and VPCLMULQDQ SIMD instructions
2. In crypto/aes: performance-optimize the AES-GCM cipher functions using VAES and VPCLMULQDQ instructions

### What did you expect to see?
in src/crypto/aes/gcm_amd64.s, the request is to support new AVX-512 SIMD crypto instructions VAES and VPCLMULQDQ.

### What did you see instead?
in src/crypto/aes/gcm_amd64.s currently there is existing support only for the scalar AES and PCLMULQDQ instructions

We have developed proposed patches for go v1.15.5 as follows:
1) internal/cpu:  check the cpu registers for presence of VAES and VPCLMULQDQ, set flags accordingly
2) crypto/aes:  performance-optimize AES-GCM using these instructions 

The patches will be contributed and submitted to the Go Gerrit for review. 

References:
1.  https://www.tomshardware.com/news/intel-10nm-xeon-ice-lake-sp-sunny-cove-core-architecture
2.  https://www.intel.com/content/dam/www/public/us/en/documents/manuals/64-ia-32-architectures-software-developer-instruction-set-reference-manual-325383.pdf

**Comment by dmitshur** [comment]
CC @FiloSottile, @agl, @katiehockman, @rolandshoemaker per [owners](https://dev.golang.org/owners).

**Comment by FiloSottile** [comment]
Please keep in mind the [new assembly policy](golang.org/wiki/AssemblyPolicy). Happy to work with you to make sure the contribution follows that policy.

**Comment by tpaint** [comment]
We have implemented a new version of the vaes/vpclmulqdq optimized GCM cipher and posted it to CL 334610.  Performance on cpus that support these instructions is significantly improved in comparison to the original version posted in CL 286852.  Details are in the CL and associated source comments.

**Comment by Jorropo** [comment]
Using AVX512 here is not needed btw, we can use VAES with AVX and still get the 2X performance improvement.
Both intel alder-lake (P and E cores) and Zen4 cores only have 256 bits wide AES units (Zen4 never do 512 AVX512, they always do two 256 bits ops).

So on today's cpus doing `VAES` on 512 bits ZMM registers takes twice longer than 256 bits YMM.

VPCLMULQDQ can help in other ways.
