### ISSUE TITLE
cmd/go: malformed module path with retract v2+

### ISSUE THREAD

**Issue by seankhliao** [golang/go#44494]
### What version of Go are you using (`go version`)?

<pre>
go version go1.16 linux/amd64
go version devel +0f66fb7b85 Sun Feb 21 02:25:41 2021 +0000 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/arccy/.cache/go-build"
GOENV="/home/arccy/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/arccy/.data/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/arccy/.data/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/arccy/sdk/gotip"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/arccy/sdk/gotip/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="devel +0f66fb7b85 Sun Feb 21 02:25:41 2021 +0000"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/arccy/testrepo-291/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1689737487=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

add a retract directive to a v2+ module and run `go mod tidy`

```gomod
module go.seankhliao.com/testrepo-291/v2

go 1.16

retract v2.0.0
```

### What did you expect to see?

no error

### What did you see instead?

```sh
» go mod tidy
go: errors parsing go.mod:
/home/arccy/testrepo-291/go.mod:5: malformed module path "": empty string
```

**Comment by komuw** [comment]
I had reported a slight variant of this in gophers slack, where I was trying to retract a version 2 while the module is still in version 0.   

repro:
```
mkdir -p /tmp/example; cd /tmp/example; go mod init example
rm -rf main.go
tee -a main.go <<EOF
package main
func main(){println("hello")}
EOF
go mod edit -retract=v2.0.2
go mod tidy
```

The error message I got is;
```
go: errors parsing go.mod:
/tmp/example/go.mod:5: malformed module path "": empty string
```
Seankhliao pointed out it should not be possible to retract a v2 while still in v0.   
So, I'm just posting this here so that the error message can be improved; `malformed module path` would lead someone to believe that the thing they need to fix is their module name/path

**Comment by bcmills** [comment]
CC @jayconrod @matloob

**Comment by bcmills** [comment]
@gopherbot, please backport to Go 1.16.

**Comment by bcmills** [comment]
Just FYI: this is **not** fixed by [CL 295150](https://golang.org/cl/295150), so #44497 appears to be unrelated.

**Comment by komuw** [comment]
@jayconrod Thanks for working on & closing this.  
However, if someone edits the `go.mod` file and adds a retract, then they still get a confusing error message when running `go mod tidy` or `go build`
```bash
mkdir -p /tmp/example; cd /tmp/example; gotip mod init example
rm -rf main.go
tee -a main.go <<EOF
package main
func main(){println("hello")}
EOF
rm -rf go.mod
tee -a go.mod <<EOF
module example
go 1.17
retract v2.0.2
EOF
gotip mod tidy
```

```
go: errors parsing go.mod:
/tmp/example/go.mod:3: malformed module path "": empty string
```
I still think this error message could be better. `malformed module path` implies that what is wrong with our mod file is the module path, yet it isn't

**Comment by jayconrod** [comment]
@komuw Thanks. Looks like things are still not quite right.

Could you verify what commit you're building from? I'm actually seeing a different error at 5f15af111c. 

```
go: errors parsing go.mod:
/tmp/example/go.mod:3: malformed module path "example": missing dot in first path element
```

**Comment by komuw** [comment]
@jayconrod 
I have just updated my `gotip`;
```bash
gotip version
go version devel +e25040d Fri Feb 26 02:52:33 2021 +0000 darwin/amd64
```

and the error I now get is;
```
go: errors parsing go.mod:
/tmp/example/go.mod:3: malformed module path "example": missing dot in first path element
```

**Comment by bcmills** [comment]
@komuw, we're getting closer, then! The real problem now, I think, is that it is not possible to `retract` a path that cannot be fetched remotely (because how would users be notified of the retraction?).

But we still need a better error message for that case. 🙂

**Comment by komuw** [comment]
```
gotip version
go version devel +a400eb3 Mon Mar 1 15:24:01 2021 +0000 darwin/amd64
```

```
gotip mod tidy

go: errors parsing go.mod:
/tmp/example/go.mod:3: retract example: version "v2.0.2" invalid: should be v0 or v1, not v2
```

```
go build .

go: errors parsing go.mod:
/tmp/example/go.mod:3: malformed module path "": empty string
```

@jayconrod Thanks for fixing the error message.  The `go build` error message is still off, is that intentional?   
Personally, I'm okay with it since I usually run tidy before build.

**Comment by komuw** [comment]
> ```
> gotip version
> go version devel +a400eb3 Mon Mar 1 15:24:01 2021 +0000 darwin/amd64
> ```
> 
> ```
> gotip mod tidy
> 
> go: errors parsing go.mod:
> /tmp/example/go.mod:3: retract example: version "v2.0.2" invalid: should be v0 or v1, not v2
> ```
> 
> ```
> go build .
> 
> go: errors parsing go.mod:
> /tmp/example/go.mod:3: malformed module path "": empty string
> ```
> 
> @jayconrod Thanks for fixing the error message. The `go build` error message is still off, is that intentional?
> Personally, I'm okay with it since I usually run tidy before build.


Apologies, I just realised I was running `go build .` instead of `gotip build .`     


```
gotip build .

go: errors parsing go.mod:
/tmp/example/go.mod:3: retract example: version "v2.0.2" invalid: should be v0 or v1, not v2
```

using `gotip build .` returns the correct error
