### ISSUE TITLE
x/website: error communicating with remote server on "try go" playground links

### ISSUE THREAD

**Issue by TNSelahle** [golang/go#49988]
### What is the URL of the page with the issue?
 https://go.dev/
 
 
### What is your user agent?
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36
 
 
 
### Screenshot
![image](https://user-images.githubusercontent.com/30689767/144754118-12abe8f1-cdd7-4392-a570-1ad2d4b3df96.png)
 
 
 
### What did you do?
Just opened the site and tried to run the example code
 
 
 
### What did you expect to see?
Hello, 世界
 
 
### What did you see instead?
Error communicating with remote server.

**Comment by TNSelahle** [comment]
![image](https://user-images.githubusercontent.com/30689767/144754201-ed71551a-b889-443a-a925-a1724d3ec4f7.png)

**Comment by ALTree** [comment]
I think [CL 368914](https://go-review.googlesource.com/c/website/+/368914) fixed the issue but it hasn't been deployed yet.

**Comment by TNSelahle** [comment]
Nice, @ALTree. And thanks for correcting the title. My bad there. 

Shall I close this?

**Comment by toothrot** [comment]
I believe this has been resolved. Please let me know if I am mistaken.

**Comment by fzipp** [comment]
@toothrot The "Try go" playground on the front page still doesn't work, even though the website was deployed. But the tour works now.
