### ISSUE TITLE
x/tools/gopls: spurious errors about vendor directories when using `go.work`

### ISSUE THREAD

**Issue by esimov** [golang/go#53933]

**Comment by findleyr** [comment]
CC @hyangah

**Comment by esimov** [comment]
@findleyr with an earlier version of gopls as suggested  by @dzpt is working, but still the package autoimport is still not working.

**Comment by esimov** [comment]
@findleyr 

> where is your go.work file? Is it in a parent directory of ./parent1 and ./parent2

exactly.

**Comment by findleyr** [comment]
Progress on this has been a bit slow because several team members have been out (myself included), but understanding and fixing this is among our top priorities.

However, I am still unable to reproduce this. Given the workspace layout below, everything works fine. I have two vendored  copies of "github.com/gorilla/websocket" in the workspace, and everything still works.

A couple additional questions:
- Which folder(s) are you opening in VS Code?
- Does your go.work happen to be inside a directory named /vendor/? (in other words, is your workspace itself in a (possibly nested) subdirectory of a "vendor" directory?)

```
issue2324]> ls -R
.:
go.work  go.work.sum  mod1  mod2

./mod1:
go.mod  go.sum  lib  main.go  vendor

./mod1/lib:
lib.go

./mod1/vendor:
github.com  modules.txt

./mod1/vendor/github.com:
gorilla

./mod1/vendor/github.com/gorilla:
websocket

./mod1/vendor/github.com/gorilla/websocket:
AUTHORS         conn.go  json.go  mask_safe.go  README.md             tls_handshake.go
client.go       doc.go   LICENSE  prepared.go   server.go             util.go
compression.go  join.go  mask.go  proxy.go      tls_handshake_116.go  x_net_proxy.go

./mod2:
foo.go  go.mod  go.sum  main.go  vendor

./mod2/vendor:
github.com  modules.txt

./mod2/vendor/github.com:
gorilla

./mod2/vendor/github.com/gorilla:
websocket

./mod2/vendor/github.com/gorilla/websocket:
AUTHORS                 client.go       conn_write.go         json.go  mask_safe.go  README.md    trace.go
client_clone.go         compression.go  conn_write_legacy.go  LICENSE  prepared.go   server.go    util.go
client_clone_legacy.go  conn.go         doc.go                mask.go  proxy.go      trace_17.go  x_net_proxy.go
```

**Comment by realnatuki** [comment]
It stops working. The whole VSCode depending on bad buggy extension is totally useless! It has become the worst code editor PERIOD!

**Comment by esimov** [comment]
> Does your go.work happen to be inside a directory named /vendor/? (in other words, is your workspace itself in a (possibly nested) subdirectory of a "vendor" directory?)

No, it's not. It's in the root directory of where my projects are located.

As a side note, if I'm reverting gopls to v0.8.4 these errors are not showing anymore. Another annoying thing which is quite hard to explain is that from time-to-time the package autoimport functionality stopped working. In this case I need to run `go work use -r .` to make it working again.

**Comment by findleyr** [comment]
Since I don't reproduce this using the workspace above, I wonder if the "AllImportsFixes" error may be a red herring: that particular error should not necessarily prevent other functionality.

@esimov could you please confirm the directory you open from vs code? If possible, could you (or anyone else) also please share a full log from a session that exhibits the behavior?

**Comment by findleyr** [comment]
Another note: https://go.dev/cl/417593 avoids the reported error. Because this may be a red herring I am not sure if it will fix the problem for you, but it would be interesting if you were to try using it:

```
git clone go.googlesource.com/tools
git fetch https://go.googlesource.com/tools refs/changes/93/417593/1 && git checkout FETCH_HEAD
cd gopls
go install
```

**Comment by findleyr** [comment]
Aha, I believe I have reproduced the behavior you are observing.

Your comment about `go work use -r .` was key: it looks like these vendored modules were not created using `go mod vendor`, but rather with direct git checkouts, in which case they would have `go.mod` files that would be discovered by `go work use -r .`. Doing that does allow me to reproduce the errors you see. It also explains why this error was not more widely reported.

I should be able to fix this tomorrow and cut a prerelease. However, in the meantime you should be able to work around this by removing the vendored modules from your `go.work` file.  Please let us know whether that resolves the issue for you (@esimov or anyone else who is experiencing the same problems).

I am not sure whether this warrants an ad-hoc patch release next week, assuming the workaround above (removing the vendored modules from your `go.work` file) resolves the issue. It does seem to be a very confusing and poor user experience, but one that perhaps affects only a small fraction of users. We'll discuss this tomorrow.

**Comment by findleyr** [comment]
Ok, assuming folks can confirm that updating their `go.work` fixes the problem, here's the outcome of my investigation:

- due to the duplicate requirements, the workspace was never valid, even at gopls v0.8.4, because our go.work parsing does some additional validation, rather than relying on e.g. `go list -m all`.
- ...but the go command's handling of duplicate module paths is confusing to me: it seems to silently take the latest 'use' directive, without error
- https://go.dev/cl/400822 "fixed" our logic for deriving workspace packages to depend on the go.work file (which *gopls* detects as invalid), and so the ad-hoc open package is not considered part of the workspace
- gopls' completion handle gets the current file in "workspace mode", which for the open file is now "parseExported", meaning it doesn't contain function bodies and therefore can't complete the selector expression. This just seems wrong.
- generally, our error handling for all this is not at all helpful. If we had a go command error, it would have been presented to the user, but as mentioned above the go command is surprisingly happy.

So, there are many things to fix, but also I don't understand the go command behavior here. (CC @bcmills for questions about the go command behavior with respect to duplicated module paths).

**Comment by bcmills** [comment]
> ...but the go command's handling of duplicate module paths is confusing to me: it seems to silently take the latest 'use' directive, without error

If so, I would call that a `cmd/go` bug. The workspace should contain at most one module per module path.

**Comment by esimov** [comment]
@findleyr in many cases I'm opting to load modules from the vendor folder, because it happens, that due to the changes occurred in the dependent packages, these are causing breaking code changes and it's quite inconvenient in many cases to update the code to the latest release. Another reason why I'm loading the module dependencies from the vendor folder is missing or incomplete functionalities which could be extended to my own needs. What is strange is that gopls is complaining about the same module is loaded twice, but from different vendor folder.

**Comment by findleyr** [comment]
@esimov there can only be one module per module path in a `go.work` file. This is true both for gopls and for the go command: the fact that the go command was not returning errors for you is a bug (#54048): the go command was using whichever vendored copy appeared last in the `go.work` file.

As a corollary: vendoring does not work as expected when using go.work. In the future, the `go` command will not add vendored modules via `go work -r`: #51710.

To work on two different copies of a module, open two separate VS Code workspace folders using different `go.work` files.

This is a confusing UX. We'll use this issue to track improving that experience in gopls.

**Comment by esimov** [comment]
> In the future, the go command will not add vendored modules via go work -r.
That wouldn't be a problem until the desired functionality is not affected (a possible side effect would be using different versions of the same package as vendored modules).

> To work on two different copies of a module, open two separate VS Code workspace folders using different go.work files
That's not quite user friendly in my opinion, but I can live with it if we don't have a better approach.

**Comment by hyangah** [comment]
My understanding is that vendored modules aren't complete copies of the original modules. They contain only packages required for the main module. When a workspace containing module `A` and `B`, and both `A` and `B` have dependency on a module `C`, there is no guarantee that the `C` under `A`'s and `B`'s vendor directories have compatible contents. Some packages required for `B` may not exist in `C` vendored for `A`. 
I think a better approach is to check out the complete copy of `C` module somewhere and load that in the workspace.

**Comment by findleyr** [comment]
Closing as I think the "confusing" bit of this should hopefully be resolved by the new error message.

Opened #54261 for generally improving the experience of working on packages outside the workspace.

**Comment by esimov** [comment]
A new gopls has been released but unfortunately the issue I have mentioned related to the autocompletion shown in the snapshot is still not fixed.

**Comment by findleyr** [comment]
@esimov the fix here was to make it an error when there are duplicate module paths in modules in your go.work file.  We do not plan to change the restriction that there can only be one module per module path in your go.work: this is fundamental to the design of go workspaces.

#54261 tracks improving the user experience such that some features will still work even if the go.work file is broken.

**Comment by esimov** [comment]
As a follow up, I'm sorry to say, but unfortunately the last gopls version which is working with the above described configuration and project settings is v0.8.4. I was waiting to show up v0.9 and later on v0.10, but none of them are working: the autocompletion is broken completely.
