### ISSUE TITLE
cmd/compile: internal compiler error: shape types have no methods

### ISSUE THREAD

**Issue by amirdlt** [golang/go#55134]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.19.1 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\AmirDLT\AppData\Local\go-build
set GOENV=C:\Users\AmirDLT\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\AmirDLT\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\AmirDLT\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Users\AmirDLT\sdk\go1.18
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Users\AmirDLT\sdk\go1.18\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.18
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=C:\Users\AmirDLT\GolandProjects\flex\go.mod
set GOWORK=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\AmirDLT\AppData\Local\Temp\go-build2421505650=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?
I assign a function argument of type `func(any) any` into a map[string]any as a value e.g. `m["func"] = func(any) any {return nil}`, then read the map and 
assert type then use it, It leads to an internal compiler error in the line I wanted to call the function.
The situation that it has happened is a bit complicated, I've pushed my code on a github project linked 
below. You can see the issue by run the main.go file, if you want to get more info.
Btw I have used generics which can caused this issue probably.
<pre>
Handler[SI ServerInjector, B any] func(injector *HandlerInjector[SI, B]) HandlerResult
handler = w.(func(any) any)(handler).(Handler[SI, B]) --> this line caused the issue
</pre>

project: https://github.com/amirdlt/flex

### What did you expect to see?
Program should be compiled and run successfully

### What did you see instead?
<pre>
# github.com/amirdlt/flex
.\core\middleware.go:142:32: internal compiler error: shape types have no methods core.Handler[go.shape.struct { Username string; ServerBaseInjector = github.com/amirdlt/flex/core.ServerBaseInjector[""._ServerInjector] }_0,go.shape.interface {}_1]

Please file a bug report including a short program that triggers the error.
https://go.dev/issue/new
</pre>

**Comment by mvdan** [comment]
1.18 is an outdated version; please try 1.18.5 or 1.19.1.

**Comment by amirdlt** [comment]
I've tested it with go 1.19.1 too, the issue persists.

**Comment by amirdlt** [comment]
> > 1.18 is an outdated version; please try 1.18.5 or 1.19.1.

I did it, the issue persists.

**Comment by amirdlt** [comment]
> 1.18 is an outdated version; please try 1.18.5 or 1.19.1.

I've tested it with go 1.19.1 too, the issue persists.

**Comment by cherrymui** [comment]
This seems fixed at tip. github.com/amirdlt/flex builds successfully. I think we can close this. Feel free to reopen if it doesn't.

Maybe this is a dup of another issue, but I'm not sure which one. There are a few "shape types have no methods" issues (https://github.com/golang/go/issues?q=is%3Aissue+%22shape+types+have+no+methods%22). It seems unified IR fixes this (it fails to build with `GOEXPERIMENT=nounified`).
cc @mdempsky @cuonglm

**Comment by cuonglm** [comment]
FYI, this does not seem to be a dup of any existed issue, the compiler still crashes with `GOEXPERIMENT=nounified` at current tip f8c659b62ff43e8455ebc675e577b9adc67b3f9f

**Comment by amirdlt** [comment]
> This seems fixed at tip. github.com/amirdlt/flex builds successfully. I think we can close this. Feel free to reopen if it doesn't.
> 
> Maybe this is a dup of another issue, but I'm not sure which one. There are a few "shape types have no methods" issues (https://github.com/golang/go/issues?q=is%3Aissue+%22shape+types+have+no+methods%22). It seems unified IR fixes this (it fails to build with `GOEXPERIMENT=nounified`). cc @mdempsky @cuonglm

It was not a compile error, It compiled successfully, I get an internal compiler error at runtime not compile time.

**Comment by cherrymui** [comment]
The text "internal compiler error" says clearly it is a compile time error.

**Comment by amirdlt** [comment]
> The text "internal compiler error" says clearly it is a compile time error.
I'm sorry, I've made a dumbly mistake.
