### ISSUE TITLE
x/pkgsite: package removal request for codeberg.org/pixelyte

### ISSUE THREAD

**Issue by niceatoms** [golang/go#57510]
### What is the path of the package that you would like to have removed?

 
codeberg.org/pixelyte 
 
### Are you the owner of this package?
yes

 
### What is the reason that you could not retract this package instead?
I have already removed the code from codeberg and i was not aware that it was on pkgsite until recently. Therefore retracting it in the go.mod file is not possible. If possible could the module also be removed from proxy.golang.org and from the go command. It has never been imported by anyone and I am the only one who knows about it. When i try to `go install` one of the commands under that url, it fails(although i did not try all of them), so I assume that means it is already not present in proxy.golang.org

**Comment by seankhliao** [comment]
i don't see it on https://pkg.go.dev/codeberg.org/pixelyte

**Comment by niceatoms** [comment]
Oh, weird. If your simply search `pixelyte` you will find it.

**Comment by niceatoms** [comment]
Am I supposed to resubmit this now that you closed it?

**Comment by niceatoms** [comment]
I'll just resubmit with individual urls

**Comment by seankhliao** [comment]
oh, the entire prefix.
Can you prove ownership of `codeberg.org/pixelyte` prefix?

**Comment by niceatoms** [comment]
Unfortunately not. I have already deleted the account on codeberg. Is there some other way?

**Comment by niceatoms** [comment]
Oh wait, the intern only deleted the repos. [Here](https://codeberg.org/pixelyte/deleteme/issues/1) is proof

**Comment by seankhliao** [comment]
cc @golang/pkgsite ?

**Comment by suzmue** [comment]
Done!

**Comment by niceatoms** [comment]
@suzmue thanks, but if you search for `pixelyte` on pkg.go.dev you still get results although the links it returns don't work. Is it possible to make it not return results at all?

**Comment by suzmue** [comment]
This appears to be a bug. Filing a follow up issue #57528

**Comment by niceatoms** [comment]
@suzmue It seems like the issue resolved itself. I guess it was probably just still in the cache or something. I think you close that issue now.
