### ISSUE TITLE
x/pkgsite: package removal request for github.com/darvaza-proxy/slog/{cblog,filtered,logrus,noop,zap,zerolog}

### ISSUE THREAD

**Issue by amery** [golang/go#58733]
### What is the path of the package that you would like to have removed?

github.com/darvaza-proxy/slog/cblog
github.com/darvaza-proxy/slog/filtered
github.com/darvaza-proxy/slog/logrus
github.com/darvaza-proxy/slog/noop
github.com/darvaza-proxy/slog/zap
github.com/darvaza-proxy/slog/zerolog
 
### Are you the owner of this package?

yes
 
### What is the reason that you could not retract this package instead?

submodules were moved into [github.com/darvaza-proxy/slog/handlers/](https://github.com/darvaza-proxy/slog/tree/main/handlers) and `pkg.go.dev` insists on showing their old selves linked in https://pkg.go.dev/github.com/darvaza-proxy/slog.
they were moved to clear the root, it would make no sense to recreate the directories just to add retract `go.mod` files on their old locations

**Comment by jamalc** [comment]
Done.

**Comment by amery** [comment]
@jamalc thank you, the broken links at the bottom of https://pkg.go.dev/github.com/darvaza-proxy/slog still appear. anything I can do about those?

**Comment by amery** [comment]
@jamalc they are gone now! THANKS
