### ISSUE TITLE
affected/package: go env GOBIN

### ISSUE THREAD

**Issue by pebbe** [golang/go#58851]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20.1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/peter/.cache/go-build"
GOENV="/home/peter/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/peter/go/pkg/mod"
GONOPROXY="github.com/pebbe/dbxml"
GONOSUMDB="github.com/pebbe/dbxml"
GOOS="linux"
GOPATH="/home/peter/go"
GOPRIVATE="github.com/pebbe/dbxml"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/my/opt/go"
GOSUMDB="sum.golang.org"
GOTMPDIR="/home/peter/tmp"
GOTOOLDIR="/my/opt/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.20.1"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/peter/go/src/github.com/rug-compling/alpinoviewer/go.mod"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/home/peter/tmp/go-build1826612007=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

<pre>
$ go env GOBIN
</pre>

### What did you expect to see?

The name of the directory where `go install` installs programs.

### What did you see instead?

Nothing at all

### More...

<pre>
$ go help environment

The go command and the tools it invokes consult environment variables
for configuration. If an environment variable is unset, the go command
uses a sensible default setting. To see the effective setting of the
variable &lt;NAME&gt;, run 'go env &ltNAME&gt;'.

[omitted]

General-purpose environment variables:

[omitted]

        GOBIN
                The directory where 'go install' will install a command.

[truncated]

$ go env GOBIN

[no output]

$ env | grep GOBIN

[no output]

$ go env GOENV
/home/peter/.config/go/env

$ cat `go env GOENV`
GOPRIVATE=github.com/pebbe/

</pre>

**Comment by fzipp** [comment]
The empty output means that the GOBIN environment variable is not set.

```
$ go help environment
[...] If an environment variable is unset, the go command
uses a sensible default setting.
```

**Comment by mvdan** [comment]
Also see https://github.com/golang/go/issues/23439#issuecomment-582483567.

**Comment by pebbe** [comment]
> The empty output means that the GOBIN environment variable is not set.
> 
> ```
> $ go help environment
> [...] If an environment variable is unset, the go command
> uses a sensible default setting.
> ```

Read the next sentence.

The current behaviour is not what the documentation says it should be. So this is clearly a bug, and it should be fixed.

**Comment by mvdan** [comment]
That is exactly what https://github.com/golang/go/issues/23439#issuecomment-582483567 describes. That issue remains open as it is not fixed.
