### ISSUE TITLE
[go1.21 toolchain] `--help` and `go version` broken when go.mod contains non-standard version

### ISSUE THREAD

**Issue by thaJeztah** [golang/go#60956]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go: downloading go1.22-schrodingers-version-yall (linux/arm64)
go: download go1.22-schrodingers-version-yall for linux/arm64: toolchain not available
</pre>

### Does this issue reproduce with the latest release?

See above

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
go: downloading go1.22-schrodingers-version-yall (linux/arm64)
go: download go1.22-schrodingers-version-yall for linux/arm64: toolchain not available

</pre></details>

### What did you do?

```bash
go mod init foo
sed -i 's/1.21rc2/1.22-schrodingers-version-yall/g' go.mod

go --help
go: downloading go1.22-schrodingers-version-yall (linux/arm64)
go: download go1.22-schrodingers-version-yall for linux/arm64: toolchain not available

go version
go: downloading go1.22-schrodingers-version-yall (linux/arm64)
go: download go1.22-schrodingers-version-yall for linux/arm64: toolchain not available

go --version
go: downloading go1.22-schrodingers-version-yall (linux/arm64)
go: download go1.22-schrodingers-version-yall for linux/arm64: toolchain not available

```

```bash
go mod init foo
sed -i 's/1.21rc2/1.22-schrödingers-version-yall/g' go.mod

go version
go: download go1.22-schrödingers-version-yall: non-semver module version "v0.0.1-go1.22-schrödingers-version-yall.linux-arm64"

go version --help
go: download go1.22-schrödingers-version-yall: non-semver module version "v0.0.1-go1.22-schrödingers-version-yall.linux-arm64"
```

### What did you expect to see?

```
go --help
Go is a tool for managing Go source code.

Usage:

	go <command> [arguments]
# (etc)

go --version
flag provided but not defined: -version
Go is a tool for managing Go source code.
```

### What did you see instead?

```
go: downloading go1.22-schrodingers-version-yall (linux/arm64)
go: download go1.22-schrodingers-version-yall for linux/arm64: toolchain not available
```

**Comment by dmitshur** [comment]
CC @rsc, @bcmills, @matloob.

**Comment by thaJeztah** [comment]
Is it possible to have this fixed in a go1.21 patch release? I see this was moved to go1.22, but this looks like a regression to me.

**Comment by dmitshur** [comment]
This issue still needs to be investigated. It it's determined that the current behavior is buggy, the fix will need to be developed for Go 1.22 first before it can be considered for backport.

To me, it seems that at least the `go version` aspect is working as intended. See the last two paragraphs of https://go.dev/doc/toolchain#select:

> Running go version prints the selected Go toolchain’s version (by running the selected toolchain’s implementation of go version).
>
> Running GOTOOLCHAIN=local go version prints the bundled Go toolchain’s version.

Consider a local toolchain version of "go1.21rc4" and a go.mod file whose "go" line is "go1.21.0". Running `go version` inside such a module correctly prints "go1.21.0", the version of the toolchain that is selected.

Similarly, it probably makes sense that `go --help` in the same module prints the behavior of running go1.21.0's go with "--help" flag, rather than that of go1.21rc4.

**Comment by bcmills** [comment]
@thaJeztah, I think it is important that we print an error and return with nonzero exit status in this case, but perhaps the error message we print in case of a failed upgrade could be more helpful?

- Perhaps it could print the file and line number containing the erroneous `go` directive.
- Perhaps it could suggest setting `GOTOOLCHAIN=local`?

But it's tricky, because additional information risks adding to the confusion instead of clarifying it.

**Comment by seankhliao** [comment]
This seems to no longer be an error on 1.27 / tip

**Comment by dmitshur** [comment]
As far as I can tell, the original reproducer works with go1.21rc2 (as the local toolchain), and not with go1.21rc3. Plausibly fixed by [CL 509097](https://go.dev/cl/509097). Setting the milestone to Go1.21.

**Comment by thaJeztah** [comment]
Yes, at a quick glance, looks to work with the current Go version;

```bash
go mod init foo
sed -i 's/1.26.4/1.22-schrodingers-version-yall/g' go.mod

cat go.mod
module foo

go 1.22-schrodingers-version-yall

go --help
Go is a tool for managing Go source code.
...


go env GOTOOLCHAIN
auto

go version
go version go1.26.4 darwin/arm64
```
