### ISSUE TITLE
x/pkgsite,go/doc: struct fields inconsistently linked in doc comments

### ISSUE THREAD

**Issue by bcmills** [golang/go#61394]
https://go.dev/doc/comment#doclinks currently says:
> Doc links are links of the form “[Name1]” or “[Name1.Name2]” to refer to exported identifiers in the current package

but it is somewhat ambiguous about whether the `[Name1.Name2]` form can refer to struct fields or only methods.

----
 
In practice, people do seem to intuitively expect references to struct fields to work; for example, this [comment](https://cs.opensource.google/go/go/+/master:src/go/types/package.go;l=44;drc=b490bdc27d5576e5ccdac33755c0156d609e1bb9) on [`types.Package.GoVersion`](https://pkg.go.dev/go/types@go1.21rc3#Package.GoVersion) (written by @rsc) refers to the [`go/ast.File.GoVersion`](https://pkg.go.dev/go/ast@go1.21rc3#File) struct field, and `pkg.go.dev` appears to render that reference correctly:
![image](https://github.com/golang/go/assets/5200974/ae92a4f6-4af3-45b5-a25c-9a90920b8d08)

----

However, similar references within the _same_ package are *not* rendered as links. For example, the reference to `[CheckedFiles.SizeError]` from [`zip.CheckedFiles.Err`](https://pkg.go.dev/golang.org/x/mod@v0.12.0/zip#CheckedFiles.Err) is currently rendered as plain text:
![image](https://github.com/golang/go/assets/5200974/f6a1067f-1728-43be-ba9d-95aed9281040)

[`go/doc.Parser`](https://pkg.go.dev/go/doc/comment@go1.21rc3#Parser) uses different functions to resolve intra- vs. inter-package references: it appears that the `LookupPackage` hook being used by `pkgsite` does resolve struct fields, whereas the `LookupSym` hook does not.

**Comment by bcmills** [comment]
I think the bug is in `go/doc`. Although the [`Package.syms`](https://cs.opensource.google/go/go/+/refs/heads/master:src/go/doc/doc.go;l=41;drc=fe5af1532ab9c749d880c05e0ffe0e17bf874d7f) field lacks a clarifying comment, in practice it appears not to include struct fields:
https://cs.opensource.google/go/go/+/refs/heads/master:src/go/doc/doc.go;l=159-171;drc=fe5af1532ab9c749d880c05e0ffe0e17bf874d7f

**Comment by bcmills** [comment]
This is blocked awaiting code review, so moving to Backlog.

**Comment by artyom** [comment]
I was about to file an issue for [net/http.Transport documentation rendering](https://pkg.go.dev/net/http#Transport) and then I found this issue.

```
¶ go doc http.Transport | grep -A3 'Transport caches'
    By default, Transport caches connections for future re-use. This may
    leave many open connections when accessing many hosts. This behavior
    can be managed using Transport.CloseIdleConnections method and the
    [Transport.MaxIdleConnsPerHost] and [Transport.DisableKeepAlives] fields.
```

Hope https://go.dev/cl/510315 gets some attention soon.

**Comment by stevenh** [comment]
I would love to see this hit 1.23 is there any chance of that @bcmills ?

**Comment by bcmills** [comment]
I'm no longer on the Go team so there's zero chance of my CL landing as-is — but you're welcome to clone it and shepherd it through the review process! 🙃

**Comment by cespare** [comment]
This is quite a visible issue with rendered package docs. There are about 30 instances where it occurs in the net/http documentation alone.

![screen_20240821104748](https://github.com/user-attachments/assets/f3455760-59e3-4c2d-9417-292379694791)

@griesemer and @golang/pkgsite -- can you suggest a good person to own this?

**Comment by FiloSottile** [comment]
@griesemer and @golang/pkgsite, friendly ping on this, we have more and more struct field links in various docs that show up as broken links, and it keeps getting reported.

**Comment by jba** [comment]
@FiloSottile Thanks for the bump. I've assigned this to myself and will take a look at it when I have some breathing room in my schedule.

**Comment by jub0bs** [comment]
Another friendly ping on this. One of my libraries is affected by this issue: the documentation heavily link to fields of a config struct type, and those links don't get rendered as they should.

<img width="546" height="293" alt="Image" src="https://github.com/user-attachments/assets/29fef6a6-3534-4018-8a98-2b9f1e9b6f1a" />

**Comment by griesemer** [comment]
Looks like one aspect has already been resolved here? What is left to be done?

**Comment by cespare** [comment]
Has anything been resolved?

As far as I can tell, each example of this bug that has been demonstrated on this issue still reproduces on the production website.

**Example 1 (from the original report):**

Link: https://pkg.go.dev/golang.org/x/mod@v0.12.0/zip#CheckedFiles.Err

Screenshot:

<img width="1462" height="202" alt="Image" src="https://github.com/user-attachments/assets/dd6528ad-e23f-490a-8c22-299c3703e657" />

**Example 2 (from my report at https://github.com/golang/go/issues/61394#issuecomment-2302652200):**

Link: https://pkg.go.dev/net/http#Handler

Screenshot:

<img width="1441" height="642" alt="Image" src="https://github.com/user-attachments/assets/56ce91ee-34aa-44a7-bd8c-d60524b8755c" />

There are a bunch of other examples on the net/http doc page.

**Comment by griesemer** [comment]
It may be too late to get this done for 1.27 but perhaps not. At least now this is on the radar. Seems like this should be fixed rather sooner than later.

**Comment by mrkfrmn** [comment]
It looks like we added fields and interface methods to the set of symbols, but the doc link parsing logic still interprets a 2-part name `Foo.Bar` with `Foo` as the package and `Bar` as some name within that package. `Foo` is not a package typically, so the link is left as-is.

**Comment by mrkfrmn** [comment]
On the other hand, when using the `godoc` and `pkgsite` tools locally, `Handler` seems to produce the expected links—thus I may have been too quick to diagnose. Will take another look tomorrow.

**Comment by mrkfrmn** [comment]
I've bumped pkgsite to the most recent stable Go version. I will check back in a day or so to allow for propagation.

**Comment by nicholashusin** [comment]
Just did another version bump in the `private` part of the pkgsite repo, and triggered a redeploy.

Should be fixed now.

**Comment by cespare** [comment]
Excellent! Thanks for fixing this!
