### ISSUE TITLE
Undefined symbols:   _darwin_arm_init_mach_exception_handler, referenced from:       _x_cgo_init in libxxx-go.a[arm64][9](000006.o)   _darwin_arm_init_thread_exception_port, referenced from:       _threadentry in libxxx-go.a[arm64][9](000006.o)       _x_cgo_init in libxxx-go.a[arm64][9](000006.o)

### ISSUE THREAD

**Issue by IKhatikVipre** [golang/go#63203]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.21.1 darwin/arm64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

GO111MODULE=''
GOARCH='arm64'
GOBIN=''
GOCACHE='/Users/xxx/Library/Caches/go-build'
GOENV='/Users/xxx/Library/Application Support/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='arm64'
GOHOSTOS='darwin'
GOINSECURE=''
GOMODCACHE='/Users/xxx/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='darwin'
GOPATH='/Users/xxx/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/opt/homebrew/Cellar/go/1.21.1/libexec'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/opt/homebrew/Cellar/go/1.21.1/libexec/pkg/tool/darwin_arm64'
GOVCS=''
GOVERSION='go1.21.1'
GCCGO='gccgo'
AR='ar'
CC='cc'
CXX='c++'
CGO_ENABLED='1'
GOMOD='/dev/null'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -ffile-prefix-map=/var/folders/5n/87gntbls2z124zs17r70p5m00000gn/T/go-build4227419323=/tmp/go-build -gno-record-gcc-switches -fno-common'
</pre></details>

### What did you do?
go build

```
SDKROOT ?= $(shell xcrun --sdk $(PLATFORM_NAME) --show-sdk-path)

export PATH := $(PATH):/usr/local/bin:/opt/homebrew/bin
CCFLAGS := clang -arch arm64 -isysroot $(SDKROOT) -mtvos-version-min=17.0 -fembed-bitcode
LDFLAGS := -framework CoreFoundation

CGO_ENABLED := 1
GOOS:= arm64
GOARCH:= appletvos // tried with ios/darwin too
CC:= $(CCFLAGS)
CGO_CFLAGS:=
CGO_LDFLAGS := $(LDFLAGS)
```

// Followed https://go.dev/src/cmd/link/link_test.go?m=text test case for configuration

Go library building fine.

### What did you expect to see?

Builded Go library should be build fine with Xcode 15 Apple TV project.

### What did you see instead?

Builded Go library throwing below build error on Xcode 15 Apple TV target.

```
ld: Undefined symbols:
  _darwin_arm_init_mach_exception_handler, referenced from:
      _x_cgo_init in libxxx-go.a[arm64][9](000006.o)
  _darwin_arm_init_thread_exception_port, referenced from:
      _threadentry in libxxx-go.a[arm64][9](000006.o)
      _x_cgo_init in libxxx-go.a[arm64][9](000006.o)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

OR is there any plan for separate tool for appletvos/arm64 && appletvos/amd64?

$ go tool dist list                                                                                   
...
darwin/amd64
darwin/arm64
...
ios/amd64
iOS/arm64
....

**Comment by thanm** [comment]
This thread may be useful? https://www.mail-archive.com/wireguard@lists.zx2c4.com/msg06624.html

**Comment by thanm** [comment]
See also https://github.com/golang/go/issues/45772

**Comment by cherrymui** [comment]
> GOOS:= arm64
GOARCH:= appletvos // tried with ios/darwin too

This setting doesn't make sense. Could you try setting `GOARCH=arm64` `GOOS=ios` `CGO_ENABLED=1`? This is probably the closest to tvOS.

**Comment by cherrymui** [comment]
@IKhatikVipre what is the exact command you run to build the Go library? And what is the command for the final linking? Thanks.

**Comment by IKhatikVipre** [comment]
> @IKhatikVipre what is the exact command you run to build the Go library? And what is the command for the final linking? Thanks.

go build -ldflags=-w -trimpath -v -o "$(BUILDDIR)/libxxx-go-$(1).a" -buildmode c-archive

**Comment by IKhatikVipre** [comment]
> > GOOS:= arm64
> > GOARCH:= appletvos // tried with ios/darwin too
> 
> This setting doesn't make sense. Could you try setting `GOARCH=arm64` `GOOS=ios` `CGO_ENABLED=1`? This is probably the closest to tvOS.

Yeah I tried this one by looking at https://go.dev/src/cmd/link/link_test.go?m=text But its throwing reported error on Xcode 15 for Apple TV device target.

**Comment by IKhatikVipre** [comment]
> This thread may be useful? https://www.mail-archive.com/wireguard@lists.zx2c4.com/msg06624.html

Hi @thanm , I wasn't trying for simulator target, I was doing it for real device

**Comment by cherrymui** [comment]
It seems you have tried a few environment settings. I think you should use `GOARCH=arm64 GOOS=ios CGO_ENABLED=1` instead of the others. Could you share the _exact_ environment you have when running the build, and the _exact_ error you see for this particular setting? I think you should not see an error like `Undefined symbols: _darwin_arm_init_mach_exception_handler` if you set `GOOS=ios`.

Also, could you share the command you run for linking the Go library with the rest of your project?

Also, as you already found the BuildForTVOS test, could you try if that test passes on your machine? Try running `go test cmd/link -run=TestBuildForTvOS -v` (without the GOOS/GOARCH settings). Thanks.

**Comment by IKhatikVipre** [comment]
> It seems you have tried a few environment settings. I think you should use `GOARCH=arm64 GOOS=ios CGO_ENABLED=1` instead of the others. Could you share the _exact_ environment you have when running the build, and the _exact_ error you see for this particular setting? I think you should not see an error like `Undefined symbols: _darwin_arm_init_mach_exception_handler` if you set `GOOS=ios`.
> 
> Also, could you share the command you run for linking the Go library with the rest of your project?
> 
> Also, as you already found the BuildForTVOS test, could you try if that test passes on your machine? Try running `go test cmd/link -run=TestBuildForTvOS -v` (without the GOOS/GOARCH settings). Thanks.

Hi @cherrymui , I used minimum environment settings `GOARCH=arm64 GOOS=ios CGO_ENABLED=1`, 

Showing below error message:
`Building for 'tvOS', but linking in object file (xxx/Library/tvOS/libxx-go.a[arm64][2](go.o)) built for 'macOS'`


```
% go test cmd/link -run=TestBuildForTvOS -v
=== RUN   TestBuildForTvOS
    link_test.go:270: skipping on non-darwin/amd64 platform
--- SKIP: TestBuildForTvOS (0.02s)
PASS
ok  	cmd/link	0.349s
```

**Comment by cherrymui** [comment]
> Building for 'tvOS', but linking in object file (xxx/Library/tvOS/libxx-go.a[arm64][2](go.o)) built for 'macOS'

This looks like a different error.
Could you try building the Go library with also the C flags, like
```
CC="clang -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/AppleTVOS.platform/Developer/SDKs/AppleTVOS17.0.sdk -mtvos-version-min=12.0 -fembed-bitcode"
CGO_CFLAGS=""
CGO_LDFLAGS="-framework CoreFoundation"
```
along with `GOARCH=arm64 GOOS=ios CGO_ENABLED=1`, when running `go build`?
With this you shouldn't see the "built for 'macOS'" error.

Also, could you try patching the Go distribution with https://go.dev/cl/531555 and then run the test `go test cmd/link -run=TestBuildForTvOS -v` again? The test was skipped, not actually run. With that patch it should actually run.

Thanks.

**Comment by IKhatikVipre** [comment]
> > Building for 'tvOS', but linking in object file (xxx/Library/tvOS/libxx-go.a[arm64][2](go.o)) built for 'macOS'
> 
> This looks like a different error. Could you try building the Go library with also the C flags, like
> 
> ```
> CC="clang -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/AppleTVOS.platform/Developer/SDKs/AppleTVOS17.0.sdk -mtvos-version-min=12.0 -fembed-bitcode"
> CGO_CFLAGS=""
> CGO_LDFLAGS="-framework CoreFoundation"
> ```
> 
> along with `GOARCH=arm64 GOOS=ios CGO_ENABLED=1`, when running `go build`? With this you shouldn't see the "built for 'macOS'" error.
> 
> Also, could you try patching the Go distribution with https://go.dev/cl/531555 and then run the test `go test cmd/link -run=TestBuildForTvOS -v` again? The test was skipped, not actually run. With that patch it should actually run.
> 
> Thanks.

Thanks @cherrymui I haven't applied patch, will do it later. Actual issue was my Makefile was corrupted and its causing to select default `darwin/arm64` GOOS/GOARCH. 
I addressed makefile issue and its started working. Once again thanks for your support.

**Comment by cherrymui** [comment]
Thanks. Sounds like we can close this issue. Feel free to reopen if there is anything more.

**Comment by khanakia** [comment]
@IKhatikVipre I am having the same issue after upgrading the Mac. However, i do have not any makefile it's just a simple HTTP server example that still cannot be built.

Reference: https://github.com/golang/go/issues/62432

Can you provide me with some insight please how to solve this issue?

**Comment by qinqin0** [comment]
@IKhatikVipre Hello, may I ask how to correctly set up and command to compile some Go code into a static library for use on a tvOS device? I have been unable to succeed so far.

**Comment by IKhatikVipre** [comment]
> @IKhatikVipre Hello, may I ask how to correctly set up and command to compile some Go code into a static library for use on a tvOS device? I have been unable to succeed so far.

Hi @qinqin0  You need to set below for tvOS,

ARCHS ?= arm64
PLATFORM_NAME =? appletvos

CFLAGS_PREFIX := $(if $(DEPLOYMENT_TARGET_CLANG_FLAG_NAME),-$(DEPLOYMENT_TARGET_CLANG_FLAG_NAME)=$($(DEPLOYMENT_TARGET_CLANG_ENV_NAME)),) -isysroot $(SDKROOT) -arch

GOARCH_arm64 := arm64
GOARCH_x86_64 := amd64
GOOS_macosx := darwin
GOOS_iphoneos := iOS
GOOS_appletvos := iOS

CGO_ENABLED := 1
CGO_CFLAGS := $(CFLAGS_PREFIX) $(ARCH)
CGO_LDFLAGS := $(CFLAGS_PREFIX) $(ARCH)
GOOS := $(GOOS_$(PLATFORM_NAME))
GOARCH := $(GOARCH_$(1))

**Comment by qinqin0** [comment]
> > @IKhatikVipre Hello, may I ask how to correctly set up and command to compile some Go code into a static library for use on a tvOS device? I have been unable to succeed so far.
> 
> Hi @qinqin0 You need to set below for tvOS,
> 
> ```
> ARCHS ?= arm64
> PLATFORM_NAME =? appletvos
> 
> CFLAGS_PREFIX := $(if $(DEPLOYMENT_TARGET_CLANG_FLAG_NAME),-$(DEPLOYMENT_TARGET_CLANG_FLAG_NAME)=$($(DEPLOYMENT_TARGET_CLANG_ENV_NAME)),) -isysroot $(SDKROOT) -arch
> 
> GOARCH_arm64 := arm64
> GOARCH_x86_64 := amd64
> GOOS_macosx := darwin
> GOOS_iphoneos := iOS
> GOOS_appletvos := iOS
> 
> CGO_ENABLED := 1
> CGO_CFLAGS := $(CFLAGS_PREFIX) $(ARCH)
> CGO_LDFLAGS := $(CFLAGS_PREFIX) $(ARCH)
> GOOS := $(GOOS_$(PLATFORM_NAME))
> GOARCH := $(GOARCH_$(1))
> ```

Thank you! It worked.

**Comment by willis-yang** [comment]
hello,i have same problem,too.
**build command**
`CC=/usr/local/go/misc/ios/clangwrap.sh CGO_ENABLED=1  GOOS=darwin GOARCH=arm64 go build -ldflags "-w"  -o test ./main.go
`
**error info** 
`# command-line-arguments
/usr/local/go/pkg/tool/darwin_amd64/link: running /usr/local/go/misc/ios/clangwrap.sh failed: exit status 1
Undefined symbols for architecture arm64:
  "_darwin_arm_init_mach_exception_handler", referenced from:
      _x_cgo_init in 000005.o
  "_darwin_arm_init_thread_exception_port", referenced from:
      _threadentry in 000005.o
      _x_cgo_init in 000005.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`
 **code**
`package main

import (
	"fmt"
	giDevice "github.com/SonicCloudOrg/sonic-gidevice"
)

func main() {
	test()
	return
}

func test() {
	um, err := giDevice.NewUsbmux()
	if err != nil {
		panic(err)
	}
	fmt.Println("socket started")
	fmt.Println(um)
	devices, err := um.Devices()
	if err != nil {
		fmt.Println("get devices failed")
		panic(err)
	}

	for _, dev := range devices {
		fmt.Println(dev.Properties().SerialNumber, dev.Properties().ProductID, dev.Properties().DeviceID)
	}
	fmt.Println("end")
}
`
go env 
![image](https://github.com/golang/go/assets/42925818/9bc5a36d-38b1-4f4c-aa7c-55efe1f4b87f)

**Comment by khanakia** [comment]
The quickest solution to this problem you can perform as follows: 

- Go to `~/Library/Developer` and rename it to `Developer11`
- Go to `~/Library/Caches` and delete all
- Restart the machine
- After restart run `go cache -clean` and `go build .`

That's it

Let me know if it works. It worked for me

**Comment by willis-yang** [comment]
> The quickest solution to this problem you can perform as follows:
> 
> * Go to `~/Library/Developer` and rename it to `Developer11`
> * Go to `~/Library/Caches` and delete all
> * Restart the machine
> * After restart run `go cache -clean` and `go build .`
> 
> That's it
> 
> Let me know if it works. It worked for me

Unfortunately, it failed.

**Comment by khanakia** [comment]
1. Can you post the output of these values
```
ld -v
clang -v
```

2. Also can you create a new mac user and try to do `go build .` as well without setting any ENV variables as you doing in your command above

**Comment by willis-yang** [comment]
> 1. Can you post the output of these values
> 
> ```
> ld -v
> clang -v
> ```
> 
> 2. Also can you create a new mac user and try to do `go build .` as well without setting any ENV variables as you doing in your command above

**ld -v**
```
>@(#)PROGRAM:ld  PROJECT:ld64-764
>BUILD 11:29:07 May 17 2022
>configured to support archs: armv6 armv7 armv7s arm64 arm64e arm64_32 i386 x86_64 x86_64h armv6m armv7k armv7m >armv7em
>LTO support using: LLVM version 13.1.6, (clang-1316.0.21.2.5) (static support for 28, runtime is 28)
>TAPI support using: Apple TAPI version 13.1.6 (tapi-1316.0.7.3)
```
**clang -v**
>```Apple clang version 13.1.6 (clang-1316.0.21.2.5) 
> Target: arm64-apple-darwin21.2.0
> Thread model: posix
> InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
>```

**Comment by khanakia** [comment]
Did you also tried building by creating a new user ?

**Comment by willis-yang** [comment]
> Did you also tried building by creating a new user ?

 it works,when i using a new user

**Comment by khanakia** [comment]
Ok, then this confirms the issue is only with the Xcode ld which usually should get resolved using the above steps I gave you. Not sure why it did not work in your case.
