### ISSUE TITLE
x/sys/unix: missing ETHTOOL_FLAG_ constants in v0.23.0

### ISSUE THREAD

**Issue by smira** [golang/go#68761]
### Go version

go version go1.22.5 linux/amd64

### Output of `go env` in your module/workspace:

```shell
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/home/smira/.cache/go-build'
GOENV='/home/smira/.config/go/env'
GOEXE=''
GOEXPERIMENT='loopvar'
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/home/smira/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/home/smira/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/home/smira/sdk/go1.22.5'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/home/smira/sdk/go1.22.5/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.22.5'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/home/smira/Documents/image-factory/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build1214322846=/tmp/go-build -gno-record-gcc-switches'
```

### What did you do?

Tried to run e.g. https://github.com/mdlayher/ethtool/blob/main/client_linux.go#L567 with `golang.org/x/sys` v0.23.0

### What did you see happen?

In the commit https://cs.opensource.google/go/x/sys/+/31ef9e726f987c593d73c3c35ca1c7477cf0e480, the constants
`ETHTOOL_FLAG_*` were removed (https://cs.opensource.google/go/x/sys/+/31ef9e726f987c593d73c3c35ca1c7477cf0e480:unix/zerrors_linux.go;dlc=d03a807229bc212694753d74c81119a9b4adb711).

### What did you expect to see?

The constants to stay :)

**Comment by ianlancetaylor** [comment]
This is from https://go.dev/cl/600516.  The constants disappeared, apparently because they changed from #define macros to enums.  Somehow we didn't pick up the enums, and thought that the names had in fact disappeared from the kernel.

CC @mauri870

**Comment by mauri870** [comment]
@ianlancetaylor Thanks for the ping. What is the proper way to guarantee these constants don't disappear when they are converted into enums? Should we always default to define them manually when this happens? I don't think there is a way to handle this during auto generation, at least not currently. This is not the first time x/sys breaks because of disappearing constants as well.

**Comment by ianlancetaylor** [comment]
I haven't looked closely, but I suspect that we need to add the names to x/sys/unix/linux/types.go.  See the `ETHTOOL` symbols that are already there.  It's possible that these names were previously being handled by the `ETHTOOL` match in x/sys/unix/mkerrors.sh.

But I could be mistaken about this.

**Comment by mauri870** [comment]
> I haven't looked closely, but I suspect that we need to add the names to x/sys/unix/linux/types.go. See the `ETHTOOL` symbols that are already there. It's possible that these names were previously being handled by the `ETHTOOL` match in x/sys/unix/mkerrors.sh.
> 
> But I could be mistaken about this.

Thanks, there is a mention to a perl command in x/sys/unix/linux/types.go, but it needs to be executed manually and the output added manually to the constants list. 

I will send a fix shortly. I think it is worth it to integrate this into the automated mkall.sh workflow somehow in the future.

**Comment by mauri870** [comment]
I'm sorry for the inconvenience. The issue should be fixed in the linked CL. Some parts of x/sys are not fully autogenerated, I'll pay more attention when updating this in the future.

**Comment by sriemer** [comment]
This is still an issue for the upgrade command `go get -u all ./... && go mod tidy` and the upgrade `golang.org/x/sys v0.12.0 => v0.33.0`. It needs manual fixing.
I was getting 
```
go: all: module golang.org/x/sys@upgrade found (v0.33.0), but does not contain package golang.org/x/sys/internal/unsafeheader
```

So I went into our `golang:latest` based Docker container and executed the following commands in there to fix this:
```
$ docker run --rm -it -v "$PWD":"/usr/src/app" -w "/usr/src/app" "go_test_image:latest" /bin/bash
$ go get golang.org/x/sys@v0.33.0
go: upgraded go 1.21 => 1.23.0
go: added toolchain go1.24.3
go: upgraded golang.org/x/sys v0.12.0 => v0.33.0
$  go get -u all ./... && go mod tidy
go: downloading ...
go: upgraded ...
...
```
So the second command did not touch `golang.org/x/sys@v0.33.0` anymore - everything upgraded properly.
I hope this helps others once they find this.
