### ISSUE TITLE
proxy.golang.org: Failed to connect to github.com port 443: Connection refused

### ISSUE THREAD

**Issue by troian** [golang/go#72121]
proxy unable to connect to github.com and fetch new version
```
curl https://proxy.golang.org/github.com/akash-network/cosmos-sdk/@v/v0.45.16-akash.3.mod                                                            
not found: github.com/akash-network/cosmos-sdk@v0.45.16-akash.3: invalid version: git ls-remote -q origin in /tmp/gopath/pkg/mod/cache/vcs/9d41348d922b05808134557d6daaee7f11b2589dedd134c83a0317e5a8c68ec7: exit status 128:
	fatal: unable to access 'https://github.com/akash-network/cosmos-sdk/': Failed to connect to github.com port 443: Connection refused
```

looks like this issue was happening earlier today #72118

**Comment by seankhliao** [comment]
seems to be temporary, but whatever the cause, it's GitHub's load balancer that's the one that rejects the connection, I don't think there's much that can be done about it.

**Comment by mholt** [comment]
Still happening here:

```
$ go mod tidy
go: downloading github.com/caddyserver/certmagic v0.22.0
go: github.com/caddyserver/caddy/v2 imports
        github.com/caddyserver/certmagic: github.com/caddyserver/certmagic@v0.22.0: verifying module: github.com/caddyserver/certmagic@v0.22.0: reading https://sum.golang.org/lookup/github.com/caddyserver/certmagic@v0.22.0: 404 Not Found
        server response:
        not found: github.com/caddyserver/certmagic@v0.22.0: invalid version: git ls-remote -q origin in /tmp/gopath/pkg/mod/cache/vcs/b23b06a42c52021c647f7a2d2e88fbbd00ae7bbfa9562e860b588980d1e28f9b: exit status 128:
                fatal: unable to access 'https://github.com/caddyserver/certmagic/': Failed to connect to github.com port 443: Connection refused
go: github.com/caddyserver/caddy/v2 imports
        github.com/quic-go/quic-go tested by
        github.com/quic-go/quic-go.test imports
        github.com/onsi/gomega: github.com/caddyserver/certmagic@v0.22.0: verifying go.mod: github.com/caddyserver/certmagic@v0.22.0/go.mod: reading https://sum.golang.org/lookup/github.com/caddyserver/certmagic@v0.22.0: 404 Not Found
        server response:
        not found: github.com/caddyserver/certmagic@v0.22.0: invalid version: git ls-remote -q origin in /tmp/gopath/pkg/mod/cache/vcs/b23b06a42c52021c647f7a2d2e88fbbd00ae7bbfa9562e860b588980d1e28f9b: exit status 128:
                fatal: unable to access 'https://github.com/caddyserver/certmagic/': Failed to connect to github.com port 443: Connection refused
go: github.com/caddyserver/caddy/v2 imports
        github.com/quic-go/quic-go/http3 tested by
        github.com/quic-go/quic-go/http3.test imports
        github.com/onsi/gomega/types: github.com/caddyserver/certmagic@v0.22.0: verifying go.mod: github.com/caddyserver/certmagic@v0.22.0/go.mod: reading https://sum.golang.org/lookup/github.com/caddyserver/certmagic@v0.22.0: 404 Not Found
        server response:
        not found: github.com/caddyserver/certmagic@v0.22.0: invalid version: git ls-remote -q origin in /tmp/gopath/pkg/mod/cache/vcs/b23b06a42c52021c647f7a2d2e88fbbd00ae7bbfa9562e860b588980d1e28f9b: exit status 128:
                fatal: unable to access 'https://github.com/caddyserver/certmagic/': Failed to connect to github.com port 443: Connection refused
go: github.com/caddyserver/caddy/v2 imports
        go.uber.org/zap tested by
        go.uber.org/zap.test imports
        go.uber.org/goleak: github.com/caddyserver/certmagic@v0.22.0: verifying go.mod: github.com/caddyserver/certmagic@v0.22.0/go.mod: reading https://sum.golang.org/lookup/github.com/caddyserver/certmagic@v0.22.0: 404 Not Found
        server response:
        not found: github.com/caddyserver/certmagic@v0.22.0: invalid version: git ls-remote -q origin in /tmp/gopath/pkg/mod/cache/vcs/b23b06a42c52021c647f7a2d2e88fbbd00ae7bbfa9562e860b588980d1e28f9b: exit status 128:
                fatal: unable to access 'https://github.com/caddyserver/certmagic/': Failed to connect to github.com port 443: Connection refused
go: github.com/caddyserver/caddy/v2/modules/caddyhttp/templates imports
        github.com/alecthomas/chroma/v2/formatters/html tested by
        github.com/alecthomas/chroma/v2/formatters/html.test imports
        github.com/alecthomas/assert/v2: github.com/caddyserver/certmagic@v0.22.0: verifying go.mod: github.com/caddyserver/certmagic@v0.22.0/go.mod: reading https://sum.golang.org/lookup/github.com/caddyserver/certmagic@v0.22.0: 404 Not Found
        server response:
        not found: github.com/caddyserver/certmagic@v0.22.0: invalid version: git ls-remote -q origin in /tmp/gopath/pkg/mod/cache/vcs/b23b06a42c52021c647f7a2d2e88fbbd00ae7bbfa9562e860b588980d1e28f9b: exit status 128:
                fatal: unable to access 'https://github.com/caddyserver/certmagic/': Failed to connect to github.com port 443: Connection refused
go: github.com/caddyserver/caddy/v2/modules/caddyhttp/templates imports
        gopkg.in/yaml.v3 tested by
        gopkg.in/yaml.v3.test imports
        gopkg.in/check.v1: github.com/caddyserver/certmagic@v0.22.0: verifying go.mod: github.com/caddyserver/certmagic@v0.22.0/go.mod: reading https://sum.golang.org/lookup/github.com/caddyserver/certmagic@v0.22.0: 404 Not Found
        server response:
        not found: github.com/caddyserver/certmagic@v0.22.0: invalid version: git ls-remote -q origin in /tmp/gopath/pkg/mod/cache/vcs/b23b06a42c52021c647f7a2d2e88fbbd00ae7bbfa9562e860b588980d1e28f9b: exit status 128:
                fatal: unable to access 'https://github.com/caddyserver/certmagic/': Failed to connect to github.com port 443: Connection refused
go: github.com/caddyserver/caddy/v2/modules/caddyhttp/tracing imports
        go.opentelemetry.io/otel/propagation tested by
        go.opentelemetry.io/otel/propagation.test imports
        github.com/google/go-cmp/cmp: github.com/caddyserver/certmagic@v0.22.0: verifying go.mod: github.com/caddyserver/certmagic@v0.22.0/go.mod: reading https://sum.golang.org/lookup/github.com/caddyserver/certmagic@v0.22.0: 404 Not Found
        server response:
        not found: github.com/caddyserver/certmagic@v0.22.0: invalid version: git ls-remote -q origin in /tmp/gopath/pkg/mod/cache/vcs/b23b06a42c52021c647f7a2d2e88fbbd00ae7bbfa9562e860b588980d1e28f9b: exit status 128:
                fatal: unable to access 'https://github.com/caddyserver/certmagic/': Failed to connect to github.com port 443: Connection refused
go: github.com/caddyserver/caddy/v2/modules/caddypki imports
        github.com/smallstep/certificates/authority tested by
        github.com/smallstep/certificates/authority.test imports
        github.com/smallstep/assert: github.com/caddyserver/certmagic@v0.22.0: verifying go.mod: github.com/caddyserver/certmagic@v0.22.0/go.mod: reading https://sum.golang.org/lookup/github.com/caddyserver/certmagic@v0.22.0: 404 Not Found
        server response:
        not found: github.com/caddyserver/certmagic@v0.22.0: invalid version: git ls-remote -q origin in /tmp/gopath/pkg/mod/cache/vcs/b23b06a42c52021c647f7a2d2e88fbbd00ae7bbfa9562e860b588980d1e28f9b: exit status 128:
                fatal: unable to access 'https://github.com/caddyserver/certmagic/': Failed to connect to github.com port 443: Connection refused
go: github.com/caddyserver/caddy/v2 imports
        github.com/prometheus/client_golang/prometheus imports
        github.com/prometheus/common/model tested by
        github.com/prometheus/common/model.test imports
        github.com/google/go-cmp/cmp/cmpopts: github.com/caddyserver/certmagic@v0.22.0: verifying go.mod: github.com/caddyserver/certmagic@v0.22.0/go.mod: reading https://sum.golang.org/lookup/github.com/caddyserver/certmagic@v0.22.0: 404 Not Found
        server response:
        not found: github.com/caddyserver/certmagic@v0.22.0: invalid version: git ls-remote -q origin in /tmp/gopath/pkg/mod/cache/vcs/b23b06a42c52021c647f7a2d2e88fbbd00ae7bbfa9562e860b588980d1e28f9b: exit status 128:
                fatal: unable to access 'https://github.com/caddyserver/certmagic/': Failed to connect to github.com port 443: Connection refused
go: github.com/caddyserver/caddy/v2/cmd imports
        go.uber.org/automaxprocs/maxprocs imports
        go.uber.org/automaxprocs/internal/runtime tested by
        go.uber.org/automaxprocs/internal/runtime.test imports
        github.com/prashantv/gostub: github.com/caddyserver/certmagic@v0.22.0: verifying go.mod: github.com/caddyserver/certmagic@v0.22.0/go.mod: reading https://sum.golang.org/lookup/github.com/caddyserver/certmagic@v0.22.0: 404 Not Found
        server response:
        not found: github.com/caddyserver/certmagic@v0.22.0: invalid version: git ls-remote -q origin in /tmp/gopath/pkg/mod/cache/vcs/b23b06a42c52021c647f7a2d2e88fbbd00ae7bbfa9562e860b588980d1e28f9b: exit status 128:
                fatal: unable to access 'https://github.com/caddyserver/certmagic/': Failed to connect to github.com port 443: Connection refused
go: github.com/caddyserver/caddy/v2/modules/caddyhttp/templates imports
        github.com/Masterminds/sprig/v3 imports
        github.com/spf13/cast tested by
        github.com/spf13/cast.test imports
        github.com/frankban/quicktest: github.com/caddyserver/certmagic@v0.22.0: verifying go.mod: github.com/caddyserver/certmagic@v0.22.0/go.mod: reading https://sum.golang.org/lookup/github.com/caddyserver/certmagic@v0.22.0: 404 Not Found
        server response:
        not found: github.com/caddyserver/certmagic@v0.22.0: invalid version: git ls-remote -q origin in /tmp/gopath/pkg/mod/cache/vcs/b23b06a42c52021c647f7a2d2e88fbbd00ae7bbfa9562e860b588980d1e28f9b: exit status 128:
                fatal: unable to access 'https://github.com/caddyserver/certmagic/': Failed to connect to github.com port 443: Connection refused
go: github.com/caddyserver/caddy/v2/modules/caddyhttp/templates imports
        github.com/yuin/goldmark-highlighting/v2 imports
        github.com/alecthomas/chroma/v2/lexers tested by
        github.com/alecthomas/chroma/v2/lexers.test imports
        github.com/alecthomas/repr: github.com/caddyserver/certmagic@v0.22.0: verifying go.mod: github.com/caddyserver/certmagic@v0.22.0/go.mod: reading https://sum.golang.org/lookup/github.com/caddyserver/certmagic@v0.22.0: 404 Not Found
        server response:
        not found: github.com/caddyserver/certmagic@v0.22.0: invalid version: git ls-remote -q origin in /tmp/gopath/pkg/mod/cache/vcs/b23b06a42c52021c647f7a2d2e88fbbd00ae7bbfa9562e860b588980d1e28f9b: exit status 128:
                fatal: unable to access 'https://github.com/caddyserver/certmagic/': Failed to connect to github.com port 443: Connection refused
go: github.com/caddyserver/caddy/v2/modules/caddypki/acmeserver imports
        github.com/smallstep/certificates/acme imports
        github.com/smallstep/go-attestation/attest tested by
        github.com/smallstep/go-attestation/attest.test imports
        github.com/google/go-tpm-tools/simulator: github.com/caddyserver/certmagic@v0.22.0: verifying go.mod: github.com/caddyserver/certmagic@v0.22.0/go.mod: reading https://sum.golang.org/lookup/github.com/caddyserver/certmagic@v0.22.0: 404 Not Found
        server response:
        not found: github.com/caddyserver/certmagic@v0.22.0: invalid version: git ls-remote -q origin in /tmp/gopath/pkg/mod/cache/vcs/b23b06a42c52021c647f7a2d2e88fbbd00ae7bbfa9562e860b588980d1e28f9b: exit status 128:
                fatal: unable to access 'https://github.com/caddyserver/certmagic/': Failed to connect to github.com port 443: Connection refused
go: github.com/caddyserver/caddy/v2/modules/caddypki/acmeserver imports
        github.com/smallstep/certificates/acme tested by
        github.com/smallstep/certificates/acme.test imports
        go.step.sm/crypto/tpm/storage imports
        github.com/peterbourgon/diskv/v3: github.com/caddyserver/certmagic@v0.22.0: verifying go.mod: github.com/caddyserver/certmagic@v0.22.0/go.mod: reading https://sum.golang.org/lookup/github.com/caddyserver/certmagic@v0.22.0: 404 Not Found
        server response:
        not found: github.com/caddyserver/certmagic@v0.22.0: invalid version: git ls-remote -q origin in /tmp/gopath/pkg/mod/cache/vcs/b23b06a42c52021c647f7a2d2e88fbbd00ae7bbfa9562e860b588980d1e28f9b: exit status 128:
                fatal: unable to access 'https://github.com/caddyserver/certmagic/': Failed to connect to github.com port 443: Connection refused
go: github.com/caddyserver/caddy/v2/modules/caddypki/acmeserver imports
        github.com/smallstep/certificates/acme tested by
        github.com/smallstep/certificates/acme.test imports
        go.step.sm/crypto/tpm/storage imports
        github.com/schollz/jsonstore: github.com/caddyserver/certmagic@v0.22.0: verifying go.mod: github.com/caddyserver/certmagic@v0.22.0/go.mod: reading https://sum.golang.org/lookup/github.com/caddyserver/certmagic@v0.22.0: 404 Not Found
        server response:
        not found: github.com/caddyserver/certmagic@v0.22.0: invalid version: git ls-remote -q origin in /tmp/gopath/pkg/mod/cache/vcs/b23b06a42c52021c647f7a2d2e88fbbd00ae7bbfa9562e860b588980d1e28f9b: exit status 128:
                fatal: unable to access 'https://github.com/caddyserver/certmagic/': Failed to connect to github.com port 443: Connection refused
go: github.com/caddyserver/caddy/v2 imports
        github.com/quic-go/quic-go imports
        github.com/onsi/ginkgo/v2/ginkgo imports
        github.com/onsi/ginkgo/v2/ginkgo/command tested by
        github.com/onsi/ginkgo/v2/ginkgo/command.test imports
        github.com/onsi/gomega/gbytes: github.com/caddyserver/certmagic@v0.22.0: verifying go.mod: github.com/caddyserver/certmagic@v0.22.0/go.mod: reading https://sum.golang.org/lookup/github.com/caddyserver/certmagic@v0.22.0: 404 Not Found
        server response:
        not found: github.com/caddyserver/certmagic@v0.22.0: invalid version: git ls-remote -q origin in /tmp/gopath/pkg/mod/cache/vcs/b23b06a42c52021c647f7a2d2e88fbbd00ae7bbfa9562e860b588980d1e28f9b: exit status 128:
                fatal: unable to access 'https://github.com/caddyserver/certmagic/': Failed to connect to github.com port 443: Connection refused
go: github.com/caddyserver/caddy/v2 imports
        github.com/quic-go/quic-go imports
        github.com/onsi/ginkgo/v2/ginkgo imports
        github.com/onsi/ginkgo/v2/types tested by
        github.com/onsi/ginkgo/v2/types.test imports
        github.com/onsi/gomega/format: github.com/caddyserver/certmagic@v0.22.0: verifying go.mod: github.com/caddyserver/certmagic@v0.22.0/go.mod: reading https://sum.golang.org/lookup/github.com/caddyserver/certmagic@v0.22.0: 404 Not Found
        server response:
        not found: github.com/caddyserver/certmagic@v0.22.0: invalid version: git ls-remote -q origin in /tmp/gopath/pkg/mod/cache/vcs/b23b06a42c52021c647f7a2d2e88fbbd00ae7bbfa9562e860b588980d1e28f9b: exit status 128:
                fatal: unable to access 'https://github.com/caddyserver/certmagic/': Failed to connect to github.com port 443: Connection refused
go: github.com/caddyserver/caddy/v2 imports
        github.com/quic-go/quic-go imports
        github.com/onsi/ginkgo/v2/ginkgo imports
        github.com/onsi/ginkgo/v2/types tested by
        github.com/onsi/ginkgo/v2/types.test imports
        github.com/onsi/gomega/ghttp: github.com/caddyserver/certmagic@v0.22.0: verifying go.mod: github.com/caddyserver/certmagic@v0.22.0/go.mod: reading https://sum.golang.org/lookup/github.com/caddyserver/certmagic@v0.22.0: 404 Not Found
        server response:
        not found: github.com/caddyserver/certmagic@v0.22.0: invalid version: git ls-remote -q origin in /tmp/gopath/pkg/mod/cache/vcs/b23b06a42c52021c647f7a2d2e88fbbd00ae7bbfa9562e860b588980d1e28f9b: exit status 128:
                fatal: unable to access 'https://github.com/caddyserver/certmagic/': Failed to connect to github.com port 443: Connection refused
go: github.com/caddyserver/caddy/v2 imports
        github.com/quic-go/quic-go imports
        github.com/onsi/ginkgo/v2/ginkgo tested by
        github.com/onsi/ginkgo/v2/ginkgo.test imports
        github.com/onsi/ginkgo/v2/internal/test_helpers imports
        github.com/onsi/gomega/gcustom: github.com/caddyserver/certmagic@v0.22.0: verifying go.mod: github.com/caddyserver/certmagic@v0.22.0/go.mod: reading https://sum.golang.org/lookup/github.com/caddyserver/certmagic@v0.22.0: 404 Not Found
        server response:
        not found: github.com/caddyserver/certmagic@v0.22.0: invalid version: git ls-remote -q origin in /tmp/gopath/pkg/mod/cache/vcs/b23b06a42c52021c647f7a2d2e88fbbd00ae7bbfa9562e860b588980d1e28f9b: exit status 128:
                fatal: unable to access 'https://github.com/caddyserver/certmagic/': Failed to connect to github.com port 443: Connection refused
go: github.com/caddyserver/caddy/v2 imports
        github.com/quic-go/quic-go imports
        github.com/onsi/ginkgo/v2/ginkgo tested by
        github.com/onsi/ginkgo/v2/ginkgo.test imports
        github.com/onsi/ginkgo/v2/internal/test_helpers imports
        github.com/onsi/gomega/gstruct: github.com/caddyserver/certmagic@v0.22.0: verifying go.mod: github.com/caddyserver/certmagic@v0.22.0/go.mod: reading https://sum.golang.org/lookup/github.com/caddyserver/certmagic@v0.22.0: 404 Not Found
        server response:
        not found: github.com/caddyserver/certmagic@v0.22.0: invalid version: git ls-remote -q origin in /tmp/gopath/pkg/mod/cache/vcs/b23b06a42c52021c647f7a2d2e88fbbd00ae7bbfa9562e860b588980d1e28f9b: exit status 128:
                fatal: unable to access 'https://github.com/caddyserver/certmagic/': Failed to connect to github.com port 443: Connection refused
go: github.com/caddyserver/caddy/v2/modules/caddypki imports
        github.com/smallstep/certificates/authority imports
        go.step.sm/cli-utils/ui imports
        github.com/chzyer/readline tested by
        github.com/chzyer/readline.test imports
        github.com/chzyer/test: github.com/caddyserver/certmagic@v0.22.0: verifying go.mod: github.com/caddyserver/certmagic@v0.22.0/go.mod: reading https://sum.golang.org/lookup/github.com/caddyserver/certmagic@v0.22.0: 404 Not Found
        server response:
        not found: github.com/caddyserver/certmagic@v0.22.0: invalid version: git ls-remote -q origin in /tmp/gopath/pkg/mod/cache/vcs/b23b06a42c52021c647f7a2d2e88fbbd00ae7bbfa9562e860b588980d1e28f9b: exit status 128:
                fatal: unable to access 'https://github.com/caddyserver/certmagic/': Failed to connect to github.com port 443: Connection refused
go: github.com/caddyserver/caddy/v2/modules/caddypki imports
        github.com/smallstep/certificates/authority imports
        go.step.sm/crypto/kms tested by
        go.step.sm/crypto/kms.test imports
        go.step.sm/crypto/kms/awskms imports
        github.com/aws/aws-sdk-go-v2/config: github.com/caddyserver/certmagic@v0.22.0: verifying go.mod: github.com/caddyserver/certmagic@v0.22.0/go.mod: reading https://sum.golang.org/lookup/github.com/caddyserver/certmagic@v0.22.0: 404 Not Found
        server response:
        not found: github.com/caddyserver/certmagic@v0.22.0: invalid version: git ls-remote -q origin in /tmp/gopath/pkg/mod/cache/vcs/b23b06a42c52021c647f7a2d2e88fbbd00ae7bbfa9562e860b588980d1e28f9b: exit status 128:
                fatal: unable to access 'https://github.com/caddyserver/certmagic/': Failed to connect to github.com port 443: Connection refused
go: github.com/caddyserver/caddy/v2/modules/caddypki imports
        github.com/smallstep/certificates/authority imports
        go.step.sm/crypto/kms tested by
        go.step.sm/crypto/kms.test imports
        go.step.sm/crypto/kms/awskms imports
        github.com/aws/aws-sdk-go-v2/service/kms: github.com/caddyserver/certmagic@v0.22.0: verifying go.mod: github.com/caddyserver/certmagic@v0.22.0/go.mod: reading https://sum.golang.org/lookup/github.com/caddyserver/certmagic@v0.22.0: 404 Not Found
        server response:
        not found: github.com/caddyserver/certmagic@v0.22.0: invalid version: git ls-remote -q origin in /tmp/gopath/pkg/mod/cache/vcs/b23b06a42c52021c647f7a2d2e88fbbd00ae7bbfa9562e860b588980d1e28f9b: exit status 128:
                fatal: unable to access 'https://github.com/caddyserver/certmagic/': Failed to connect to github.com port 443: Connection refused
go: github.com/caddyserver/caddy/v2/modules/caddypki imports
        github.com/smallstep/certificates/authority imports
        go.step.sm/crypto/kms tested by
        go.step.sm/crypto/kms.test imports
        go.step.sm/crypto/kms/awskms imports
        github.com/aws/aws-sdk-go-v2/service/kms/types: github.com/caddyserver/certmagic@v0.22.0: verifying go.mod: github.com/caddyserver/certmagic@v0.22.0/go.mod: reading https://sum.golang.org/lookup/github.com/caddyserver/certmagic@v0.22.0: 404 Not Found
        server response:
        not found: github.com/caddyserver/certmagic@v0.22.0: invalid version: git ls-remote -q origin in /tmp/gopath/pkg/mod/cache/vcs/b23b06a42c52021c647f7a2d2e88fbbd00ae7bbfa9562e860b588980d1e28f9b: exit status 128:
                fatal: unable to access 'https://github.com/caddyserver/certmagic/': Failed to connect to github.com port 443: Connection refused
go: github.com/caddyserver/caddy/v2/modules/caddypki imports
        github.com/smallstep/certificates/authority imports
        go.step.sm/crypto/kms tested by
        go.step.sm/crypto/kms.test imports
        go.step.sm/crypto/kms/cloudkms imports
        cloud.google.com/go/kms/apiv1: github.com/caddyserver/certmagic@v0.22.0: verifying go.mod: github.com/caddyserver/certmagic@v0.22.0/go.mod: reading https://sum.golang.org/lookup/github.com/caddyserver/certmagic@v0.22.0: 404 Not Found
        server response:
        not found: github.com/caddyserver/certmagic@v0.22.0: invalid version: git ls-remote -q origin in /tmp/gopath/pkg/mod/cache/vcs/b23b06a42c52021c647f7a2d2e88fbbd00ae7bbfa9562e860b588980d1e28f9b: exit status 128:
                fatal: unable to access 'https://github.com/caddyserver/certmagic/': Failed to connect to github.com port 443: Connection refused
go: github.com/caddyserver/caddy/v2/modules/caddypki imports
        github.com/smallstep/certificates/authority imports
        go.step.sm/crypto/kms tested by
        go.step.sm/crypto/kms.test imports
        go.step.sm/crypto/kms/cloudkms imports
        cloud.google.com/go/kms/apiv1/kmspb: github.com/caddyserver/certmagic@v0.22.0: verifying go.mod: github.com/caddyserver/certmagic@v0.22.0/go.mod: reading https://sum.golang.org/lookup/github.com/caddyserver/certmagic@v0.22.0: 404 Not Found
        server response:
        not found: github.com/caddyserver/certmagic@v0.22.0: invalid version: git ls-remote -q origin in /tmp/gopath/pkg/mod/cache/vcs/b23b06a42c52021c647f7a2d2e88fbbd00ae7bbfa9562e860b588980d1e28f9b: exit status 128:
                fatal: unable to access 'https://github.com/caddyserver/certmagic/': Failed to connect to github.com port 443: Connection refused
go: github.com/caddyserver/caddy/v2/modules/caddypki imports
        github.com/smallstep/certificates/authority imports
        go.step.sm/crypto/kms tested by
        go.step.sm/crypto/kms.test imports
        go.step.sm/crypto/kms/cloudkms imports
        github.com/googleapis/gax-go/v2: github.com/caddyserver/certmagic@v0.22.0: verifying go.mod: github.com/caddyserver/certmagic@v0.22.0/go.mod: reading https://sum.golang.org/lookup/github.com/caddyserver/certmagic@v0.22.0: 404 Not Found
        server response:
        not found: github.com/caddyserver/certmagic@v0.22.0: invalid version: git ls-remote -q origin in /tmp/gopath/pkg/mod/cache/vcs/b23b06a42c52021c647f7a2d2e88fbbd00ae7bbfa9562e860b588980d1e28f9b: exit status 128:
                fatal: unable to access 'https://github.com/caddyserver/certmagic/': Failed to connect to github.com port 443: Connection refused
go: github.com/caddyserver/caddy/v2/modules/caddypki imports
        github.com/smallstep/certificates/authority imports
        go.step.sm/crypto/kms tested by
        go.step.sm/crypto/kms.test imports
        go.step.sm/crypto/kms/cloudkms imports
        google.golang.org/api/option: github.com/caddyserver/certmagic@v0.22.0: verifying go.mod: github.com/caddyserver/certmagic@v0.22.0/go.mod: reading https://sum.golang.org/lookup/github.com/caddyserver/certmagic@v0.22.0: 404 Not Found
        server response:
        not found: github.com/caddyserver/certmagic@v0.22.0: invalid version: git ls-remote -q origin in /tmp/gopath/pkg/mod/cache/vcs/b23b06a42c52021c647f7a2d2e88fbbd00ae7bbfa9562e860b588980d1e28f9b: exit status 128:
                fatal: unable to access 'https://github.com/caddyserver/certmagic/': Failed to connect to github.com port 443: Connection refused
go: github.com/caddyserver/caddy/v2/modules/caddypki/acmeserver imports
        github.com/smallstep/nosql imports
        github.com/smallstep/nosql/postgresql imports
        github.com/jackc/pgx/v4 tested by
        github.com/jackc/pgx/v4.test imports
        github.com/cockroachdb/apd: github.com/caddyserver/certmagic@v0.22.0: verifying go.mod: github.com/caddyserver/certmagic@v0.22.0/go.mod: reading https://sum.golang.org/lookup/github.com/caddyserver/certmagic@v0.22.0: 404 Not Found
        server response:
        not found: github.com/caddyserver/certmagic@v0.22.0: invalid version: git ls-remote -q origin in /tmp/gopath/pkg/mod/cache/vcs/b23b06a42c52021c647f7a2d2e88fbbd00ae7bbfa9562e860b588980d1e28f9b: exit status 128:
                fatal: unable to access 'https://github.com/caddyserver/certmagic/': Failed to connect to github.com port 443: Connection refused
go: github.com/caddyserver/caddy/v2/modules/caddypki/acmeserver imports
        github.com/smallstep/nosql imports
        github.com/smallstep/nosql/postgresql imports
        github.com/jackc/pgx/v4 tested by
        github.com/jackc/pgx/v4.test imports
        github.com/gofrs/uuid: github.com/caddyserver/certmagic@v0.22.0: verifying go.mod: github.com/caddyserver/certmagic@v0.22.0/go.mod: reading https://sum.golang.org/lookup/github.com/caddyserver/certmagic@v0.22.0: 404 Not Found
        server response:
        not found: github.com/caddyserver/certmagic@v0.22.0: invalid version: git ls-remote -q origin in /tmp/gopath/pkg/mod/cache/vcs/b23b06a42c52021c647f7a2d2e88fbbd00ae7bbfa9562e860b588980d1e28f9b: exit status 128:
                fatal: unable to access 'https://github.com/caddyserver/certmagic/': Failed to connect to github.com port 443: Connection refused
go: github.com/caddyserver/caddy/v2/modules/caddypki/acmeserver imports
        github.com/smallstep/nosql imports
        github.com/smallstep/nosql/postgresql imports
        github.com/jackc/pgx/v4 imports
        github.com/jackc/pgconn tested by
        github.com/jackc/pgconn.test imports
        github.com/jackc/pgmock: github.com/caddyserver/certmagic@v0.22.0: verifying go.mod: github.com/caddyserver/certmagic@v0.22.0/go.mod: reading https://sum.golang.org/lookup/github.com/caddyserver/certmagic@v0.22.0: 404 Not Found
        server response:
        not found: github.com/caddyserver/certmagic@v0.22.0: invalid version: git ls-remote -q origin in /tmp/gopath/pkg/mod/cache/vcs/b23b06a42c52021c647f7a2d2e88fbbd00ae7bbfa9562e860b588980d1e28f9b: exit status 128:
                fatal: unable to access 'https://github.com/caddyserver/certmagic/': Failed to connect to github.com port 443: Connection refused
go: github.com/caddyserver/caddy/v2/modules/caddypki/acmeserver imports
        github.com/smallstep/nosql imports
        github.com/smallstep/nosql/postgresql imports
        github.com/jackc/pgx/v4 imports
        github.com/jackc/pgtype tested by
        github.com/jackc/pgtype.test imports
        github.com/lib/pq: github.com/caddyserver/certmagic@v0.22.0: verifying go.mod: github.com/caddyserver/certmagic@v0.22.0/go.mod: reading https://sum.golang.org/lookup/github.com/caddyserver/certmagic@v0.22.0: 404 Not Found
        server response:
        not found: github.com/caddyserver/certmagic@v0.22.0: invalid version: git ls-remote -q origin in /tmp/gopath/pkg/mod/cache/vcs/b23b06a42c52021c647f7a2d2e88fbbd00ae7bbfa9562e860b588980d1e28f9b: exit status 128:
                fatal: unable to access 'https://github.com/caddyserver/certmagic/': Failed to connect to github.com port 443: Connection refused
go: github.com/caddyserver/caddy/v2/modules/caddypki/acmeserver imports
        github.com/smallstep/nosql imports
        github.com/smallstep/nosql/badger/v2 imports
        github.com/dgraph-io/badger/v2 imports
        github.com/dgraph-io/badger/v2/y imports
        github.com/cespare/xxhash tested by
        github.com/cespare/xxhash.test imports
        github.com/OneOfOne/xxhash: github.com/caddyserver/certmagic@v0.22.0: verifying go.mod: github.com/caddyserver/certmagic@v0.22.0/go.mod: reading https://sum.golang.org/lookup/github.com/caddyserver/certmagic@v0.22.0: 404 Not Found
        server response:
        not found: github.com/caddyserver/certmagic@v0.22.0: invalid version: git ls-remote -q origin in /tmp/gopath/pkg/mod/cache/vcs/b23b06a42c52021c647f7a2d2e88fbbd00ae7bbfa9562e860b588980d1e28f9b: exit status 128:
                fatal: unable to access 'https://github.com/caddyserver/certmagic/': Failed to connect to github.com port 443: Connection refused
go: github.com/caddyserver/caddy/v2/modules/caddypki/acmeserver imports
        github.com/smallstep/nosql imports
        github.com/smallstep/nosql/badger/v2 imports
        github.com/dgraph-io/badger/v2 imports
        github.com/dgraph-io/badger/v2/y imports
        github.com/cespare/xxhash tested by
        github.com/cespare/xxhash.test imports
        github.com/spaolacci/murmur3: github.com/caddyserver/certmagic@v0.22.0: verifying go.mod: github.com/caddyserver/certmagic@v0.22.0/go.mod: reading https://sum.golang.org/lookup/github.com/caddyserver/certmagic@v0.22.0: 404 Not Found
        server response:
        not found: github.com/caddyserver/certmagic@v0.22.0: invalid version: git ls-remote -q origin in /tmp/gopath/pkg/mod/cache/vcs/b23b06a42c52021c647f7a2d2e88fbbd00ae7bbfa9562e860b588980d1e28f9b: exit status 128:
                fatal: unable to access 'https://github.com/caddyserver/certmagic/': Failed to connect to github.com port 443: Connection refused
```

**Comment by mholt** [comment]
More information:

`go get` (and `go mod tidy`, etc) work again after about 30 minutes.

pkg.go.dev still does not have the new versions, even after 30 minutes.

![Image](https://github.com/user-attachments/assets/03492d3f-4a91-4fda-821f-cb91507d652a)

Not really sure what is going on here, since the issue is clearly not local or intermittent -- but the 30 minute thing seems oddly specific. And I'm not sure why it doesn't apply to the Go package docs. Either the code can be accessed or it can't, right?

I'm _supposing_ this is an issue with the Go module proxy, since GitHub hasn't had any connectivity issues on my end, or on their status page, in the last few days.

**Comment by JunyangShao** [comment]
CC @golang/tools-team.

**Comment by ldemailly** [comment]
Still and issue, 2 tags done and neither working/both having that cached connection error

I don't think connection error should be cached for 1/2h or not retried

**Comment by ldemailly** [comment]
Thanks whoever kicked the thing it started working again now (or maybe it did because I pulled a specific sha first)

**Comment by ldemailly** [comment]
Though https://proxy.golang.org/fortio.org/progressbar/@latest is still broken :-(

**Comment by vault-thirteen** [comment]
Still broken. Please, repair it. Thank you.

**Comment by findleyr** [comment]
@mholt I believe there's a 30m cache of errors. If there were transient github connectivity issues, they may persist for that long.

pkg.go.dev on the other hand has a work queue, which can sometimes get backed up. It looks like https://pkg.go.dev/github.com/caddyserver/certmagic@v0.22.0 is there now.

@vault-thirteen: can you please clarify what is still broken? This issue is reporting ingestion issues, perhaps related to connectivity between Google and GitHub. With which modules are you experiencing problems?

**Comment by findleyr** [comment]
@troian it looks like https://proxy.golang.org/github.com/akash-network/cosmos-sdk/@v/v0.45.16-akash.3.mod is now there as well.

**Comment by vault-thirteen** [comment]
@findleyr 

https://sum.golang.org/lookup/github.com/vault-thirteen/auxie@v0.28.4

![Image](https://github.com/user-attachments/assets/952461be-95ba-4a59-ac3e-ad5ed79ec291)

That git tag was added more than an hour ago and it is still not visible for Golang.

**Comment by ldemailly** [comment]
@findleyr 
> can you please clarify what is still broken? 
this:
> Though https://proxy.golang.org/fortio.org/progressbar/@latest is still broken :-(

**Comment by 3052** [comment]
this tag was pushed yesterday and does not work

~~~
> go get 41.neocities.org/google@v1.7.2
go: downloading 41.neocities.org/google v1.7.2
go: 41.neocities.org/google@v1.7.2: verifying module: 41.neocities.org/google@v1.7.2: reading https://sum.golang.org/lookup/41.neocities.org/google@v1.7.2: 404 Not Found
        server response:
        not found: 41.neocities.org/google@v1.7.2: invalid version: git ls-remote -q origin in /tmp/gopath/pkg/mod/cache/vcs/b18afd26c62b1824482e2ccf2f5c34fa7d46b2c8621dc74f02d7f8cfae7008f7: exit status 128:
                fatal: unable to access 'https://github.com/3052/google.git/': Failed to connect to github.com port 443: Connection refused
~~~

classy response from @seankhliao  - this is obviously an issue with the Go client, as other clients can reach the server without issue

**Comment by devhaozi** [comment]
The problem still exists, I had to run `go env -w GOSUMDB=off` to temporarily disable sumdb.

```
go: loading module retractions for github.com/agiledragon/gomonkey@v2.0.2+incompatible: git fetch -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in C:\Users\HaoZi\go\pkg\mod\cache\vcs\e505e1b31fa80fba07b0dd6d29be728f20337b3f70405b8846c94b4d01abde34: exit status 128:
	fatal: unable to access 'https://github.com/agiledragon/gomonkey/': Failure when receiving data from the peer
go: loading module retractions for github.com/jaevor/go-nanoid@v1.4.0: git ls-remote -q origin in C:\Users\HaoZi\go\pkg\mod\cache\vcs\a97ee9f6b7bb69b45e338f74cfe7c993a510c608f0dec28d52b0cfd796f06ada: exit status 128:
	remote: Repository not found.
	fatal: repository 'https://github.com/jaevor/go-nanoid/' not found
```

**Comment by jamesdube** [comment]
This worked for me:
```
go env -w GOPROXY=direct
go env -w GOSUMDB=off
```

**Comment by 3052** [comment]
> This worked for me:
> 
> ```
> go env -w GOPROXY=direct
> go env -w GOSUMDB=off
> ```

this is the correct fix. this is the second time this year I have been completely down because of the default proxy and checksum database. no more.

https://github.com/golang/go/issues/71125
https://go.dev/doc/go1.13#proxy-vars

**Comment by findleyr** [comment]
Hi all, while we always have some flakiness in fetching from origin servers, the responses here indicate more connectivity issues than normal. I've investigated a bit, and have a few leads as to what could be causing this. I'm currently attempting one mitigation, but if it doesn't work, further intervention will have to wait until Monday.

I see that many of the failing versions are eventually being fetched (for example, both https://proxy.golang.org/fortio.org/progressbar/@latest and https://sum.golang.org/lookup/github.com/vault-thirteen/auxie@v0.28.4 are now there).

As others have pointed out, fetching directly from the origin server is always an available workaround, though it is generally faster and safer to fetch from the proxy. Setting `GOPROXY=direct` and `GOSUMDB=off` in your environment means that all modules, even those that are already hosted in the proxy, will be fetched from the origin server, and sumdb verification is disabled. This can significantly slow down builds, and bypasses the repeatability guarantees provided by the sumdb.

**Comment by vault-thirteen** [comment]
@findleyr 

The problem is not fixed. I started updating the chain of dependencies and see that something is broken again.

https://sum.golang.org/lookup/github.com/vault-thirteen/!simple-!file-!server@v0.16.3

![Image](https://github.com/user-attachments/assets/a86190c1-36c6-4ec0-9253-6f653d79ff1e)

**Comment by rad12000** [comment]
I am also experiencing this issue
![Image](https://github.com/user-attachments/assets/b1565f26-7e52-4574-b43f-4e8a32008d7f)

**Comment by andydotxyz** [comment]
Happening again right now - recent Fyne release cannot be found.

https://sum.golang.org/lookup/fyne.io/fyne/v2@v2.6.0-beta1

![image](https://github.com/user-attachments/assets/e46bc69f-6d0d-4740-ae23-b3113a93771a)

**Comment by findleyr** [comment]
> The problem is not fixed. 

@vault-thirteen understood. Unfortunately, our next step in investigating this will require a rollout, and due to the timing this will likely have to wait until Monday.

[Versions are still flowing](https://index.golang.org/index?since=2025-03-07T18:00:00.000000Z) from GitHub, at a similar rate to a few days ago, so it's not yet clear to me why some seem to be significantly more flaky.

**Comment by trakhimenok** [comment]
Should the `go get` fallback to a a direct retrieval in case if proxy.goland.org failed?

**Comment by andydotxyz** [comment]
> Should the `go get` fallback to a a direct retrieval in case if proxy.goland.org failed?

It feels like that would be a nice to have. I understand the security implications but it seems a little unreasonable to have builds fail just because a GitHub limit was hit internally to the Go sum server systems...

**Comment by findleyr** [comment]
From logs, it looks like these errors are much less frequent after a deployment today, and all of the versions mentioned above have been fetched.

If people are still experiencing this with github.com modules, please let me know the failing module name and version and I'll take a look. Otherwise, I will close this tomorrow. Thanks.

**Comment by ldemailly** [comment]
That's great news - can you share what was fixed/changed or a post mortem result?
tia

**Comment by findleyr** [comment]
@ldemailly we still don't fully understand the root cause. However, our automated deployments of the service responsible for ingesting new module versions were stalled, due to an infrastructure issue. The timing was suspicious: it's possible that the longer-than-usual uptime of the previous deployment could have led to some form of resource exhaustion.

...except that it seems like certain modules were more affected than others, indicating some sort of throttling by Github.

In any case, I unblocked our deployments, and the problem seems to have subsided. We will have to keep an eye out for more reports, and I'll discuss with other team members when they are back from vacation.

Closing as this seems to be resolved.

**Comment by ldemailly** [comment]
Happens again and... how long is the bad error going to get cached?

```
go: grol.io/grol@v0.96.0: verifying module: grol.io/grol@v0.96.0: reading https://sum.golang.org/lookup/grol.io/grol@v0.96.0: 404 Not Found
        server response:
        not found: grol.io/grol@v0.96.0: invalid version: git ls-remote -q https://github.com/grol-io/grol in /tmp/gopath/pkg/mod/cache/vcs/92cd9b71f1f14eb89ab4747e05dab68ada7779384ed7d986274d228500401def: exit status 128:
                fatal: unable to access 'https://github.com/grol-io/grol/': Failed to connect to github.com port 443: Connection refused
```

**Comment by findleyr** [comment]
CC @nicholashusin 

We're rolling out a change to the proxy today. Nicholas, can you see if this is related?

**Comment by nicholashusin** [comment]
This should be unrelated. The rollout has only recently started (by the time the comment was posted, I think basically no change has even made it to prod), and this particular module falls outside of the range of the change we're rolling out.

**Comment by findleyr** [comment]
Actually, this might be another clue: _until today_, our rollouts had been paused for a few weeks due to infrastructure changes and then the holiday freeze.

That's the same context that I discovered when this first happened. I wonder if there's some resource that gets depleted when our rollouts are paused (maybe an issue with egress from Google's infrastructure).

If that's the case, then the rollout that's happening now would *fix* the symptoms.

**Comment by ldemailly** [comment]
fixed now, thanks! (and hopefully fixed for everyone/good)
