### ISSUE TITLE
go/types: invalid memory address or nil pointer dereference on ppc64le

### ISSUE THREAD

**Issue by Rajalakshmi-Girish** [golang/go#76051]
### Go version

go1.26-devel_39fd61ddb0

### Output of `go env` in your module/workspace:

```shell
[root@raji-ws ~]# go env
AR='ar'
CC='gcc'
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_ENABLED='1'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
CXX='g++'
GCCGO='gccgo'
GO111MODULE=''
GOARCH='ppc64le'
GOAUTH='netrc'
GOBIN=''
GOCACHE='/root/.cache/go-build'
GOCACHEPROG=''
GODEBUG=''
GOENV='/root/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFIPS140='off'
GOFLAGS=''
GOGCCFLAGS='-fPIC -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build1568121291=/tmp/go-build -gno-record-gcc-switches'
GOHOSTARCH='ppc64le'
GOHOSTOS='linux'
GOINSECURE=''
GOMOD='/dev/null'
GOMODCACHE=''
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH=''
GOPPC64='power8'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/usr/local/go'
GOSUMDB='sum.golang.org'
GOTELEMETRY='local'
GOTELEMETRYDIR='/root/.config/go/telemetry'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/local/go/pkg/tool/linux_ppc64le'
GOVCS=''
GOVERSION='go1.26-devel_39fd61ddb0 Tue Oct 21 13:51:31 2025 -0700'
GOWORK=''
PKG_CONFIG='pkg-config'
[root@raji-ws ~]#
```

### What did you do?

Below k8s Unit tests are failing on ppc64le after https://github.com/golang/go/commit/39fd61ddb0b5987749979bc7e453cf2a575c9392 with `panic: runtime error: invalid memory address or nil pointer dereference` 
```
k8s.io/code-generator/cmd/client-gen
k8s.io/code-generator/cmd/client-gen/generators
k8s.io/code-generator/cmd/client-gen: types
k8s.io/code-generator/cmd/deepcopy-gen: generators
k8s.io/code-generator/cmd/go-to-protobuf: protobuf
k8s.io/code-generator/cmd/prerelease-lifecycle-gen: prerelease-lifecycle-generators
k8s.io/code-generator/cmd: validation-gen
k8s.io/code-generator/cmd/validation-gen: util
k8s.io/code-generator/cmd/validation-gen: validators
k8s.io/code-generator/pkg: util
k8s.io/kubernetes/cmd: import-boss
k8s.io/kubernetes/test: typecheck
```

### What did you see happen?
```
[root@raji-ws kubernetes]# go test k8s.io/code-generator/cmd/client-gen/args -race
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xeee28]

goroutine 1 [running]:
go/types.(*Named).setState(...)
        /usr/local/go/src/go/types/named.go:293
go/types.(*Named).unpack(0xc0001aa000)
        /usr/local/go/src/go/types/named.go:281 +0x490
go/types.(*Named).Underlying(0xc0001aa000)
        /usr/local/go/src/go/types/named.go:557 +0x3c
go/types.defPredeclaredTypes()
        /usr/local/go/src/go/types/universe.go:135 +0x1688
go/types.init.2()
        /usr/local/go/src/go/types/universe.go:278 +0x284
FAIL    k8s.io/code-generator/cmd/client-gen/args       0.015s
FAIL
[root@raji-ws kubernetes]# go test k8s.io/code-generator/cmd/client-gen/generators -race
?       k8s.io/code-generator/cmd/client-gen/generators [no test files]
[root@raji-ws kubernetes]# go test k8s.io/code-generator/cmd/client-gen/generators/util -race
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xeee38]

goroutine 1 [running]:
go/types.(*Named).setState(...)
        /usr/local/go/src/go/types/named.go:293
go/types.(*Named).unpack(0xc00022a000)
        /usr/local/go/src/go/types/named.go:281 +0x490
go/types.(*Named).Underlying(0xc00022a000)
        /usr/local/go/src/go/types/named.go:557 +0x3c
go/types.defPredeclaredTypes()
        /usr/local/go/src/go/types/universe.go:135 +0x1688
go/types.init.2()
        /usr/local/go/src/go/types/universe.go:278 +0x284
FAIL    k8s.io/code-generator/cmd/client-gen/generators/util    0.015s
FAIL
[root@raji-ws kubernetes]# go test k8s.io/code-generator/cmd/client-gen/types -race
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xee1b8]

goroutine 1 [running]:
go/types.(*Named).setState(...)
        /usr/local/go/src/go/types/named.go:293
go/types.(*Named).unpack(0xc000228000)
        /usr/local/go/src/go/types/named.go:281 +0x490
go/types.(*Named).Underlying(0xc000228000)
        /usr/local/go/src/go/types/named.go:557 +0x3c
go/types.defPredeclaredTypes()
        /usr/local/go/src/go/types/universe.go:135 +0x1688
go/types.init.2()
        /usr/local/go/src/go/types/universe.go:278 +0x284
FAIL    k8s.io/code-generator/cmd/client-gen/types      0.015s
FAIL
[root@raji-ws kubernetes]#
[root@raji-ws kubernetes]#  go test k8s.io/code-generator/cmd/deepcopy-gen/generators -race
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xef4a8]

goroutine 1 [running]:
go/types.(*Named).setState(...)
        /usr/local/go/src/go/types/named.go:293
go/types.(*Named).unpack(0xc0001ee000)
        /usr/local/go/src/go/types/named.go:281 +0x490
go/types.(*Named).Underlying(0xc0001ee000)
        /usr/local/go/src/go/types/named.go:557 +0x3c
go/types.defPredeclaredTypes()
        /usr/local/go/src/go/types/universe.go:135 +0x1688
go/types.init.2()
        /usr/local/go/src/go/types/universe.go:278 +0x284
FAIL    k8s.io/code-generator/cmd/deepcopy-gen/generators       0.016s
FAIL
[root@raji-ws kubernetes]# go test k8s.io/code-generator/cmd/go-to-protobuf/protobuf -race
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xeeed8]

goroutine 1 [running]:
go/types.(*Named).setState(...)
        /usr/local/go/src/go/types/named.go:293
go/types.(*Named).unpack(0xc0001aa000)
        /usr/local/go/src/go/types/named.go:281 +0x490
go/types.(*Named).Underlying(0xc0001aa000)
        /usr/local/go/src/go/types/named.go:557 +0x3c
go/types.defPredeclaredTypes()
        /usr/local/go/src/go/types/universe.go:135 +0x1688
go/types.init.2()
        /usr/local/go/src/go/types/universe.go:278 +0x284
FAIL    k8s.io/code-generator/cmd/go-to-protobuf/protobuf       0.016s
FAIL
[root@raji-ws kubernetes]# go version
go version go1.26-devel_7b506d106f Fri Oct 24 18:10:58 2025 -0700 linux/ppc64le
[root@raji-ws kubernetes]#
[root@raji-ws kubernetes]#  go test -race k8s.io/code-generator/cmd/prerelease-lifecycle-gen/prerelease-lifecycle-generators
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xf5718]

goroutine 1 [running]:
go/types.(*Named).setState(...)
        /usr/local/go/src/go/types/named.go:293
go/types.(*Named).unpack(0xc0001ae000)
        /usr/local/go/src/go/types/named.go:281 +0x490
go/types.(*Named).Underlying(0xc0001ae000)
        /usr/local/go/src/go/types/named.go:557 +0x3c
go/types.defPredeclaredTypes()
        /usr/local/go/src/go/types/universe.go:135 +0x1688
go/types.init.2()
        /usr/local/go/src/go/types/universe.go:278 +0x284
FAIL    k8s.io/code-generator/cmd/prerelease-lifecycle-gen/prerelease-lifecycle-generators      0.016s
FAIL
[root@raji-ws kubernetes]# go test -race k8s.io/code-generator/cmd/validation-gen
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xf27d8]

goroutine 1 [running]:
go/types.(*Named).setState(...)
        /usr/local/go/src/go/types/named.go:293
go/types.(*Named).unpack(0xc000202000)
        /usr/local/go/src/go/types/named.go:281 +0x490
go/types.(*Named).Underlying(0xc000202000)
        /usr/local/go/src/go/types/named.go:557 +0x3c
go/types.defPredeclaredTypes()
        /usr/local/go/src/go/types/universe.go:135 +0x1688
go/types.init.2()
        /usr/local/go/src/go/types/universe.go:278 +0x284
FAIL    k8s.io/code-generator/cmd/validation-gen        0.016s
FAIL
[root@raji-ws kubernetes]# go test -race k8s.io/api/extensions/v1beta1
ok      k8s.io/api/extensions/v1beta1   1.018s
[root@raji-ws kubernetes]# go test -race k8s.io/code-generator/cmd/validation-gen/util
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xee1b8]

goroutine 1 [running]:
go/types.(*Named).setState(...)
        /usr/local/go/src/go/types/named.go:293
go/types.(*Named).unpack(0xc0001a8000)
        /usr/local/go/src/go/types/named.go:281 +0x490
go/types.(*Named).Underlying(0xc0001a8000)
        /usr/local/go/src/go/types/named.go:557 +0x3c
go/types.defPredeclaredTypes()
        /usr/local/go/src/go/types/universe.go:135 +0x1688
go/types.init.2()
        /usr/local/go/src/go/types/universe.go:278 +0x284
FAIL    k8s.io/code-generator/cmd/validation-gen/util   0.015s
FAIL
[root@raji-ws kubernetes]#
[root@raji-ws kubernetes]# go test -race k8s.io/code-generator/cmd/validation-gen/validators
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xf27d8]

goroutine 1 [running]:
go/types.(*Named).setState(...)
        /usr/local/go/src/go/types/named.go:293
go/types.(*Named).unpack(0xc0001fa000)
        /usr/local/go/src/go/types/named.go:281 +0x490
go/types.(*Named).Underlying(0xc0001fa000)
        /usr/local/go/src/go/types/named.go:557 +0x3c
go/types.defPredeclaredTypes()
        /usr/local/go/src/go/types/universe.go:135 +0x1688
go/types.init.2()
        /usr/local/go/src/go/types/universe.go:278 +0x284
FAIL    k8s.io/code-generator/cmd/validation-gen/validators     0.016s
FAIL
[root@raji-ws kubernetes]# go test -race k8s.io/code-generator/pkg/util
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xf5678]

goroutine 1 [running]:
go/types.(*Named).setState(...)
        /usr/local/go/src/go/types/named.go:293
go/types.(*Named).unpack(0xc0001f4000)
        /usr/local/go/src/go/types/named.go:281 +0x490
go/types.(*Named).Underlying(0xc0001f4000)
        /usr/local/go/src/go/types/named.go:557 +0x3c
go/types.defPredeclaredTypes()
        /usr/local/go/src/go/types/universe.go:135 +0x1688
go/types.init.2()
        /usr/local/go/src/go/types/universe.go:278 +0x284
FAIL    k8s.io/code-generator/pkg/util  0.017s
FAIL
[root@raji-ws kubernetes]# go test -race k8s.io/kubernetes/cmd/import-boss
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xf0228]

goroutine 1 [running]:
go/types.(*Named).setState(...)
        /usr/local/go/src/go/types/named.go:293
go/types.(*Named).unpack(0xc0001aa000)
        /usr/local/go/src/go/types/named.go:281 +0x490
go/types.(*Named).Underlying(0xc0001aa000)
        /usr/local/go/src/go/types/named.go:557 +0x3c
go/types.defPredeclaredTypes()
        /usr/local/go/src/go/types/universe.go:135 +0x1688
go/types.init.2()
        /usr/local/go/src/go/types/universe.go:278 +0x284
FAIL    k8s.io/kubernetes/cmd/import-boss       0.016s
FAIL
[root@raji-ws kubernetes]#
[root@raji-ws kubernetes]# go test -race k8s.io/kubernetes/test/typecheck
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xef648]

goroutine 1 [running]:
go/types.(*Named).setState(...)
        /usr/local/go/src/go/types/named.go:293
go/types.(*Named).unpack(0xc000170000)
        /usr/local/go/src/go/types/named.go:281 +0x490
go/types.(*Named).Underlying(0xc000170000)
        /usr/local/go/src/go/types/named.go:557 +0x3c
go/types.defPredeclaredTypes()
        /usr/local/go/src/go/types/universe.go:135 +0x1688
go/types.init.2()
        /usr/local/go/src/go/types/universe.go:278 +0x284
FAIL    k8s.io/kubernetes/test/typecheck        0.015s
FAIL
[root@raji-ws kubernetes]#
```

### What did you expect to see?

The tests have to PASS.

**Comment by seankhliao** [comment]
we need a better bug report.
both the code and the actual panic output.

**Comment by jkrishmys** [comment]
@seankhliao
go test -race k8s.io/kubernetes/test/typecheck
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xef9d8]

goroutine 1 [running]:
go/types.(*Named).setState(...)
/usr/local/go/src/go/types/named.go:292
go/types.(*Named).resolve(0xc0001f0000)
/usr/local/go/src/go/types/named.go:280 +0x490
go/types.(*Named).Underlying(0xc0001f0000)
/usr/local/go/src/go/types/named.go:556 +0x3c
go/types.defPredeclaredTypes()
/usr/local/go/src/go/types/universe.go:135 +0x1688
go/types.init.2()
/usr/local/go/src/go/types/universe.go:278 +0x284
FAIL    k8s.io/kubernetes/test/typecheck        0.017s
FAIL

After commit 39fd61ddb0b5987749979bc7e453cf2a575c9392 ([CL 712720](https://go.dev/cl/712720): “go/types, types2: guard Named.underlying with Named.mu”), running go test -race confirms concurrent access to (*Named).underlying and state_ between under() and resolve() / SetUnderlying().

This appears to occur because under() still writes:
t.underlying = u
t.setState(underlying)

for all entries in seen without holding each t.mu.
These pointer writes race with other goroutines reading or updating underlying, and the subsequent atomic.OrUint32 in setState can observe partially initialized memory.

**This failure reproduces consistently on Power (ppc64le) but not on x86 (amd64).**
On  architectures like Power, memory writes are not guaranteed to be visible to other goroutines without explicit synchronization (e.g. a mutex or happens-before edge), as a result, the “underlying” bit in state_ may become visible before the corresponding pointer write, leading to a nil-pointer dereference or data-race detection.

I believe a  fix would be to guard each assignment in under() with t.mu, or move this logic into a helper that applies double-checked locking to synchronize both underlying and state_ updates.

**Comment by Rajalakshmi-Girish** [comment]
> we need a better bug report. both the code and the actual panic output.

I now added the stacktrace to bug description.

**Comment by randall77** [comment]
@mrkfrmn

**Comment by adonovan** [comment]
Possible dup of the locking problem that was either introduced or fixed in https://go.dev/cl/713521. (I can't find an issue number for that stack of go/types CLs).

**Comment by mrkfrmn** [comment]
Quite likely this is the same root cause as 75963 which was tripping up our race builders briefly — this should be fixed past CL cf826bfcb494a7dba5451bd7e4432f150590b19e.

@Rajalakshmi-Girish @jkrishmys can you confirm if this reproduces past there?

**Comment by jkrishmys** [comment]
> Quite likely this is the same root cause as 75963 which was tripping up our race builders briefly — this should be fixed past CL [cf826bf](https://github.com/golang/go/commit/cf826bfcb494a7dba5451bd7e4432f150590b19e).
> 
> [@Rajalakshmi-Girish](https://github.com/Rajalakshmi-Girish) [@jkrishmys](https://github.com/jkrishmys) can you confirm if this reproduces past there?

Thanks, we will confirm.

**Comment by Rajalakshmi-Girish** [comment]
> @Rajalakshmi-Girish @jkrishmys can you confirm if this reproduces past there?

@mrkfrmn Yes it is still reproducible on `go version go1.26-devel_041f564b3e Tue Oct 28 13:58:12 2025 -0700 linux/ppc64le`

```
[root@alpha-enabled-1761677903-worker-0 kubernetes]# go test k8s.io/code-generator/cmd/client-gen/args -race
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xeef18]

goroutine 1 [running]:
go/types.(*Named).setState(...)
        /usr/local/go/src/go/types/named.go:293
go/types.(*Named).unpack(0xc000150000)
        /usr/local/go/src/go/types/named.go:281 +0x490
go/types.(*Named).Underlying(0xc000150000)
        /usr/local/go/src/go/types/named.go:584 +0x3c
go/types.defPredeclaredTypes()
        /usr/local/go/src/go/types/universe.go:135 +0x1688
go/types.init.2()
        /usr/local/go/src/go/types/universe.go:278 +0x284
FAIL    k8s.io/code-generator/cmd/client-gen/args       0.014s
FAIL
[root@alpha-enabled-1761677903-worker-0 kubernetes]#  go version
go version go1.26-devel_041f564b3e Tue Oct 28 13:58:12 2025 -0700 linux/ppc64le
[root@alpha-enabled-1761677903-worker-0 kubernetes]#

```

**Comment by jkrishmys** [comment]
@mrkfrmn. Thanks for the CL update.  After verifying with Go commit (go1.26-devel_cf826bfcb4), the original concurrency **_**issue in go/types.(*Named).resolveUnderlying appears fixed**_** — there is no panic without **-race** on ppc64le.

However, when running with the race detector, reproducible crashes persist during Go’s universe initialization (defPredeclaredTypes) as reported above by @Rajalakshmi-Girish . So, Without **-race:** All tests (k8s.io/code-generator/cmd/client-gen/args, test/typecheck) pass cleanly. With **-race:** Crashes reproducibly even with GOMAXPROCS=1, so it is not a data race. 

Just to ensure did a small test with this code 

> package repro
> import _ "go/types"
> import "testing"
> func TestNoop(t *testing.T) {}

`go test -race -count=1 -v `  with **-race**

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xedbf8]

goroutine 1 [running]:
go/types.(*Named).setState(...)
	/home/jkrishna/godevel/go/src/go/types/named.go:292
go/types.(*Named).resolve(0xc000378000)
	/home/jkrishna/godevel/go/src/go/types/named.go:280 +0x490
go/types.(*Named).Underlying(0xc000378000)
	/home/jkrishna/godevel/go/src/go/types/named.go:556 +0x3c
go/types.defPredeclaredTypes()
	/home/jkrishna/godevel/go/src/go/types/universe.go:135 +0x1688
go/types.init.2()
	/home/jkrishna/godevel/go/src/go/types/universe.go:278 +0x284
exit status 2
FAIL	test	0.019s

and without **-race**

`go test  -count=1 -v`

> === RUN   TestNoop
> --- PASS: TestNoop (0.00s)

**Comment by jkrishmys** [comment]
is it because,  in ppc64 race instrumentation  is happening  before runtime is fully bootstrapped?. Will explore.

**Comment by jkrishmys** [comment]
I guess what we are seeing is due to the following code in **race_ppc64le.s** which  is triggering SIGSEGV early,  if address passed  is bad.   So by carefully preventing  early-race probe in racecallatomic on ppc64le  we may mitigate this.  
          



> // Common function used to call tsan's atomic functions                                                                                                                                             
> // R3 = *ThreadState                                                                                                                                                                                
> // R4 = TODO: What's this supposed to be?                                                                                                                                                           
> // R5 = caller pc                                                                                                                                                                                   
> // R6 = addr of incoming arg list                                                                                                                                                                   
> // R8 contains addr of target function.                                                                                                                                                             
> TEXT    racecallatomic<>(SB), NOSPLIT, $0-0
>         // Trigger SIGSEGV early if address passed to atomic function is bad.                                                                                                                       
> 	MOVD    (R6), R7        // 1st arg is addr                                                                                                                                                  
>         MOVB    (R7), R9        // segv here if addr is bad                                                                                                                                         
>         // Check that addr is within [arenastart, arenaend) or within [racedatastart, racedataend). 
>

**Comment by jkrishmys** [comment]
The Power-specific race runtime (racecallatomic) currently dereferences the first argument ((R6) → R7 → (R7)) to intentionally trigger a SIGSEGV early if the address is invalid. However, this occurs before the runtime and memory arenas are fully initialized, which can lead to a spurious fault during race-instrumented builds on Power.

The patch I am working on will mitigate this  by preventing early probe dereference for un-initialized addresses, ensuring stable and correct behavior during runtime bootstrap.

**Comment by Mizommz** [comment]
#76051

**Comment by jkrishmys** [comment]
@mrkfrmn,  can this fix [718560](https://go-review.googlesource.com/c/go/+/718560) for the above be merged  upstream. Thank in advance.

**Comment by mkumatag** [comment]
can we back port this to older releases?

**Comment by jkrishmys** [comment]
@gopherbot please backport this [44cb824](https://github.com/golang/go/commit/44cb82449e7f24530fe0fe0bf8261ba9e0e4e7d8) to Go 1.25. This is a correctness fix for ppc64x under -race and is needed for stable race-enabled builds on this architecture.

**Comment by dmitshur** [comment]
The original report said that tests started to fail after [go.dev/cl/712720](https://go.dev/cl/712720), which is new to 1.26, so does this apply to older releases? If so, is it only 1.25 that needs this fix, or both 1.24 and 1.25?

**Comment by mkumatag** [comment]
> The original report said that tests started to fail after [go.dev/cl/712720](https://go.dev/cl/712720), which is new to 1.26, so does this apply to older releases? If so, is it only 1.25 that needs this fix, or both 1.24 and 1.25?

@Rajalakshmi-Girish can you please if this is happening with older releases(1.25, 1.24 etc..) as well?

**Comment by Rajalakshmi-Girish** [comment]
The test `kubernetes/pkg/controller/devicetainteviction: TestController` is failing when golang 1.25.5 and 1.24.11 are used with below error, **but PASSES when golang matser is used.**

```
unexpected fault address 0x41ee12
fatal error: fault
[signal SIGBUS: bus error code=0x1 addr=0x41ee12 pc=0x4da8c]

goroutine 90 gp=0xc0003001c0 m=29 mp=0xc001280808 [running (durable), synctest bubble 1]:
runtime.throw({0x7fff33ffe200?, 0x0?})
        /root/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.25.0.linux-ppc64le/src/runtime/panic.go:1094 +0x34 fp=0x7fff33ffe240 sp=0x7fff33ffe200 pc=0xed874
runtime: g 90: unexpected return pc for runtime.throw called from 0x314cb82
stack: frame={sp:0x7fff33ffe200, fp:0x7fff33ffe240} stack=[0xc0010a2000,0xc0010b2000)
```

[testgo1.25.log](https://github.com/user-attachments/files/24096974/testgo1.25.log)
[testgomaster.log](https://github.com/user-attachments/files/24096975/testgomaster.log)
[testgo1.24.log](https://github.com/user-attachments/files/24096976/testgo1.24.log)

Hence back porting is needed for both 1.25 and 1.24
@dmitshur @jkrishmys

**Comment by jkrishmys** [comment]
> The test `kubernetes/pkg/controller/devicetainteviction: TestController` is failing when golang 1.25.5 and 1.24.11 are used with below error, **but PASSES when golang matser is used.**
> 
> ```
> unexpected fault address 0x41ee12
> fatal error: fault
> [signal SIGBUS: bus error code=0x1 addr=0x41ee12 pc=0x4da8c]
> 
> goroutine 90 gp=0xc0003001c0 m=29 mp=0xc001280808 [running (durable), synctest bubble 1]:
> runtime.throw({0x7fff33ffe200?, 0x0?})
>         /root/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.25.0.linux-ppc64le/src/runtime/panic.go:1094 +0x34 fp=0x7fff33ffe240 sp=0x7fff33ffe200 pc=0xed874
> runtime: g 90: unexpected return pc for runtime.throw called from 0x314cb82
> stack: frame={sp:0x7fff33ffe200, fp:0x7fff33ffe240} stack=[0xc0010a2000,0xc0010b2000)
> ```
> 
> [testgo1.25.log](https://github.com/user-attachments/files/24096974/testgo1.25.log) [testgomaster.log](https://github.com/user-attachments/files/24096975/testgomaster.log) [testgo1.24.log](https://github.com/user-attachments/files/24096976/testgo1.24.log)
> 
> Hence back porting is needed for both 1.25 and 1.24 [@dmitshur](https://github.com/dmitshur) [@jkrishmys](https://github.com/jkrishmys)

@dmitshur, we require back porting for both 1.25 and 1.24. Thanks for checking with us.

**Comment by dr2chase** [comment]
@gopherbot, please backport to Go 1.24.
