### ISSUE TITLE
cmd/dist: runs simd/archsimd tests on unsupported cpus

### ISSUE THREAD

**Issue by JetSetIlly** [golang/go#76866]
I'm building Go1.26rc1 from source (all.bash)

The testing phase fails with the SIMD test.

```
##### GOEXPERIMENT=simd go test simd/archsimd/...
ok  	simd/archsimd	0.096s
SIGILL: illegal instruction
PC=0x548760 m=2 sigcode=2
instruction bytes: 0xc5 0xfd 0xfd 0xc1 0xc3 0xcc 0xcc 0xcc 0xcc 0xcc 0xcc 0xcc 0xcc 0xcc 0xcc 0xcc
```

I have an older amd64 CPU (i3-3225) which has limited SIMD instructions.

With regards to testing, all tests following this failure are "skipped due to earlier error"

Should GOEXPERIMENT tests be an automatic part of the test suite? (I hadn't specified any GOEXPERIMENTs)

<details>
<summary>Full output of all.bash from simd test onwards</summary>

```
##### GOEXPERIMENT=simd go test simd/archsimd/...
ok  	simd/archsimd	0.096s
SIGILL: illegal instruction
PC=0x548760 m=2 sigcode=2
instruction bytes: 0xc5 0xfd 0xfd 0xc1 0xc3 0xcc 0xcc 0xcc 0xcc 0xcc 0xcc 0xcc 0xcc 0xcc 0xcc 0xcc

goroutine 17 gp=0x33b50d26d20 m=2 mp=0x33b508d8808 [running]:
simd/archsimd.Int16x16.Add(0x0?, 0x497912?)
	/home/steve/Go/1.26.0.rc1/go/src/simd/archsimd/ops_amd64.go:252 fp=0x33b50989d80 sp=0x33b50989d78 pc=0x548760
simd/archsimd/internal/simd_test_test.testInt16x16Binary.func1({0x33b509be000, 0x10, 0x90}, {0x33b509be000, 0x10, 0x90})
	/home/steve/Go/1.26.0.rc1/go/src/simd/archsimd/internal/simd_test/binary_helpers_test.go:190 +0xf6 fp=0x33b50989e80 sp=0x33b50989d80 pc=0x5615b6
simd/archsimd/internal/simd_test_test.forSlicePair[...](0x64b1d0?, {0x33b509be000?, 0x90, 0x90}, 0x10, 0x33b50989f10)
	/home/steve/Go/1.26.0.rc1/go/src/simd/archsimd/internal/simd_test/helpers_test.go:206 +0x12c fp=0x33b50989ed8 sp=0x33b50989e80 pc=0x59db4c
simd/archsimd/internal/simd_test_test.testInt16x16Binary(0x33b509ba248, 0x614258, 0x614dc8)
	/home/steve/Go/1.26.0.rc1/go/src/simd/archsimd/internal/simd_test/binary_helpers_test.go:185 +0x8d fp=0x33b50989f48 sp=0x33b50989ed8 pc=0x56148d
simd/archsimd/internal/simd_test_test.TestAdd(0x33b509ba248)
	/home/steve/Go/1.26.0.rc1/go/src/simd/archsimd/internal/simd_test/binary_test.go:20 +0x8d fp=0x33b50989f70 sp=0x33b50989f48 pc=0x5665cd
testing.tRunner(0x33b509ba248, 0x613b18)
	/home/steve/Go/1.26.0.rc1/go/src/testing/testing.go:2036 +0xea fp=0x33b50989fc0 sp=0x33b50989f70 pc=0x503daa
testing.(*T).Run.gowrap1()
	/home/steve/Go/1.26.0.rc1/go/src/testing/testing.go:2101 +0x1b fp=0x33b50989fe0 sp=0x33b50989fc0 pc=0x504f5b
runtime.goexit({})
	/home/steve/Go/1.26.0.rc1/go/src/runtime/asm_amd64.s:1771 +0x1 fp=0x33b50989fe8 sp=0x33b50989fe0 pc=0x499381
created by testing.(*T).Run in goroutine 1
	/home/steve/Go/1.26.0.rc1/go/src/testing/testing.go:2101 +0x4dd

goroutine 1 gp=0x33b5088a1e0 m=nil [chan receive]:
runtime.gopark(0x7f7a8cf85420?, 0x7f7a8cf7dbf0?, 0x80?, 0x50?, 0x5c8ca0?)
	/home/steve/Go/1.26.0.rc1/go/src/runtime/proc.go:462 +0xce fp=0x33b5098a940 sp=0x33b5098a920 pc=0x49272e
runtime.chanrecv(0x33b509b6080, 0x33b5098aa27, 0x1)
	/home/steve/Go/1.26.0.rc1/go/src/runtime/chan.go:667 +0x4ae fp=0x33b5098a9b8 sp=0x33b5098a940 pc=0x416cee
runtime.chanrecv1(0x18?, 0x5e6620?)
	/home/steve/Go/1.26.0.rc1/go/src/runtime/chan.go:509 +0x12 fp=0x33b5098a9e0 sp=0x33b5098a9b8 pc=0x416832
testing.(*T).Run(0x33b509ba008, {0x604cf7?, 0x33b5098aad8?}, 0x613b18)
	/home/steve/Go/1.26.0.rc1/go/src/testing/testing.go:2109 +0x4fb fp=0x33b5098aab8 sp=0x33b5098a9e0 pc=0x504ddb
testing.runTests.func1(0x33b509ba008)
	/home/steve/Go/1.26.0.rc1/go/src/testing/testing.go:2585 +0x37 fp=0x33b5098aaf8 sp=0x33b5098aab8 pc=0x5071b7
testing.tRunner(0x33b509ba008, 0x33b5098ac00)
	/home/steve/Go/1.26.0.rc1/go/src/testing/testing.go:2036 +0xea fp=0x33b5098ab48 sp=0x33b5098aaf8 pc=0x503daa
testing.runTests({0x0, 0x0}, {0x60cc3b, 0x20}, 0x33b50896060, {0x7c02c0, 0x74, 0x74}, {0xc24890f846dbb49e, 0x8c25585b26, ...})
	/home/steve/Go/1.26.0.rc1/go/src/testing/testing.go:2583 +0x510 fp=0x33b5098ac30 sp=0x33b5098ab48 pc=0x507070
testing.(*M).Run(0x33b5098e140)
	/home/steve/Go/1.26.0.rc1/go/src/testing/testing.go:2443 +0x6b8 fp=0x33b5098ae70 sp=0x33b5098ac30 pc=0x5059f8
simd/archsimd/internal/simd_test_test.TestMain(0x7e5c80?)
	/home/steve/Go/1.26.0.rc1/go/src/simd/archsimd/internal/simd_test/simd_test.go:23 +0x65 fp=0x33b5098aeb8 sp=0x33b5098ae70 pc=0x571765
main.main()
	_testmain.go:296 +0xa5 fp=0x33b5098af48 sp=0x33b5098aeb8 pc=0x5a4685
runtime.main()
	/home/steve/Go/1.26.0.rc1/go/src/runtime/proc.go:290 +0x2d5 fp=0x33b5098afe0 sp=0x33b5098af48 pc=0x45d9f5
runtime.goexit({})
	/home/steve/Go/1.26.0.rc1/go/src/runtime/asm_amd64.s:1771 +0x1 fp=0x33b5098afe8 sp=0x33b5098afe0 pc=0x499381

goroutine 2 gp=0x33b5088a780 m=nil [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/home/steve/Go/1.26.0.rc1/go/src/runtime/proc.go:462 +0xce fp=0x33b508d4fa8 sp=0x33b508d4f88 pc=0x49272e
runtime.goparkunlock(...)
	/home/steve/Go/1.26.0.rc1/go/src/runtime/proc.go:468
runtime.forcegchelper()
	/home/steve/Go/1.26.0.rc1/go/src/runtime/proc.go:375 +0xb3 fp=0x33b508d4fe0 sp=0x33b508d4fa8 pc=0x45dd13
runtime.goexit({})
	/home/steve/Go/1.26.0.rc1/go/src/runtime/asm_amd64.s:1771 +0x1 fp=0x33b508d4fe8 sp=0x33b508d4fe0 pc=0x499381
created by runtime.init.7 in goroutine 1
	/home/steve/Go/1.26.0.rc1/go/src/runtime/proc.go:363 +0x1a

goroutine 3 gp=0x33b5088ad20 m=nil [GC sweep wait]:
runtime.gopark(0x1?, 0x0?, 0x0?, 0x0?, 0x0?)
	/home/steve/Go/1.26.0.rc1/go/src/runtime/proc.go:462 +0xce fp=0x33b508d5788 sp=0x33b508d5768 pc=0x49272e
runtime.goparkunlock(...)
	/home/steve/Go/1.26.0.rc1/go/src/runtime/proc.go:468
runtime.bgsweep(0x33b508f4000)
	/home/steve/Go/1.26.0.rc1/go/src/runtime/mgcsweep.go:324 +0x151 fp=0x33b508d57c8 sp=0x33b508d5788 pc=0x445cf1
runtime.gcenable.gowrap1()
	/home/steve/Go/1.26.0.rc1/go/src/runtime/mgc.go:214 +0x17 fp=0x33b508d57e0 sp=0x33b508d57c8 pc=0x437097
runtime.goexit({})
	/home/steve/Go/1.26.0.rc1/go/src/runtime/asm_amd64.s:1771 +0x1 fp=0x33b508d57e8 sp=0x33b508d57e0 pc=0x499381
created by runtime.gcenable in goroutine 1
	/home/steve/Go/1.26.0.rc1/go/src/runtime/mgc.go:214 +0x66

goroutine 4 gp=0x33b5088af00 m=nil [GC scavenge wait]:
runtime.gopark(0x10000?, 0x615bc8?, 0x0?, 0x0?, 0x0?)
	/home/steve/Go/1.26.0.rc1/go/src/runtime/proc.go:462 +0xce fp=0x33b508d5f78 sp=0x33b508d5f58 pc=0x49272e
runtime.goparkunlock(...)
	/home/steve/Go/1.26.0.rc1/go/src/runtime/proc.go:468
runtime.(*scavengerState).park(0x7c5c00)
	/home/steve/Go/1.26.0.rc1/go/src/runtime/mgcscavenge.go:425 +0x49 fp=0x33b508d5fa8 sp=0x33b508d5f78 pc=0x443769
runtime.bgscavenge(0x33b508f4000)
	/home/steve/Go/1.26.0.rc1/go/src/runtime/mgcscavenge.go:658 +0x59 fp=0x33b508d5fc8 sp=0x33b508d5fa8 pc=0x443cf9
runtime.gcenable.gowrap2()
	/home/steve/Go/1.26.0.rc1/go/src/runtime/mgc.go:215 +0x17 fp=0x33b508d5fe0 sp=0x33b508d5fc8 pc=0x437057
runtime.goexit({})
	/home/steve/Go/1.26.0.rc1/go/src/runtime/asm_amd64.s:1771 +0x1 fp=0x33b508d5fe8 sp=0x33b508d5fe0 pc=0x499381
created by runtime.gcenable in goroutine 1
	/home/steve/Go/1.26.0.rc1/go/src/runtime/mgc.go:215 +0xa5

goroutine 5 gp=0x33b5088b4a0 m=nil [GOMAXPROCS updater (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/home/steve/Go/1.26.0.rc1/go/src/runtime/proc.go:462 +0xce fp=0x33b508d6788 sp=0x33b508d6768 pc=0x49272e
runtime.goparkunlock(...)
	/home/steve/Go/1.26.0.rc1/go/src/runtime/proc.go:468
runtime.updateMaxProcsGoroutine()
	/home/steve/Go/1.26.0.rc1/go/src/runtime/proc.go:7087 +0xe7 fp=0x33b508d67e0 sp=0x33b508d6788 pc=0x46c1e7
runtime.goexit({})
	/home/steve/Go/1.26.0.rc1/go/src/runtime/asm_amd64.s:1771 +0x1 fp=0x33b508d67e8 sp=0x33b508d67e0 pc=0x499381
created by runtime.defaultGOMAXPROCSUpdateEnable in goroutine 1
	/home/steve/Go/1.26.0.rc1/go/src/runtime/proc.go:7075 +0x37

goroutine 6 gp=0x33b5088b680 m=nil [finalizer wait]:
runtime.gopark(0x46d235?, 0x442c7c?, 0x80?, 0x6d?, 0x480013?)
	/home/steve/Go/1.26.0.rc1/go/src/runtime/proc.go:462 +0xce fp=0x33b508d4620 sp=0x33b508d4600 pc=0x49272e
runtime.runFinalizers()
	/home/steve/Go/1.26.0.rc1/go/src/runtime/mfinal.go:210 +0x107 fp=0x33b508d47e0 sp=0x33b508d4620 pc=0x4360a7
runtime.goexit({})
	/home/steve/Go/1.26.0.rc1/go/src/runtime/asm_amd64.s:1771 +0x1 fp=0x33b508d47e8 sp=0x33b508d47e0 pc=0x499381
created by runtime.createfing in goroutine 1
	/home/steve/Go/1.26.0.rc1/go/src/runtime/mfinal.go:172 +0x3d

goroutine 7 gp=0x33b5088b860 m=nil [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/home/steve/Go/1.26.0.rc1/go/src/runtime/proc.go:462 +0xce fp=0x33b508d6f40 sp=0x33b508d6f20 pc=0x49272e
runtime.gcBgMarkWorker(0x33b50984150)
	/home/steve/Go/1.26.0.rc1/go/src/runtime/mgc.go:1791 +0xeb fp=0x33b508d6fc8 sp=0x33b508d6f40 pc=0x439b6b
runtime.gcBgMarkStartWorkers.gowrap1()
	/home/steve/Go/1.26.0.rc1/go/src/runtime/mgc.go:1695 +0x17 fp=0x33b508d6fe0 sp=0x33b508d6fc8 pc=0x439a57
runtime.goexit({})
	/home/steve/Go/1.26.0.rc1/go/src/runtime/asm_amd64.s:1771 +0x1 fp=0x33b508d6fe8 sp=0x33b508d6fe0 pc=0x499381
created by runtime.gcBgMarkStartWorkers in goroutine 1
	/home/steve/Go/1.26.0.rc1/go/src/runtime/mgc.go:1695 +0x105

goroutine 8 gp=0x33b50d26000 m=nil [GC worker (idle)]:
runtime.gopark(0x13c8bcf6da0b?, 0x0?, 0x0?, 0x0?, 0x0?)
	/home/steve/Go/1.26.0.rc1/go/src/runtime/proc.go:462 +0xce fp=0x33b508d7740 sp=0x33b508d7720 pc=0x49272e
runtime.gcBgMarkWorker(0x33b50984150)
	/home/steve/Go/1.26.0.rc1/go/src/runtime/mgc.go:1791 +0xeb fp=0x33b508d77c8 sp=0x33b508d7740 pc=0x439b6b
runtime.gcBgMarkStartWorkers.gowrap1()
	/home/steve/Go/1.26.0.rc1/go/src/runtime/mgc.go:1695 +0x17 fp=0x33b508d77e0 sp=0x33b508d77c8 pc=0x439a57
runtime.goexit({})
	/home/steve/Go/1.26.0.rc1/go/src/runtime/asm_amd64.s:1771 +0x1 fp=0x33b508d77e8 sp=0x33b508d77e0 pc=0x499381
created by runtime.gcBgMarkStartWorkers in goroutine 1
	/home/steve/Go/1.26.0.rc1/go/src/runtime/mgc.go:1695 +0x105

goroutine 9 gp=0x33b50d265a0 m=nil [GC worker (idle)]:
runtime.gopark(0x13c870336995?, 0x0?, 0x0?, 0x0?, 0x0?)
	/home/steve/Go/1.26.0.rc1/go/src/runtime/proc.go:462 +0xce fp=0x33b508d7f40 sp=0x33b508d7f20 pc=0x49272e
runtime.gcBgMarkWorker(0x33b50984150)
	/home/steve/Go/1.26.0.rc1/go/src/runtime/mgc.go:1791 +0xeb fp=0x33b508d7fc8 sp=0x33b508d7f40 pc=0x439b6b
runtime.gcBgMarkStartWorkers.gowrap1()
	/home/steve/Go/1.26.0.rc1/go/src/runtime/mgc.go:1695 +0x17 fp=0x33b508d7fe0 sp=0x33b508d7fc8 pc=0x439a57
runtime.goexit({})
	/home/steve/Go/1.26.0.rc1/go/src/runtime/asm_amd64.s:1771 +0x1 fp=0x33b508d7fe8 sp=0x33b508d7fe0 pc=0x499381
created by runtime.gcBgMarkStartWorkers in goroutine 1
	/home/steve/Go/1.26.0.rc1/go/src/runtime/mgc.go:1695 +0x105

goroutine 10 gp=0x33b50d26b40 m=nil [GC worker (idle)]:
runtime.gopark(0x13c8bcf618c2?, 0x33b509fe600?, 0x1c?, 0xa?, 0x0?)
	/home/steve/Go/1.26.0.rc1/go/src/runtime/proc.go:462 +0xce fp=0x33b508d0740 sp=0x33b508d0720 pc=0x49272e
runtime.gcBgMarkWorker(0x33b50984150)
	/home/steve/Go/1.26.0.rc1/go/src/runtime/mgc.go:1791 +0xeb fp=0x33b508d07c8 sp=0x33b508d0740 pc=0x439b6b
runtime.gcBgMarkStartWorkers.gowrap1()
	/home/steve/Go/1.26.0.rc1/go/src/runtime/mgc.go:1695 +0x17 fp=0x33b508d07e0 sp=0x33b508d07c8 pc=0x439a57
runtime.goexit({})
	/home/steve/Go/1.26.0.rc1/go/src/runtime/asm_amd64.s:1771 +0x1 fp=0x33b508d07e8 sp=0x33b508d07e0 pc=0x499381
created by runtime.gcBgMarkStartWorkers in goroutine 1
	/home/steve/Go/1.26.0.rc1/go/src/runtime/mgc.go:1695 +0x105

rax    0x33bb2864480
rbx    0x5c8d60
rcx    0x0
rdx    0x614258
rdi    0x0
rsi    0x548760
rbp    0x33b50989e70
rsp    0x33b50989d78
r8     0x25
r9     0x25
r10    0xffffffffffffffff
r11    0x1
r12    0x33bb2864480
r13    0x33b509b86c0
r14    0x33b50d26d20
r15    0x2
rip    0x548760
rflags 0x10212
cs     0x33
fs     0x0
gs     0x0
FAIL	simd/archsimd/internal/simd_test	2.241s
?   	simd/archsimd/internal/test_helpers	[no test files]
FAIL
2025/12/16 21:07:40 Failed: exit status 1

##### Testing without libgcc.
ok  	net	0.044s
ok  	os/user	0.014s

##### internal linking, -buildmode=pie
ok  	reflect	0.204s
skipped due to earlier error
skipped due to earlier error

##### external linking, -buildmode=exe
skipped due to earlier error

##### external linking, -buildmode=pie
skipped due to earlier error

##### sync -cpu=10
skipped due to earlier error

##### Testing cgo
skipped due to earlier error
skipped due to earlier error
skipped due to earlier error
skipped due to earlier error
skipped due to earlier error
skipped due to earlier error
skipped due to earlier error
skipped due to earlier error
skipped due to earlier error
skipped due to earlier error
skipped due to earlier error
skipped due to earlier error

##### API release note check
skipped due to earlier error

##### API check
skipped due to earlier error

##### GOMAXPROCS=2 runtime -cpu=1 -quick
skipped due to earlier error

##### GOMAXPROCS=2 runtime -cpu=2 -quick
skipped due to earlier error

##### GOMAXPROCS=2 runtime -cpu=4 -quick
skipped due to earlier error

##### Testing race detector
skipped due to earlier error
skipped due to earlier error
skipped due to earlier error
skipped due to earlier error
skipped due to earlier error
skipped due to earlier error
skipped due to earlier error
skipped due to earlier error
```

</details>

**Comment by mknyszek** [comment]
CC @cherrymui @dr2chase @JunyangShao

**Comment by mknyszek** [comment]
I don't think this is a release blocker since the tests are mostly for the Go team itself, but this should probably be fixed before release.

I guess there's a missing feature flag check, or the CPU you're running falls in some gap that the current feature flags miss. The `SIGILL` is pretty clear.

**Comment by cherrymui** [comment]
@dr2chase we should guard the tests like `testInt16x16Binary` with AVX2 check.

It seems the tests have guards of AVX512, and a global check for  AVX1, but not AVX2 in all places. We should fix that. Thanks.

**Comment by JetSetIlly** [comment]
> I don't think this is a release blocker since the tests are mostly for the Go team itself, but this should probably be fixed before release.
> 
> I guess there's a missing feature flag check, or the CPU you're running falls in some gap that the current feature flags miss. The `SIGILL` is pretty clear.

I agree that the cause of the problem is clear and that the test failures are not a show-stopper. I've commented out the SIMD test in the dist cmd and now the release passes all other tests .

It also seems it's not just my specific CPU model. This golang-nuts discussion https://groups.google.com/g/golang-nuts/c/0HPyP7l0Pak has a reply which shows a different amd64 CPU has a similar test failure. In that case the Intel Ultra7 has AVX2 but not AVX512

**Comment by mpx** [comment]
CPU: Intel(R) Core(TM) Ultra 7 258V

FYI, I cherrypick'd https://go.dev/cl/730941/1 on top of go1.26rc1 and it still fails for me:

This line in `TestDotProductQuadruple`:
```
	x.DotProductQuadruple(y).Add(z).StoreSlice(res1)
```

```
##### GOEXPERIMENT=simd go test simd/archsimd/...
ok  	simd/archsimd	0.035s
SIGILL: illegal instruction
PC=0x57bcbc m=2 sigcode=2
instruction bytes: 0x62 0xf2 0x75 0x8 0x50 0xd0 0x90 0x90 0x90 0xc5 0xfa 0x7f 0x54 0x24 0x60 0x31

goroutine 103 gp=0x3e03089a2780 m=2 mp=0x3e0308527008 [running]:
simd/archsimd/internal/simd_test_test.TestDotProductQuadruple(0x3e037324bb08)
	/.../src/simd/archsimd/internal/simd_test/simd_test.go:1177 +0xfc fp=0x3e03085a3770 sp=0x3e03085a3688 pc=0x57bcbc
testing.tRunner(0x3e037324bb08, 0x614bc8)
	/.../src/testing/testing.go:2036 +0xea fp=0x3e03085a37c0 sp=0x3e03085a3770 pc=0x503daa
testing.(*T).Run.gowrap1()
	/.../src/testing/testing.go:2101 +0x1b fp=0x3e03085a37e0 sp=0x3e03085a37c0 pc=0x504f5b
runtime.goexit({})
	/.../src/runtime/asm_amd64.s:1771 +0x1 fp=0x3e03085a37e8 sp=0x3e03085a37e0 pc=0x499381
created by testing.(*T).Run in goroutine 1
	/.../src/testing/testing.go:2101 +0x4dd

```

**Comment by dr2chase** [comment]
It looks very likely that the internal cpu test for plain VNNI is busted, a separate bug.

**Comment by mpx** [comment]
Thanks, the master branch with fixes work for me at:
 7ecb1f3 [simd/archsimd: add HasAVX2() guards to tests that need them](https://github.com/golang/go/commit/7ecb1f36acab7b48d77991d58d456a34074a2d0e)
